In [6]:
bands = ['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B9', 'B11',
       'B12']

"""
a. Ratio 1 = b[i]-b[j]
b. Ratio 2 = b[i]/b[j]
c. Ratio 3 = (b[i]-b[j])/(b[i]+b[j])
"""
ratio_1= []
ratio_2 = []
ratio_3 = []

print(len(bands))

for i in range (len(bands)):
    for j in range (len(bands)):
        if i!=j:
            ratio_1.append(f"{bands[i]}-{bands[j]}")
            ratio_2.append(f"{bands[i]}/{bands[j]}")
            ratio_3.append(f"[{bands[i]}-{bands[j]}]/[{bands[i]}+{bands[j]}]")

print(len(ratio_1))
print(len(ratio_2))
print(ratio_3)

12
132
132
['[B1-B2]/[B1+B2]', '[B1-B3]/[B1+B3]', '[B1-B4]/[B1+B4]', '[B1-B5]/[B1+B5]', '[B1-B6]/[B1+B6]', '[B1-B7]/[B1+B7]', '[B1-B8]/[B1+B8]', '[B1-B8A]/[B1+B8A]', '[B1-B9]/[B1+B9]', '[B1-B11]/[B1+B11]', '[B1-B12]/[B1+B12]', '[B2-B1]/[B2+B1]', '[B2-B3]/[B2+B3]', '[B2-B4]/[B2+B4]', '[B2-B5]/[B2+B5]', '[B2-B6]/[B2+B6]', '[B2-B7]/[B2+B7]', '[B2-B8]/[B2+B8]', '[B2-B8A]/[B2+B8A]', '[B2-B9]/[B2+B9]', '[B2-B11]/[B2+B11]', '[B2-B12]/[B2+B12]', '[B3-B1]/[B3+B1]', '[B3-B2]/[B3+B2]', '[B3-B4]/[B3+B4]', '[B3-B5]/[B3+B5]', '[B3-B6]/[B3+B6]', '[B3-B7]/[B3+B7]', '[B3-B8]/[B3+B8]', '[B3-B8A]/[B3+B8A]', '[B3-B9]/[B3+B9]', '[B3-B11]/[B3+B11]', '[B3-B12]/[B3+B12]', '[B4-B1]/[B4+B1]', '[B4-B2]/[B4+B2]', '[B4-B3]/[B4+B3]', '[B4-B5]/[B4+B5]', '[B4-B6]/[B4+B6]', '[B4-B7]/[B4+B7]', '[B4-B8]/[B4+B8]', '[B4-B8A]/[B4+B8A]', '[B4-B9]/[B4+B9]', '[B4-B11]/[B4+B11]', '[B4-B12]/[B4+B12]', '[B5-B1]/[B5+B1]', '[B5-B2]/[B5+B2]', '[B5-B3]/[B5+B3]', '[B5-B4]/[B5+B4]', '[B5-B6]/[B5+B6]', '[B5-B7]/[B5+B7]', '[B5-B8]/[B5+B8]', '[B5-B8A]/[B5+B8A]', '[B5-B9]/[B5+B9]', '[B5-B11]/[B5+B11]', '[B5-B12]/[B5+B12]', '[B6-B1]/[B6+B1]', '[B6-B2]/[B6+B2]', '[B6-B3]/[B6+B3]', '[B6-B4]/[B6+B4]', '[B6-B5]/[B6+B5]', '[B6-B7]/[B6+B7]', '[B6-B8]/[B6+B8]', '[B6-B8A]/[B6+B8A]', '[B6-B9]/[B6+B9]', '[B6-B11]/[B6+B11]', '[B6-B12]/[B6+B12]', '[B7-B1]/[B7+B1]', '[B7-B2]/[B7+B2]', '[B7-B3]/[B7+B3]', '[B7-B4]/[B7+B4]', '[B7-B5]/[B7+B5]', '[B7-B6]/[B7+B6]', '[B7-B8]/[B7+B8]', '[B7-B8A]/[B7+B8A]', '[B7-B9]/[B7+B9]', '[B7-B11]/[B7+B11]', '[B7-B12]/[B7+B12]', '[B8-B1]/[B8+B1]', '[B8-B2]/[B8+B2]', '[B8-B3]/[B8+B3]', '[B8-B4]/[B8+B4]', '[B8-B5]/[B8+B5]', '[B8-B6]/[B8+B6]', '[B8-B7]/[B8+B7]', '[B8-B8A]/[B8+B8A]', '[B8-B9]/[B8+B9]', '[B8-B11]/[B8+B11]', '[B8-B12]/[B8+B12]', '[B8A-B1]/[B8A+B1]', '[B8A-B2]/[B8A+B2]', '[B8A-B3]/[B8A+B3]', '[B8A-B4]/[B8A+B4]', '[B8A-B5]/[B8A+B5]', '[B8A-B6]/[B8A+B6]', '[B8A-B7]/[B8A+B7]', '[B8A-B8]/[B8A+B8]', '[B8A-B9]/[B8A+B9]', '[B8A-B11]/[B8A+B11]', '[B8A-B12]/[B8A+B12]', '[B9-B1]/[B9+B1]', '[B9-B2]/[B9+B2]', '[B9-B3]/[B9+B3]', '[B9-B4]/[B9+B4]', '[B9-B5]/[B9+B5]', '[B9-B6]/[B9+B6]', '[B9-B7]/[B9+B7]', '[B9-B8]/[B9+B8]', '[B9-B8A]/[B9+B8A]', '[B9-B11]/[B9+B11]', '[B9-B12]/[B9+B12]', '[B11-B1]/[B11+B1]', '[B11-B2]/[B11+B2]', '[B11-B3]/[B11+B3]', '[B11-B4]/[B11+B4]', '[B11-B5]/[B11+B5]', '[B11-B6]/[B11+B6]', '[B11-B7]/[B11+B7]', '[B11-B8]/[B11+B8]', '[B11-B8A]/[B11+B8A]', '[B11-B9]/[B11+B9]', '[B11-B12]/[B11+B12]', '[B12-B1]/[B12+B1]', '[B12-B2]/[B12+B2]', '[B12-B3]/[B12+B3]', '[B12-B4]/[B12+B4]', '[B12-B5]/[B12+B5]', '[B12-B6]/[B12+B6]', '[B12-B7]/[B12+B7]', '[B12-B8]/[B12+B8]', '[B12-B8A]/[B12+B8A]', '[B12-B9]/[B12+B9]', '[B12-B11]/[B12+B11]']

In [1]:
import pandas as pd

chlorophyll = pd.read_csv ("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Chlorophyll.csv")
chlorophyll

,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,B7,...,result_Chlorophyll,Chlorophyll_Merged_How_many_n,county_name,sample_code,parameter,sample_depth,sample_depth_units,reporting_limit,units,method_name
0,2019-09-17 18:00:00,0.0624,0.1123,0.0881,0.0374,0.0552,0.0640,0.0888,0.0950,0.1004,...,3.06,1,Merced,C0919B0932,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
1,2020-09-16 19:00:00,0.0681,0.0494,0.0391,0.0484,0.0572,0.0528,0.0664,0.0598,0.0631,...,1.83,1,Merced,C0920B0678,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
2,2021-04-21 19:45:00,0.0791,0.0847,0.0622,0.0517,0.0608,0.0542,0.0754,0.0771,0.0713,...,1.52,1,Merced,C0421B0180,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
3,2021-06-25 18:45:00,0.1207,0.2477,0.2172,0.1576,0.1976,0.2160,0.2350,0.2393,0.2288,...,7.07,1,Merced,C0621B0304,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
4,2022-02-25 22:00:00,0.0915,0.1924,0.1699,0.1251,0.1539,0.1764,0.1875,0.1910,0.1903,...,0.82,1,Merced,C0222B0075,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,2023-08-22 17:13:00,0.0535,0.1462,0.1204,0.0581,0.0856,0.0890,0.1173,0.1680,0.1990,...,5.49,1,Yolo,ES0823B0534,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
542,2023-09-06 16:22:00,0.0469,0.1503,0.1177,0.0501,0.0764,0.0877,0.1184,0.1803,0.2028,...,3.30,1,Yolo,ES0923B0556,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
543,2019-10-07 17:15:00,0.0380,0.1134,0.0714,0.0352,0.0628,0.0531,0.0845,0.0913,0.1007,...,11.63,1,Yolo,C1019B0946,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
544,2021-08-02 15:13:00,0.0722,0.2492,0.2019,0.0845,0.1189,0.1340,0.1717,0.1995,0.2076,...,59.30,1,Colusa,ES0821B0116,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
545,2021-10-11 16:46:00,0.0474,0.1927,0.1681,0.0685,0.0953,0.1128,0.1386,0.1510,0.1564,...,32.20,1,Colusa,ES1021B0260,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H

In [3]:
df= chlorophyll.copy()
df

,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,B7,...,result_Chlorophyll,Chlorophyll_Merged_How_many_n,county_name,sample_code,parameter,sample_depth,sample_depth_units,reporting_limit,units,method_name
0,2019-09-17 18:00:00,0.0624,0.1123,0.0881,0.0374,0.0552,0.0640,0.0888,0.0950,0.1004,...,3.06,1,Merced,C0919B0932,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
1,2020-09-16 19:00:00,0.0681,0.0494,0.0391,0.0484,0.0572,0.0528,0.0664,0.0598,0.0631,...,1.83,1,Merced,C0920B0678,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
2,2021-04-21 19:45:00,0.0791,0.0847,0.0622,0.0517,0.0608,0.0542,0.0754,0.0771,0.0713,...,1.52,1,Merced,C0421B0180,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
3,2021-06-25 18:45:00,0.1207,0.2477,0.2172,0.1576,0.1976,0.2160,0.2350,0.2393,0.2288,...,7.07,1,Merced,C0621B0304,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
4,2022-02-25 22:00:00,0.0915,0.1924,0.1699,0.1251,0.1539,0.1764,0.1875,0.1910,0.1903,...,0.82,1,Merced,C0222B0075,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,2023-08-22 17:13:00,0.0535,0.1462,0.1204,0.0581,0.0856,0.0890,0.1173,0.1680,0.1990,...,5.49,1,Yolo,ES0823B0534,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
542,2023-09-06 16:22:00,0.0469,0.1503,0.1177,0.0501,0.0764,0.0877,0.1184,0.1803,0.2028,...,3.30,1,Yolo,ES0923B0556,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
543,2019-10-07 17:15:00,0.0380,0.1134,0.0714,0.0352,0.0628,0.0531,0.0845,0.0913,0.1007,...,11.63,1,Yolo,C1019B0946,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
544,2021-08-02 15:13:00,0.0722,0.2492,0.2019,0.0845,0.1189,0.1340,0.1717,0.1995,0.2076,...,59.30,1,Colusa,ES0821B0116,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H
545,2021-10-11 16:46:00,0.0474,0.1927,0.1681,0.0685,0.0953,0.1128,0.1386,0.1510,0.1564,...,32.20,1,Colusa,ES1021B0260,Chlorophyll a,1.0,Meters,0.5,ug/L,Std Method 10200 H

In [5]:
import pandas as pd
from itertools import permutations

bands = ['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B9', 'B11',
       'B12']

"""
a. Ratio 1 = b[i]-b[j]
b. Ratio 2 = b[i]/b[j]
c. Ratio 3 (Normalized Difference Band Ratio) = (b[i]-b[j])/(b[i]+b[j])
"""

diff_features1 = {}
diff_features2 = {}
diff_features3 = {}
eps = 1e-6

for b1, b2 in permutations(bands, 2):
    name1 = f"{b1}_minus_{b2}"
    name2 = f"{b1}_divide_{b2}"
    name3 = f"ND_{b1}_{b2}"
    
    diff_features1[name1] = df[b1] - df[b2]
    diff_features2[name2] = df[b1] / (df[b2]+ eps)
    diff_features3[name3] = (df[b1] - df[b2])/(df[b1] + df[b2]+ eps)
    

df_ratio1 = pd.concat(
    [
        df, 
        pd.DataFrame(diff_features1, index=df.index),
    ],
    axis=1
)


df_ratio2 = pd.concat(
    [
        df,
        pd.DataFrame(diff_features2, index=df.index)
    ],
    axis=1
)

df_ratio3 = pd.concat(
    [
        df, 
        pd.DataFrame(diff_features3, index=df.index)
    ],
    axis=1
)

#df_ratio1.to_csv(r"D:\\Shukra_sir\\MLAllTraining\\ForTraining\\bands_ratio_rough.csv")

df_ratio1

,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,B7,...,B12_minus_B2,B12_minus_B3,B12_minus_B4,B12_minus_B5,B12_minus_B6,B12_minus_B7,B12_minus_B8,B12_minus_B8A,B12_minus_B9,B12_minus_B11
0,2019-09-17 18:00:00,0.0624,0.1123,0.0881,0.0374,0.0552,0.0640,0.0888,0.0950,0.1004,...,0.0507,0.0329,0.0241,-0.0007,-0.0069,-0.0123,-0.0055,-0.0218,-0.0602,-0.0242
1,2020-09-16 19:00:00,0.0681,0.0494,0.0391,0.0484,0.0572,0.0528,0.0664,0.0598,0.0631,...,-0.0093,-0.0181,-0.0137,-0.0273,-0.0207,-0.0240,-0.0068,-0.0241,-0.0816,-0.0103
2,2021-04-21 19:45:00,0.0791,0.0847,0.0622,0.0517,0.0608,0.0542,0.0754,0.0771,0.0713,...,0.0105,0.0014,0.0080,-0.0132,-0.0149,-0.0091,-0.0038,-0.0200,-0.0961,-0.0225
3,2021-06-25 18:45:00,0.1207,0.2477,0.2172,0.1576,0.1976,0.2160,0.2350,0.2393,0.2288,...,0.0596,0.0196,0.0012,-0.0178,-0.0221,-0.0116,-0.0154,-0.0166,-0.0088,-0.0305
4,2022-02-25 22:00:00,0.0915,0.1924,0.1699,0.1251,0.1539,0.1764,0.1875,0.1910,0.1903,...,0.0448,0.0160,-0.0065,-0.0176,-0.0211,-0.0204,-0.0372,-0.0194,-0.0246,-0.0225
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,2023-08-22 17:13:00,0.0535,0.1462,0.1204,0.0581,0.0856,0.0890,0.1173,0.1680,0.1990,...,0.0623,0.0348,0.0314,0.0031,-0.0476,-0.0786,-0.1022,-0.0840,-0.1411,-0.0258
542,2023-09-06 16:22:00,0.0469,0.1503,0.1177,0.0501,0.0764,0.0877,0.1184,0.1803,0.2028,...,0.0676,0.0413,0.0300,-0.0007,-0.0626,-0.0851,-0.0934,-0.0796,-0.1290,-0.0326
543,2019-10-07 17:15:00,0.0380,0.1134,0.0714,0.0352,0.0628,0.0531,0.0845,0.0913,0.1007,...,0.0362,0.0086,0.0183,-0.0131,-0.0199,-0.0293,-0.0517,-0.0506,-0.1067,-0.0420
544,2021-08-02 15:13:00,0.0722,0.2492,0.2019,0.0845,0.1189,0.1340,0.1717,0.1995,0.2076,...,0.1174,0.0830,0.0679,0.0302,0.0024,-0.0057,-0.0235,-0.0122,-0.0216,-0.0473
545,2021-10-11 16:46:00,0.0474,0.1927,0.1681,0.0685,0.0953,0.1128,0.1386,0.1510,0.1564,...,0.0996,0.0728,0.0553,0.0295,0.0171,0.0117,0.0021,0.0024,-0.0009,-0.0246

In [ ]:
import pandas as pd

target = "result_Chlorophyll"

diff_corr = {}

for col in df_ratio1.columns:
    if "_minus_" in col:   # only difference features
        diff_corr[col] = df_ratio1[col].corr(df_ratio1[target], method= "spearman")

df_diff_corr = (
    pd.DataFrame.from_dict(diff_corr, orient="index", columns=["spearman_corr"])
    .abs()
    .sort_values("spearman_corr", ascending=False)
)

df_diff_corr.to_csv(
    r"D:\Shukra_sir\MLAllTraining\ForTraining\Band Ratio and Correlations\corr_band_difference_spearman.csv"
)

In [1]:
#ML TRAINING STAGE 1: Bands Ratios calculation for each params

import pandas as pd

chlorophyll = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Chlorophyll.csv")
tss = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\TSS.csv")
doc = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\DOC.csv")
pheophytin = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Pheophytin.csv")

output_folder_chlorophyll ="D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For Chlorophyll"
output_folder_tss = "D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For TSS"
output_folder_doc = "D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For DOC"
output__folder_pheophytin = "D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For Pheophytin"

In [ ]:
#Continued STAGE 1

from itertools import permutations
import os

PARAMETERS = ['Chlorophyll', 'DOC', 'TSS', 'Pheophytin']

"""
 Visible Bands

These are in the visible light spectrum (~400–700 nm) — the colors the human eye can see:

B02 – Blue (490 nm)

B03 – Green (560 nm)

B04 – Red (665 nm)
These are typically used for true-color images and basic water/vegetation analyses
"""

"""
Red Edge

B5, B6, B7
"""

"""
Near Infrared
B8 and B8A
"""

"""
For Detecting Water vapour
B9
"""

"""
SWIR
B11, B12
Often excluded in Water Quality studies
"""


def BandsRatioAndCorr(parameter):
    bands = ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B9']
    
    """
    a. Ratio 1 = b[i]-b[j]
    b. Ratio 2 = b[i]/b[j]
    c. Ratio 3 (Normalized Difference Band Ratio) = (b[i]-b[j])/(b[i]+b[j])
    """
    
    diff_features1 = {}
    diff_features2 = {}
    diff_features3 = {}
    eps = 1e-6

    if parameter == "Chlorophyll":
        df = chlorophyll
        output = output_folder_chlorophyll
        target = "result_Chlorophyll"

        outfile_file_path_BandRatio1 = os.path.join(output, f"Chlorophyll_BandRatio1.csv")
        outfile_file_path_BandRatio2= os.path.join(output, f"Chlorophyll_BandRatio2.csv")
        outfile_file_path_BandRatio3 = os.path.join(output, f"Chlorophyll_BandRatio3.csv")
        
        outfile_file_path_CorrBR1 = os.path.join(output, f"Chlorophyll_BR1Corr.csv")
        outfile_file_path_CorrBR2 = os.path.join(output, f"Chlorophyll_BR2Corr.csv")
        outfile_file_path_CorrBR3 = os.path.join(output, f"Chlorophyll_BR3Corr.csv")
        
    elif parameter == "DOC":
        df = doc
        output = output_folder_doc
        target = "result_DOC"


        outfile_file_path_BandRatio1 = os.path.join(output, f"DOC_BandRatio1.csv")
        outfile_file_path_BandRatio2 = os.path.join(output, f"DOC_BandRatio2.csv")
        outfile_file_path_BandRatio3 = os.path.join(output, f"DOC_BandRatio3.csv")
        
        outfile_file_path_CorrBR1 = os.path.join(output, f"DOC_BR1Corr.csv")
        outfile_file_path_CorrBR2 = os.path.join(output, f"DOC_BR2Corr.csv")
        outfile_file_path_CorrBR3 = os.path.join(output, f"DOC_BR3Corr.csv")

    elif parameter == 'TSS':
        df = tss
        output = output_folder_tss
        target = "result_TSS"

        outfile_file_path_BandRatio1 = os.path.join(output, f"TSS_BandRatio1.csv")
        outfile_file_path_BandRatio2= os.path.join(output, f"TSS_BandRatio2.csv")
        outfile_file_path_BandRatio3 = os.path.join(output, f"TSS_BandRatio3.csv")
        
        outfile_file_path_CorrBR1 = os.path.join(output, f"TSS_BR1Corr.csv")
        outfile_file_path_CorrBR2 = os.path.join(output, f"TSS_BR2Corr.csv")
        outfile_file_path_CorrBR3 = os.path.join(output, f"TSS_BR3Corr.csv")
        
    elif parameter == 'Pheophytin':
        df =  pheophytin
        output = output__folder_pheophytin
        target = "result_Pheophytin"

        outfile_file_path_BandRatio1 = os.path.join(output, f"Pheophytin_BandRatio1.csv")        
        outfile_file_path_BandRatio2 = os.path.join(output, f"Pheophytin_BandRatio2.csv")
        outfile_file_path_BandRatio3 = os.path.join(output, f"Pheophytin_BandRatio3.csv")

        outfile_file_path_CorrBR1 = os.path.join(output, f"Pheophytin_BR1Corr.csv")
        outfile_file_path_CorrBR2 = os.path.join(output, f"Pheophytin_BR2Corr.csv")
        outfile_file_path_CorrBR3 = os.path.join(output, f"Pheophytin_BR3Corr.csv")
        
    
    for b1, b2 in permutations(bands, 2):
        name1 = f"{b1}_minus_{b2}"
        name2 = f"{b1}_div_{b2}"
        name3 = f"ND_{b1}_{b2}"
        
        diff_features1[name1] = df[b1] - df[b2]
        diff_features2[name2] = df[b1] / (df[b2]+ eps)
        diff_features3[name3] = (df[b1] - df[b2])/(df[b1] + df[b2]+ eps)
    
    df_ratio1 = pd.concat(
    [
        df, 
        pd.DataFrame(diff_features1, index=df.index),
    ],
    axis=1
    )

    df_ratio2 = pd.concat(
    [
        df,
        pd.DataFrame(diff_features2, index=df.index)
    ],
    axis=1
    )
    
    df_ratio3 = pd.concat(
    [
        df, 
        pd.DataFrame(diff_features3, index=df.index)
    ],
    axis=1
    )
    
    print('Saving for Band Ratio 1')
    df_ratio1.to_csv(outfile_file_path_BandRatio1)
    print('Saving for Band Ratio 2')
    df_ratio2.to_csv(outfile_file_path_BandRatio2)
    print('Saving for Band Ratio 3')
    df_ratio3.to_csv(outfile_file_path_BandRatio3)


    #FOR Band Ratio1
    rowsBR1 = []
    for col in df_ratio1.columns:
        if "_minus_" in col:
            rowsBR1.append({
                "feature": col,
                "pearson_corr": df_ratio1[col].corr(df_ratio1[target], method="pearson"),
                "spearman_corr": df_ratio1[col].corr(df_ratio1[target], method="spearman"),
            })
        
    df_diff_corrBR1 = (pd.DataFrame(rowsBR1)
    .set_index("feature")
    .abs()
    .sort_values("spearman_corr", ascending=False)
    )
    
    print("Saving Correlations for Band Ratio 1")
    df_diff_corrBR1.to_csv(outfile_file_path_CorrBR1)
    print("Done: Correlations for Band Ratio 1")


    #For Band Ratio 2
    rowsBR2 = []
    for col in df_ratio2.columns:
        if "_div_" in col:
            rowsBR2.append({
                "feature": col,
                "pearson_corr": df_ratio2[col].corr(df_ratio2[target], method="pearson"),
                "spearman_corr": df_ratio2[col].corr(df_ratio2[target], method="spearman"),
            })
        
    df_diff_corrBR2 = (pd.DataFrame(rowsBR2)
    .set_index("feature")
    .abs()
    .sort_values("spearman_corr", ascending=False)
    )
    
    print("Saving Correlations for Band Ratio 2")
    df_diff_corrBR2.to_csv(outfile_file_path_CorrBR2)
    print('Saving For Band Ratio 2')




    #For Band Ratio 3
    rowsBR3 = []
    for col in df_ratio3.columns:
        if col.startswith("ND_"):
            rowsBR3.append({
                "feature": col,
                "pearson_corr": df_ratio3[col].corr(df_ratio3[target], method="pearson"),
                "spearman_corr": df_ratio3[col].corr(df_ratio3[target], method="spearman"),
            })
        
    df_diff_corrBR3 = (pd.DataFrame(rowsBR3)
    .set_index("feature")
    .abs()
    .sort_values("spearman_corr", ascending=False)
    )
    
    print("Saving Correlations for Band Ratio 3")
    df_diff_corrBR3.to_csv(outfile_file_path_CorrBR3)
    print('Saving For Band Ratio 3')


PARAMETERS = ['Chlorophyll', 'DOC', 'TSS', 'Pheophytin']

#param = PARAMETERS[0]
#BandsRatioAndCorr(param)

#param = PARAMETERS[1]
#BandsRatioAndCorr(param)

#param = PARAMETERS[2]
#BandsRatioAndCorr(param)


param = PARAMETERS[3]
BandsRatioAndCorr(param)

Saving for Band Ratio 1
Saving for Band Ratio 2
Saving for Band Ratio 3
Saving Correlations for Band Ratio 1
Done: Correlations for Band Ratio 1
Saving Correlations for Band Ratio 2
Saving For Band Ratio 2
Saving Correlations for Band Ratio 3
Saving For Band Ratio 3

In [1]:
#SPEARMAN AND PEARSON WITH P VALUE

# STAGE 1 [modified]

import pandas as pd

chlorophyll = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Chlorophyll.csv")
tss = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\TSS.csv")
doc = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\DOC.csv")
pheophytin = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Pheophytin.csv")

output_folder_chlorophyll ="D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For Chlorophyll"
output_folder_tss = "D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For TSS"
output_folder_doc = "D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For DOC"
output__folder_pheophytin = "D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For Pheophytin"

In [5]:
#SPEARMAN AND PEARSON WITH P VALUE

# STAGE 1 [modified]

from itertools import permutations
import os
from scipy.stats import pearsonr, spearmanr
import numpy as np

#ML TRAINING STAGE 1: Bands Ratios calculation for each params



PARAMETERS = ['Chlorophyll', 'DOC', 'TSS', 'Pheophytin']

"""
 Visible Bands

These are in the visible light spectrum (~400–700 nm) — the colors the human eye can see:

B02 – Blue (490 nm)

B03 – Green (560 nm)

B04 – Red (665 nm)
These are typically used for true-color images and basic water/vegetation analyses
"""

"""
Red Edge

B5, B6, B7
"""

"""
Near Infrared
B8 and B8A
"""

"""
For Detecting Water vapour
B9
"""

"""
SWIR
B11, B12
Often excluded in Water Quality studies
"""


def BandsRatioAndCorr(parameter):
    bands = ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B9']
    
    """
    a. Ratio 1 = b[i]-b[j]
    b. Ratio 2 = b[i]/b[j]
    c. Ratio 3 (Normalized Difference Band Ratio) = (b[i]-b[j])/(b[i]+b[j])
    """
    
    diff_features1 = {}
    diff_features2 = {}
    diff_features3 = {}
    eps = 1e-6

    if parameter == "Chlorophyll":
        df = chlorophyll
        output = output_folder_chlorophyll
        target = "result_Chlorophyll"

        outfile_file_path_BandRatio1 = os.path.join(output, f"NewChlorophyll_BandRatio1.csv")
        outfile_file_path_BandRatio2= os.path.join(output, f"NewChlorophyll_BandRatio2.csv")
        outfile_file_path_BandRatio3 = os.path.join(output, f"NewChlorophyll_BandRatio3.csv")
        
        outfile_file_path_CorrBR1 = os.path.join(output, f"WithP_Chlorophyll_BR1Corr.csv")
        outfile_file_path_CorrBR2 = os.path.join(output, f"WithP_Chlorophyll_BR2Corr.csv")
        outfile_file_path_CorrBR3 = os.path.join(output, f"WithP_Chlorophyll_BR3Corr.csv")
        
    elif parameter == "DOC":
        df = doc
        output = output_folder_doc
        target = "result_DOC"


        outfile_file_path_BandRatio1 = os.path.join(output, f"NewDOC_BandRatio1.csv")
        outfile_file_path_BandRatio2 = os.path.join(output, f"NewDOC_BandRatio2.csv")
        outfile_file_path_BandRatio3 = os.path.join(output, f"NewDOC_BandRatio3.csv")
        
        outfile_file_path_CorrBR1 = os.path.join(output, f"WithP_DOC_BR1Corr.csv")
        outfile_file_path_CorrBR2 = os.path.join(output, f"WithP_DOC_BR2Corr.csv")
        outfile_file_path_CorrBR3 = os.path.join(output, f"WithP_DOC_BR3Corr.csv")

    elif parameter == 'TSS':
        df = tss
        output = output_folder_tss
        target = "result_TSS"

        outfile_file_path_BandRatio1 = os.path.join(output, f"NewTSS_BandRatio1.csv")
        outfile_file_path_BandRatio2= os.path.join(output, f"NewTSS_BandRatio2.csv")
        outfile_file_path_BandRatio3 = os.path.join(output, f"NewTSS_BandRatio3.csv")
        
        outfile_file_path_CorrBR1 = os.path.join(output, f"WithP_TSS_BR1Corr.csv")
        outfile_file_path_CorrBR2 = os.path.join(output, f"WithP_TSS_BR2Corr.csv")
        outfile_file_path_CorrBR3 = os.path.join(output, f"WithP_TSS_BR3Corr.csv")
        
    elif parameter == 'Pheophytin':
        df =  pheophytin
        output = output__folder_pheophytin
        target = "result_Pheophytin"

        outfile_file_path_BandRatio1 = os.path.join(output, f"NewPheophytin_BandRatio1.csv")        
        outfile_file_path_BandRatio2 = os.path.join(output, f"NewPheophytin_BandRatio2.csv")
        outfile_file_path_BandRatio3 = os.path.join(output, f"NewPheophytin_BandRatio3.csv")

        outfile_file_path_CorrBR1 = os.path.join(output, f"WithP_Pheophytin_BR1Corr.csv")
        outfile_file_path_CorrBR2 = os.path.join(output, f"WithP_Pheophytin_BR2Corr.csv")
        outfile_file_path_CorrBR3 = os.path.join(output, f"WithP_Pheophytin_BR3Corr.csv")
        
    
    for b1, b2 in permutations(bands, 2):
        name1 = f"{b1}_minus_{b2}"
        name2 = f"{b1}_div_{b2}"
        name3 = f"ND_{b1}_{b2}"
        
        diff_features1[name1] = df[b1] - df[b2]
        diff_features2[name2] = df[b1] / (df[b2]+ eps)
        diff_features3[name3] = (df[b1] - df[b2])/(df[b1] + df[b2]+ eps)
    
    df_ratio1 = pd.concat(
    [
        df, 
        pd.DataFrame(diff_features1, index=df.index),
    ],
    axis=1
    )

    df_ratio2 = pd.concat(
    [
        df,
        pd.DataFrame(diff_features2, index=df.index)
    ],
    axis=1
    )
    
    df_ratio3 = pd.concat(
    [
        df, 
        pd.DataFrame(diff_features3, index=df.index)
    ],
    axis=1
    )
    
    print('Saving for Band Ratio 1')
    df_ratio1.to_csv(outfile_file_path_BandRatio1)
    print('Saving for Band Ratio 2')
    df_ratio2.to_csv(outfile_file_path_BandRatio2)
    print('Saving for Band Ratio 3')
    df_ratio3.to_csv(outfile_file_path_BandRatio3)


    #FOR Band Ratio1
    rowsBR1 = []
    for col in df_ratio1.columns:
        if "_minus_" in col:

            x = df_ratio1[col]
            y = df_ratio1[target]
            mask = x.notna() & y.notna()
            
            if mask.sum() < 3:
                pear_corr = pear_p = spear_corr = spear_p = np.nan

            else:
                pear_corr, pear_p = pearsonr(x[mask], y[mask])
                spear_corr, spear_p = spearmanr(x[mask], y[mask])

            rowsBR1.append({
            "feature": col,
            "pearson_corr": pear_corr,
            "pearson_pval": pear_p,      # ← added
            "spearman_corr": spear_corr,
            "spearman_pval": spear_p,    # ← added
            })


            """
            rowsBR1.append({
                "feature": col,
                "pearson_corr": df_ratio1[col].corr(df_ratio1[target], method="pearson"),
                "spearman_corr": df_ratio1[col].corr(df_ratio1[target], method="spearman"),
            })"""
        
    df_diff_corrBR1 = (pd.DataFrame(rowsBR1)
    .set_index("feature")
    .abs()
    .sort_values("spearman_corr", ascending=False)
    )
    
    print("Saving Correlations for Band Ratio 1")
    df_diff_corrBR1.to_csv(outfile_file_path_CorrBR1)
    print("Done: Correlations for Band Ratio 1")

    # drop NaNs pairwise (IMPORTANT for p-values)
    


    #For Band Ratio 2
    rowsBR2 = []
    for col in df_ratio2.columns:
        if "_div_" in col:

            x = df_ratio2[col]
            y = df_ratio2[target]
            mask = x.notna() & y.notna()
            
            if mask.sum() < 3:
                pear_corr = pear_p = spear_corr = spear_p = np.nan

            else:
                pear_corr, pear_p = pearsonr(x[mask], y[mask])
                spear_corr, spear_p = spearmanr(x[mask], y[mask])

            rowsBR2.append({
            "feature": col,
            "pearson_corr": pear_corr,
            "pearson_pval": pear_p,      # ← added
            "spearman_corr": spear_corr,
            "spearman_pval": spear_p,    # ← added
            })

            """
            rowsBR2.append({
                "feature": col,
                "pearson_corr": df_ratio2[col].corr(df_ratio2[target], method="pearson"),
                "spearman_corr": df_ratio2[col].corr(df_ratio2[target], method="spearman"),
            })
            """
        
    df_diff_corrBR2 = (pd.DataFrame(rowsBR2)
    .set_index("feature")
    .abs()
    .sort_values("spearman_corr", ascending=False)
    )
    
    print("Saving Correlations for Band Ratio 2")
    df_diff_corrBR2.to_csv(outfile_file_path_CorrBR2)
    print('Saving For Band Ratio 2')




    #For Band Ratio 3
    rowsBR3 = []
    for col in df_ratio3.columns:
        if col.startswith("ND_"):

            x = df_ratio3[col]
            y = df_ratio3[target]
            mask = x.notna() & y.notna()
            
            if mask.sum() < 3:
                pear_corr = pear_p = spear_corr = spear_p = np.nan

            else:
                pear_corr, pear_p = pearsonr(x[mask], y[mask])
                spear_corr, spear_p = spearmanr(x[mask], y[mask])

            rowsBR3.append({
            "feature": col,
            "pearson_corr": pear_corr,
            "pearson_pval": pear_p,      # ← added
            "spearman_corr": spear_corr,
            "spearman_pval": spear_p,    # ← added
            })

            """
            rowsBR3.append({
                "feature": col,
                "pearson_corr": df_ratio3[col].corr(df_ratio3[target], method="pearson"),
                "spearman_corr": df_ratio3[col].corr(df_ratio3[target], method="spearman"),
            })"""
        
    df_diff_corrBR3 = (pd.DataFrame(rowsBR3)
    .set_index("feature")
    .abs()
    .sort_values("spearman_corr", ascending=False)
    )
    
    print("Saving Correlations for Band Ratio 3")
    df_diff_corrBR3.to_csv(outfile_file_path_CorrBR3)
    print('Saving For Band Ratio 3')


PARAMETERS = ['Chlorophyll', 'DOC', 'TSS', 'Pheophytin']

param = PARAMETERS[0]
BandsRatioAndCorr(param)

#param = PARAMETERS[1]
#BandsRatioAndCorr(param)

#param = PARAMETERS[2]
#BandsRatioAndCorr(param)


#param = PARAMETERS[3]
#BandsRatioAndCorr(param)

Saving for Band Ratio 1
Saving for Band Ratio 2
Saving for Band Ratio 3
Saving Correlations for Band Ratio 1
Done: Correlations for Band Ratio 1
Saving Correlations for Band Ratio 2
Saving For Band Ratio 2
Saving Correlations for Band Ratio 3
Saving For Band Ratio 3

In [8]:

bands = ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B9']

for b1, b2 in permutations(bands, 2):
    name1 = f"{b1}_minus_{b2}"
    print(name1)

B2_minus_B3
B2_minus_B4
B2_minus_B5
B2_minus_B6
B2_minus_B7
B2_minus_B8
B2_minus_B8A
B2_minus_B9
B3_minus_B2
B3_minus_B4
B3_minus_B5
B3_minus_B6
B3_minus_B7
B3_minus_B8
B3_minus_B8A
B3_minus_B9
B4_minus_B2
B4_minus_B3
B4_minus_B5
B4_minus_B6
B4_minus_B7
B4_minus_B8
B4_minus_B8A
B4_minus_B9
B5_minus_B2
B5_minus_B3
B5_minus_B4
B5_minus_B6
B5_minus_B7
B5_minus_B8
B5_minus_B8A
B5_minus_B9
B6_minus_B2
B6_minus_B3
B6_minus_B4
B6_minus_B5
B6_minus_B7
B6_minus_B8
B6_minus_B8A
B6_minus_B9
B7_minus_B2
B7_minus_B3
B7_minus_B4
B7_minus_B5
B7_minus_B6
B7_minus_B8
B7_minus_B8A
B7_minus_B9
B8_minus_B2
B8_minus_B3
B8_minus_B4
B8_minus_B5
B8_minus_B6
B8_minus_B7
B8_minus_B8A
B8_minus_B9
B8A_minus_B2
B8A_minus_B3
B8A_minus_B4
B8A_minus_B5
B8A_minus_B6
B8A_minus_B7
B8A_minus_B8
B8A_minus_B9
B9_minus_B2
B9_minus_B3
B9_minus_B4
B9_minus_B5
B9_minus_B6
B9_minus_B7
B9_minus_B8
B9_minus_B8A

In [1]:
import pandas as pd

df_sample = pd.DataFrame({
    "Band_Ratio": [1, 2, 3, 4, 5],
    "Chlorophyll": [2, 4, 5, 4, 10]
})
df_sample

   Band_Ratio  Chlorophyll
0           1            2
1           2            4
2           3            5
3           4            4
4           5           10

In [3]:
pearson_corr = df_sample["Band_Ratio"].corr(df_sample["Chlorophyll"], method="pearson")
pearson_corr

np.float64(0.8432740427115678)

In [4]:
spearman_corr = df_sample["Band_Ratio"].corr(df_sample["Chlorophyll"], method="spearman")
spearman_corr

np.float64(0.8207826816681233)

In [ ]:
from scipy.stats import pearsonr, spearmanr

A = [1, 2, 3, 4, 5]
B = [2, 4, 5, 4, 10]

pearson_r, pearson_p = pearsonr(A, B)
spearman_r, spearman_p = spearmanr(A, B)

pearson_r, spearman_r

(np.float64(0.8432740427115679), np.float64(0.8207826816681233))