In [2]:
#FOR AUGMENTED_NEW

import pandas as pd
import numpy as np

aug_factor = 3 #augmented has been done initially for aug_factor = 2, then for aug_factor = 3

doc_train_augmented = pd.read_csv (f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TRAIN_AUG{aug_factor}.csv")
doc_test = pd.read_csv(f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TEST_AUG{aug_factor}.csv")

doc_train_augmented.shape, doc_test.shape

((2732, 55), (171, 55))

In [3]:
doc_train_augmented ['result_DOC_log'] = np.log1p (doc_train_augmented ['result_DOC'])
doc_test ['result_DOC_log'] = np.log1p (doc_test ['result_DOC'])
doc_train_augmented

,Unnamed: 0,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,...,B3_div_B2,ND_B4_B3,ND_B2_B3,ND_B6_B8,day_of_year,doy_sin,doy_cos,hour_sin,hour_cos,result_DOC_log
0,0,2024-05-08 14:00:00,0.037800,0.168600,0.105100,0.040100,0.063600,0.050700,0.094400,0.220200,...,1.585995,-0.112860,-0.226613,-0.130503,129,0.796183,-0.605056,-0.500000,-0.866025,0.741937
1,1,2019-08-20 15:00:00,0.068100,0.144400,0.130300,0.057300,0.075900,0.073100,0.098200,0.105800,...,1.324584,-0.018792,-0.139639,0.109596,232,-0.752667,-0.658402,-0.707107,-0.707107,1.308333
2,2,2022-02-01 20:55:00,0.015100,0.165100,0.131400,0.033200,0.053800,0.056300,0.095100,0.146200,...,1.620433,0.022706,-0.236779,-0.071156,32,0.523416,0.852078,-0.866025,0.500000,0.741937
3,3,2018-11-06 21:25:00,0.007100,0.026500,0.019000,0.019100,0.030400,0.022600,0.023400,0.014200,...,1.591540,-0.147167,-0.228278,-0.080904,310,-0.811539,0.584298,-0.707107,0.707107,1.481605
4,4,2018-11-06 19:20:00,0.001400,0.010400,0.010300,0.013300,0.020300,0.008900,0.006200,0.000000,...,1.526201,-0.390398,-0.208327,0.000000,310,-0.811539,0.584298,-0.965926,0.258819,1.193922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,2727,2019-08-20 16:00:00,0.160048,0.347841,0.301870,0.194634,0.206942,0.225023,0.253643,0.254485,...,1.063231,0.041857,-0.030649,-0.043629,232,-0.752667,-0.658402,-0.866025,-0.500000,1.536867
2728,2728,2021-08-17 15:45:00,0.106466,0.173790,0.156926,0.132880,0.156900,0.169819,0.182550,0.194755,...,1.180757,0.039542,-0.082891,0.040882,229,-0.717677,-0.696376,-0.707107,-0.707107,1.547563
2729,2729,2023-05-24 17:43:00,0.041518,0.115512,0.094602,0.046671,0.063934,0.065133,0.090442,0.112315,...,1.369847,0.009291,-0.156073,-0.035528,144,0.615285,-0.788305,-0.965926,-0.258819,1.410987
2730,2730,2018-06-19 19:24:00,0.051536,0.046751,0.038356,0.069572,0.074987,0.053739,0.051703,0.041847,...,1.077817,-0.165069,-0.037458,-0.020389,170,0.213521,-0.976938,-0.965926,0.258819,1.029619
2731,2731,2019-09-17 15:50:00,0.048440,0.116872,0.101207,0.040520,0.053809,0.062569,0.082519,0.073375,...,1.327936,0.075266,-0.140880,0.122702,260,-0.972118,-0.234491,-0.707107,-0.707107,1.280934

In [4]:
TARGET = "result_DOC_log" #FOR DOC
TARGET1 = "result_DOC"

input_features = [#'B1',
                  'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 
                'B9',
               "B4_minus_B3",
               
               "B4_div_B3", 
               
               "ND_B4_B3", 
               
               'Temperature', 'DewPoint', 'v10n', 
               'doy_sin', 'doy_cos', 
                
               'latitude', 'longitude'
               ]

X_train = doc_train_augmented[input_features]
y_train = doc_train_augmented[TARGET]

X_test = doc_test[input_features]
y_test = doc_test[TARGET]

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2732, 19), (2732,), (171, 19), (171,))

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
import catboost
print(catboost.__version__)

1.2.7

In [12]:
from catboost import CatBoostRegressor
import numpy as np

X = np.random.rand(1000, 10)
y = np.random.rand(1000)

model = CatBoostRegressor(
    iterations=50,
    task_type="GPU",
    devices='0',
    verbose=0
)

model.fit(X, y)
print("CatBoost GPU training successful ✅")

CatBoost GPU training successful ✅

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:

baseline_CBR = CatBoostRegressor(
    iterations=3600,         # baseline, can increase later
    learning_rate=0.03,      # baseline
    depth=4,                 # baseline
    l2_leaf_reg=3,            # L2 regularization, prevents overfitting
    task_type="CPU",         # GPU training
    devices='0',             # first GPU
    random_seed=42,
    verbose=100              # log progress every 100 iterations
)

baseline_CBR.fit(X_train_scaled, y_train)

y_pred = baseline_CBR.predict(X_test_scaled)

print("R² for DOC for log scaled | CatBoost Regressor:", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | CatBoost Regressor:", r2_score(y_test_real, y_pred_orig))


# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)


print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

0:	learn: 0.3687761	total: 3.03ms	remaining: 10.9s
100:	learn: 0.2485162	total: 90.6ms	remaining: 3.14s
200:	learn: 0.2178294	total: 159ms	remaining: 2.68s
300:	learn: 0.1933255	total: 231ms	remaining: 2.53s
400:	learn: 0.1731283	total: 302ms	remaining: 2.41s
500:	learn: 0.1570845	total: 376ms	remaining: 2.33s
600:	learn: 0.1446297	total: 444ms	remaining: 2.22s
700:	learn: 0.1334584	total: 513ms	remaining: 2.12s
800:	learn: 0.1233706	total: 580ms	remaining: 2.03s
900:	learn: 0.1151164	total: 646ms	remaining: 1.94s
1000:	learn: 0.1081343	total: 716ms	remaining: 1.86s
1100:	learn: 0.1016998	total: 790ms	remaining: 1.79s
1200:	learn: 0.0961495	total: 857ms	remaining: 1.71s
1300:	learn: 0.0907791	total: 926ms	remaining: 1.64s
1400:	learn: 0.0859513	total: 991ms	remaining: 1.55s
1500:	learn: 0.0814117	total: 1.06s	remaining: 1.48s
1600:	learn: 0.0771182	total: 1.13s	remaining: 1.41s
1700:	learn: 0.0732025	total: 1.19s	remaining: 1.33s
1800:	learn: 0.0694239	total: 1.27s	remaining: 1.27s
1900:	learn: 0.0658062	total: 1.34s	remaining: 1.2s
2000:	learn: 0.0628349	total: 1.41s	remaining: 1.13s
2100:	learn: 0.0602056	total: 1.48s	remaining: 1.06s
2200:	learn: 0.0575372	total: 1.56s	remaining: 990ms
2300:	learn: 0.0549755	total: 1.62s	remaining: 917ms
2400:	learn: 0.0524971	total: 1.69s	remaining: 844ms
2500:	learn: 0.0503478	total: 1.76s	remaining: 773ms
2600:	learn: 0.0482342	total: 1.83s	remaining: 702ms
2700:	learn: 0.0462298	total: 1.89s	remaining: 630ms
2800:	learn: 0.0444381	total: 1.96s	remaining: 560ms
2900:	learn: 0.0426613	total: 2.03s	remaining: 489ms
3000:	learn: 0.0409116	total: 2.1s	remaining: 418ms
3100:	learn: 0.0394145	total: 2.17s	remaining: 349ms
3200:	learn: 0.0380068	total: 2.23s	remaining: 278ms
3300:	learn: 0.0367617	total: 2.3s	remaining: 208ms
3400:	learn: 0.0355055	total: 2.37s	remaining: 139ms
3500:	learn: 0.0341406	total: 2.43s	remaining: 68.8ms
3599:	learn: 0.0329352	total: 2.5s	remaining: 0us
R² for DOC for log scaled | CatBoost Regressor: 0.6916158541368884
R² for DOC on normal scaled | CatBoost Regressor: 0.6216256792038427
R² for DOC on normal: 0.6216256792038427
Final metrics on NORMAL scale (after inverse log):
R²   : 0.6216
MSE  : 1.1799
RMSE : 1.0863
MAE  : 0.6654

In [ ]:
#HYPERPARAM TUNING WITH OPTUNA -

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
import optuna 
scaler = StandardScaler()
X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:

kf = KFold(n_splits=3, shuffle=True, random_state=42)

def objective_Kfold_withScaled(trial):
    # Hyperparameters to tune
    params = {
        'iterations': trial.suggest_int('iterations', 1800, 3900, step=100),
        'learning_rate': trial.suggest_float('learning_rate', 0.02, 0.04, log=True),
        
        'depth': 4,
        
        'l2_leaf_reg': trial.suggest_int('l2_leaf_reg', 1, 10),
        
        
        'task_type': 'CPU',   
        'verbose': 0,
        'random_seed': 42
    }
    
    # Manual CV loop

    r2_scores = []
    for train_idx, valid_idx in kf.split(X_train_scaled):
        X_tr, X_val = X_train_scaled[train_idx], X_train_scaled[valid_idx]
        y_tr, y_val = y_train[train_idx], y_train[valid_idx]

        model = CatBoostRegressor(**params)
        model.fit(
            X_tr, y_tr,
            eval_set=(X_val, y_val),
            early_stopping_rounds=100,
            verbose=0
        )

        y_pred = model.predict(X_val)
        r2_scores.append(r2_score(y_val, y_pred))

    return np.mean(r2_scores)

In [22]:
# 3️⃣ Run Optuna study
# --------------------------
study = optuna.create_study(direction="maximize", study_name = "Catboost_study_CPU", sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective_Kfold_withScaled, n_trials=50, show_progress_bar=True, n_jobs=-1)

[I 2026-01-28 10:17:03,827] A new study created in memory with name: Catboost_study_CPU
Best trial: 5. Best value: 0.895808:   2%|▏         | 1/50 [00:17<14:04, 17.23s/it]

[I 2026-01-28 10:17:21,053] Trial 5 finished with value: 0.8958075155357753 and parameters: {'iterations': 1900, 'learning_rate': 0.03450279118514946, 'l2_leaf_reg': 9}. Best is trial 5 with value: 0.8958075155357753.

Best trial: 5. Best value: 0.895808:   4%|▍         | 2/50 [00:18<06:02,  7.56s/it]

[I 2026-01-28 10:17:21,841] Trial 4 finished with value: 0.8786363563492897 and parameters: {'iterations': 2000, 'learning_rate': 0.025191085451999672, 'l2_leaf_reg': 7}. Best is trial 5 with value: 0.8958075155357753.

Best trial: 15. Best value: 0.924239:   6%|▌         | 3/50 [00:20<03:58,  5.08s/it]

[I 2026-01-28 10:17:23,978] Trial 15 finished with value: 0.9242390071261423 and parameters: {'iterations': 2300, 'learning_rate': 0.02724712645358446, 'l2_leaf_reg': 1}. Best is trial 15 with value: 0.9242390071261423.

Best trial: 15. Best value: 0.924239:   8%|▊         | 4/50 [00:21<02:36,  3.41s/it]

[I 2026-01-28 10:17:24,831] Trial 11 finished with value: 0.9111807637766933 and parameters: {'iterations': 2300, 'learning_rate': 0.03528009804562942, 'l2_leaf_reg': 9}. Best is trial 15 with value: 0.9242390071261423.

Best trial: 15. Best value: 0.924239:  10%|█         | 5/50 [00:21<01:48,  2.42s/it]

[I 2026-01-28 10:17:25,482] Trial 12 finished with value: 0.8788474599997763 and parameters: {'iterations': 2400, 'learning_rate': 0.020284264054969813, 'l2_leaf_reg': 6}. Best is trial 15 with value: 0.9242390071261423.

Best trial: 7. Best value: 0.931455:  12%|█▏        | 6/50 [00:24<01:54,  2.61s/it]

[I 2026-01-28 10:17:28,465] Trial 7 finished with value: 0.9314546016889157 and parameters: {'iterations': 2800, 'learning_rate': 0.03963640282399753, 'l2_leaf_reg': 9}. Best is trial 7 with value: 0.9314546016889157.

Best trial: 7. Best value: 0.931455:  14%|█▍        | 7/50 [00:26<01:40,  2.34s/it]

[I 2026-01-28 10:17:30,265] Trial 14 finished with value: 0.9166723146890141 and parameters: {'iterations': 3000, 'learning_rate': 0.021682642015649584, 'l2_leaf_reg': 3}. Best is trial 7 with value: 0.9314546016889157.

Best trial: 7. Best value: 0.931455:  16%|█▌        | 8/50 [00:27<01:22,  1.96s/it]

[I 2026-01-28 10:17:31,403] Trial 10 finished with value: 0.899754617398544 and parameters: {'iterations': 3000, 'learning_rate': 0.020481390594726392, 'l2_leaf_reg': 6}. Best is trial 7 with value: 0.9314546016889157.

Best trial: 8. Best value: 0.937063:  18%|█▊        | 9/50 [00:29<01:16,  1.86s/it]

[I 2026-01-28 10:17:33,037] Trial 8 finished with value: 0.9370629412615084 and parameters: {'iterations': 3300, 'learning_rate': 0.03846397496967618, 'l2_leaf_reg': 9}. Best is trial 8 with value: 0.9370629412615084.

Best trial: 8. Best value: 0.937063:  20%|██        | 10/50 [00:31<01:13,  1.84s/it]

[I 2026-01-28 10:17:34,829] Trial 13 finished with value: 0.9230298142290376 and parameters: {'iterations': 3500, 'learning_rate': 0.02754000157808212, 'l2_leaf_reg': 9}. Best is trial 8 with value: 0.9370629412615084.

Best trial: 6. Best value: 0.951049:  22%|██▏       | 11/50 [00:32<01:09,  1.79s/it]

[I 2026-01-28 10:17:36,495] Trial 6 finished with value: 0.9510487215566358 and parameters: {'iterations': 3500, 'learning_rate': 0.034993876186148465, 'l2_leaf_reg': 2}. Best is trial 6 with value: 0.9510487215566358.

Best trial: 6. Best value: 0.951049:  24%|██▍       | 12/50 [00:34<01:03,  1.66s/it]

[I 2026-01-28 10:17:37,846] Trial 9 finished with value: 0.9215223938731144 and parameters: {'iterations': 3800, 'learning_rate': 0.0229520302342718, 'l2_leaf_reg': 7}. Best is trial 6 with value: 0.9510487215566358.

Best trial: 6. Best value: 0.951049:  26%|██▌       | 13/50 [00:35<01:01,  1.67s/it]

[I 2026-01-28 10:17:39,568] Trial 1 finished with value: 0.8907343825677562 and parameters: {'iterations': 2500, 'learning_rate': 0.022041872925472793, 'l2_leaf_reg': 6}. Best is trial 6 with value: 0.9510487215566358.

Best trial: 6. Best value: 0.951049:  28%|██▊       | 14/50 [00:42<01:58,  3.29s/it]

[I 2026-01-28 10:17:46,603] Trial 0 finished with value: 0.9269360975899118 and parameters: {'iterations': 3000, 'learning_rate': 0.021711161633497168, 'l2_leaf_reg': 1}. Best is trial 6 with value: 0.9510487215566358.

Best trial: 6. Best value: 0.951049:  30%|███       | 15/50 [00:44<01:38,  2.80s/it]

[I 2026-01-28 10:17:48,265] Trial 22 finished with value: 0.8883668641565864 and parameters: {'iterations': 1900, 'learning_rate': 0.029727277280778345, 'l2_leaf_reg': 7}. Best is trial 6 with value: 0.9510487215566358.

Best trial: 6. Best value: 0.951049:  32%|███▏      | 16/50 [00:45<01:20,  2.36s/it]

[I 2026-01-28 10:17:49,563] Trial 3 finished with value: 0.9392054235072678 and parameters: {'iterations': 3200, 'learning_rate': 0.02924424425389412, 'l2_leaf_reg': 3}. Best is trial 6 with value: 0.9510487215566358.

Best trial: 6. Best value: 0.951049:  34%|███▍      | 17/50 [00:46<01:03,  1.92s/it]

[I 2026-01-28 10:17:50,495] Trial 24 finished with value: 0.8892725374754559 and parameters: {'iterations': 1800, 'learning_rate': 0.03391598222173359, 'l2_leaf_reg': 9}. Best is trial 6 with value: 0.9510487215566358.

Best trial: 6. Best value: 0.951049:  36%|███▌      | 18/50 [00:47<00:49,  1.56s/it]

[I 2026-01-28 10:17:51,218] Trial 2 finished with value: 0.9244372083455811 and parameters: {'iterations': 3300, 'learning_rate': 0.028418827099673246, 'l2_leaf_reg': 8}. Best is trial 6 with value: 0.9510487215566358.

Best trial: 6. Best value: 0.951049:  38%|███▊      | 19/50 [00:54<01:36,  3.11s/it]

[I 2026-01-28 10:17:57,947] Trial 17 finished with value: 0.9130848390196044 and parameters: {'iterations': 3500, 'learning_rate': 0.022826683599781294, 'l2_leaf_reg': 8}. Best is trial 6 with value: 0.9510487215566358.

Best trial: 6. Best value: 0.951049:  40%|████      | 20/50 [00:54<01:08,  2.28s/it]

[I 2026-01-28 10:17:58,301] Trial 21 finished with value: 0.9351522910644329 and parameters: {'iterations': 3000, 'learning_rate': 0.03077499373145697, 'l2_leaf_reg': 4}. Best is trial 6 with value: 0.9510487215566358.

Best trial: 6. Best value: 0.951049:  42%|████▏     | 21/50 [00:55<00:58,  2.03s/it]

[I 2026-01-28 10:17:59,738] Trial 16 finished with value: 0.9396850120651363 and parameters: {'iterations': 3700, 'learning_rate': 0.03341184186146243, 'l2_leaf_reg': 8}. Best is trial 6 with value: 0.9510487215566358.

Best trial: 6. Best value: 0.951049:  44%|████▍     | 22/50 [00:57<00:56,  2.01s/it]

[I 2026-01-28 10:18:01,707] Trial 18 finished with value: 0.9208478388411973 and parameters: {'iterations': 3800, 'learning_rate': 0.02604156016247852, 'l2_leaf_reg': 10}. Best is trial 6 with value: 0.9510487215566358.

Best trial: 19. Best value: 0.956342:  46%|████▌     | 23/50 [00:58<00:42,  1.56s/it]

[I 2026-01-28 10:18:02,213] Trial 19 finished with value: 0.956342306944633 and parameters: {'iterations': 3500, 'learning_rate': 0.03673811404854623, 'l2_leaf_reg': 1}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  48%|████▊     | 24/50 [00:59<00:40,  1.55s/it]

[I 2026-01-28 10:18:03,746] Trial 20 finished with value: 0.9297680228616326 and parameters: {'iterations': 3600, 'learning_rate': 0.025995895401177988, 'l2_leaf_reg': 6}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  50%|█████     | 25/50 [01:10<01:42,  4.12s/it]

[I 2026-01-28 10:18:13,852] Trial 27 finished with value: 0.945016586078124 and parameters: {'iterations': 3400, 'learning_rate': 0.032397732635132855, 'l2_leaf_reg': 3}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  52%|█████▏    | 26/50 [01:10<01:14,  3.09s/it]

[I 2026-01-28 10:18:14,526] Trial 23 finished with value: 0.918029083719015 and parameters: {'iterations': 3900, 'learning_rate': 0.023592851056063496, 'l2_leaf_reg': 10}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  54%|█████▍    | 27/50 [01:11<00:51,  2.26s/it]

[I 2026-01-28 10:18:14,850] Trial 25 finished with value: 0.9462716759427376 and parameters: {'iterations': 3800, 'learning_rate': 0.03129644595027153, 'l2_leaf_reg': 4}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  56%|█████▌    | 28/50 [01:16<01:10,  3.19s/it]

[I 2026-01-28 10:18:20,229] Trial 26 finished with value: 0.9499121439017663 and parameters: {'iterations': 3900, 'learning_rate': 0.03257549416289762, 'l2_leaf_reg': 3}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  58%|█████▊    | 29/50 [01:22<01:23,  3.97s/it]

[I 2026-01-28 10:18:26,012] Trial 30 finished with value: 0.9494708888816028 and parameters: {'iterations': 3400, 'learning_rate': 0.037788775633834384, 'l2_leaf_reg': 3}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  60%|██████    | 30/50 [01:28<01:34,  4.74s/it]

[I 2026-01-28 10:18:32,542] Trial 32 finished with value: 0.9486419608244431 and parameters: {'iterations': 3800, 'learning_rate': 0.03102173405246421, 'l2_leaf_reg': 3}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  62%|██████▏   | 31/50 [01:29<01:08,  3.60s/it]

[I 2026-01-28 10:18:33,492] Trial 28 finished with value: 0.944404770140436 and parameters: {'iterations': 3400, 'learning_rate': 0.03260430596278952, 'l2_leaf_reg': 4}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  64%|██████▍   | 32/50 [01:37<01:26,  4.82s/it]

[I 2026-01-28 10:18:41,155] Trial 35 finished with value: 0.9504288012951326 and parameters: {'iterations': 3900, 'learning_rate': 0.031850149774761326, 'l2_leaf_reg': 3}. Best is trial 19 with value: 0.956342306944633.
[I 2026-01-28 10:18:41,220] Trial 29 finished with value: 0.9451220579006979 and parameters: {'iterations': 3400, 'learning_rate': 0.03239364330548761, 'l2_leaf_reg': 3}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  68%|██████▊   | 34/50 [01:37<00:42,  2.64s/it]

[I 2026-01-28 10:18:41,369] Trial 37 finished with value: 0.9467207668906069 and parameters: {'iterations': 3600, 'learning_rate': 0.03214316436988556, 'l2_leaf_reg': 3}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  70%|███████   | 35/50 [01:38<00:34,  2.31s/it]

[I 2026-01-28 10:18:42,671] Trial 34 finished with value: 0.9506648066406456 and parameters: {'iterations': 3900, 'learning_rate': 0.03164652710532442, 'l2_leaf_reg': 3}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  72%|███████▏  | 36/50 [01:39<00:27,  1.94s/it]

[I 2026-01-28 10:18:43,548] Trial 38 finished with value: 0.9502702085590281 and parameters: {'iterations': 3600, 'learning_rate': 0.0321664322393625, 'l2_leaf_reg': 2}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  74%|███████▍  | 37/50 [01:40<00:20,  1.58s/it]

[I 2026-01-28 10:18:44,170] Trial 36 finished with value: 0.9494363024270299 and parameters: {'iterations': 3900, 'learning_rate': 0.03171857016712279, 'l2_leaf_reg': 3}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  76%|███████▌  | 38/50 [01:43<00:24,  2.04s/it]

[I 2026-01-28 10:18:47,407] Trial 39 finished with value: 0.9525085920531179 and parameters: {'iterations': 3900, 'learning_rate': 0.03195999215752195, 'l2_leaf_reg': 2}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  78%|███████▊  | 39/50 [01:45<00:23,  2.10s/it]

[I 2026-01-28 10:18:49,643] Trial 40 finished with value: 0.9479035407591754 and parameters: {'iterations': 3400, 'learning_rate': 0.0317436142575863, 'l2_leaf_reg': 2}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  80%|████████  | 40/50 [01:46<00:16,  1.69s/it]

[I 2026-01-28 10:18:50,328] Trial 31 finished with value: 0.9481556468275071 and parameters: {'iterations': 3800, 'learning_rate': 0.03194591470271566, 'l2_leaf_reg': 3}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  82%|████████▏ | 41/50 [01:47<00:12,  1.39s/it]

[I 2026-01-28 10:18:51,004] Trial 41 finished with value: 0.9516911050834702 and parameters: {'iterations': 3400, 'learning_rate': 0.036466416560620586, 'l2_leaf_reg': 2}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  84%|████████▍ | 42/50 [01:47<00:08,  1.11s/it]

[I 2026-01-28 10:18:51,448] Trial 33 finished with value: 0.9481181952322224 and parameters: {'iterations': 3800, 'learning_rate': 0.03145841156080967, 'l2_leaf_reg': 3}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  86%|████████▌ | 43/50 [01:50<00:10,  1.55s/it]

[I 2026-01-28 10:18:54,031] Trial 42 finished with value: 0.9556333140961007 and parameters: {'iterations': 3900, 'learning_rate': 0.03685177672194535, 'l2_leaf_reg': 2}. Best is trial 19 with value: 0.956342306944633.

Best trial: 19. Best value: 0.956342:  88%|████████▊ | 44/50 [01:53<00:12,  2.12s/it]

[I 2026-01-28 10:18:57,499] Trial 43 finished with value: 0.9546687690760957 and parameters: {'iterations': 3900, 'learning_rate': 0.036889561280999135, 'l2_leaf_reg': 2}. Best is trial 19 with value: 0.956342306944633.

Best trial: 44. Best value: 0.957542:  90%|█████████ | 45/50 [01:55<00:10,  2.11s/it]

[I 2026-01-28 10:18:59,577] Trial 44 finished with value: 0.9575418245594619 and parameters: {'iterations': 3900, 'learning_rate': 0.03617035352979516, 'l2_leaf_reg': 1}. Best is trial 44 with value: 0.9575418245594619.

Best trial: 44. Best value: 0.957542:  92%|█████████▏| 46/50 [01:57<00:08,  2.11s/it]

[I 2026-01-28 10:19:01,704] Trial 45 finished with value: 0.9555558155226592 and parameters: {'iterations': 3600, 'learning_rate': 0.03633197291705052, 'l2_leaf_reg': 1}. Best is trial 44 with value: 0.9575418245594619.

Best trial: 44. Best value: 0.957542:  94%|█████████▍| 47/50 [02:00<00:06,  2.33s/it]

[I 2026-01-28 10:19:04,542] Trial 49 finished with value: 0.9565023480706949 and parameters: {'iterations': 3600, 'learning_rate': 0.03694204157088448, 'l2_leaf_reg': 1}. Best is trial 44 with value: 0.9575418245594619.

Best trial: 44. Best value: 0.957542:  96%|█████████▌| 48/50 [02:01<00:03,  1.77s/it]

[I 2026-01-28 10:19:04,996] Trial 47 finished with value: 0.9558822117584125 and parameters: {'iterations': 3600, 'learning_rate': 0.03596516338014669, 'l2_leaf_reg': 1}. Best is trial 44 with value: 0.9575418245594619.

Best trial: 44. Best value: 0.957542:  98%|█████████▊| 49/50 [02:02<00:01,  1.62s/it]

[I 2026-01-28 10:19:06,262] Trial 46 finished with value: 0.9557895844982056 and parameters: {'iterations': 3600, 'learning_rate': 0.037106053393193686, 'l2_leaf_reg': 1}. Best is trial 44 with value: 0.9575418245594619.

Best trial: 44. Best value: 0.957542: 100%|██████████| 50/50 [02:04<00:00,  2.49s/it]

[I 2026-01-28 10:19:08,225] Trial 48 finished with value: 0.9573016059746191 and parameters: {'iterations': 3900, 'learning_rate': 0.0359716245998971, 'l2_leaf_reg': 1}. Best is trial 44 with value: 0.9575418245594619.

In [23]:
print("Best mean CV R²:", study.best_value)
print("Best hyperparameters:", study.best_params)

Best mean CV R²: 0.9575418245594619
Best hyperparameters: {'iterations': 3900, 'learning_rate': 0.03617035352979516, 'l2_leaf_reg': 1}

In [17]:
best_params = {'iterations': 3900, 'learning_rate': 0.03617035352979516, 'l2_leaf_reg': 1}
print(best_params)

{'iterations': 3900, 'learning_rate': 0.03617035352979516, 'l2_leaf_reg': 1}

In [ ]:
# 4️⃣ Train final model on all augmented train data with best params
# --------------------------
best_params = best_params

FinalCatBoostModel = CatBoostRegressor(
    **best_params,
    depth=4, 
    
    task_type= 'CPU',   # use 'CPU' for stable CV, switch to 'GPU' if desired
    verbose= 100,
    random_seed= 42,
)

FinalCatBoostModel.fit(X_train_scaled, y_train)

y_pred_log = FinalCatBoostModel.predict(X_test_scaled)

import numpy as np
from sklearn.metrics import r2_score

y_pred_real = np.expm1(y_pred_log)
y_test_real = np.expm1(y_test)

print("Final R² (log scale) | After hyperparameter tuning | CatBoost Regressor :", r2_score(y_test, y_pred_log))
print("Final R² (real scale) | After hyperparameter tuning | CatBoost Regressor:", r2_score(y_test_real, y_pred_real))


# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred_log)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

0:	learn: 0.3678437	total: 1.91ms	remaining: 7.45s
100:	learn: 0.2391295	total: 106ms	remaining: 4s
200:	learn: 0.2023803	total: 174ms	remaining: 3.21s
300:	learn: 0.1753730	total: 245ms	remaining: 2.93s
400:	learn: 0.1550542	total: 314ms	remaining: 2.74s
500:	learn: 0.1391600	total: 380ms	remaining: 2.58s
600:	learn: 0.1262574	total: 447ms	remaining: 2.45s
700:	learn: 0.1155408	total: 522ms	remaining: 2.38s
800:	learn: 0.1059393	total: 587ms	remaining: 2.27s
900:	learn: 0.0978805	total: 664ms	remaining: 2.21s
1000:	learn: 0.0909342	total: 731ms	remaining: 2.12s
1100:	learn: 0.0837958	total: 796ms	remaining: 2.02s
1200:	learn: 0.0773340	total: 863ms	remaining: 1.94s
1300:	learn: 0.0716810	total: 931ms	remaining: 1.86s
1400:	learn: 0.0668407	total: 996ms	remaining: 1.77s
1500:	learn: 0.0625581	total: 1.06s	remaining: 1.7s
1600:	learn: 0.0586002	total: 1.13s	remaining: 1.62s
1700:	learn: 0.0549791	total: 1.19s	remaining: 1.54s
1800:	learn: 0.0517030	total: 1.26s	remaining: 1.47s
1900:	learn: 0.0485774	total: 1.33s	remaining: 1.4s
2000:	learn: 0.0457610	total: 1.39s	remaining: 1.32s
2100:	learn: 0.0433097	total: 1.46s	remaining: 1.25s
2200:	learn: 0.0410093	total: 1.52s	remaining: 1.18s
2300:	learn: 0.0388014	total: 1.59s	remaining: 1.1s
2400:	learn: 0.0369378	total: 1.66s	remaining: 1.03s
2500:	learn: 0.0350763	total: 1.73s	remaining: 965ms
2600:	learn: 0.0334670	total: 1.79s	remaining: 896ms
2700:	learn: 0.0317519	total: 1.86s	remaining: 827ms
2800:	learn: 0.0303415	total: 1.94s	remaining: 762ms
2900:	learn: 0.0289746	total: 2.02s	remaining: 696ms
3000:	learn: 0.0277378	total: 2.09s	remaining: 626ms
3100:	learn: 0.0266805	total: 2.16s	remaining: 556ms
3200:	learn: 0.0255940	total: 2.23s	remaining: 486ms
3300:	learn: 0.0245732	total: 2.29s	remaining: 416ms
3400:	learn: 0.0237030	total: 2.36s	remaining: 347ms
3500:	learn: 0.0228707	total: 2.43s	remaining: 277ms
3600:	learn: 0.0220917	total: 2.5s	remaining: 207ms
3700:	learn: 0.0213875	total: 2.56s	remaining: 138ms
3800:	learn: 0.0207140	total: 2.63s	remaining: 68.5ms
3899:	learn: 0.0200863	total: 2.7s	remaining: 0us
Final R² (log scale) | After hyperparameter tuning | CatBoost Regressor : 0.6914258358805703
Final R² (real scale) | After hyperparameter tuning | CatBoost Regressor: 0.6177209333520652
R² for DOC on normal: 0.6177209333520652
Final metrics on NORMAL scale (after inverse log):
R²   : 0.6177
MSE  : 1.1921
RMSE : 1.0918
MAE  : 0.6698

In [ ]:
#for no Meteo

In [6]:
#FOR AUGMENTED_NEW

import pandas as pd
import numpy as np

aug_factor = 3 #augmented has been done initially for aug_factor = 2, then for aug_factor = 3

doc_train_augmented = pd.read_csv (f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TRAIN_AUG{aug_factor}.csv")
doc_test = pd.read_csv(f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TEST_AUG{aug_factor}.csv")

doc_train_augmented.shape, doc_test.shape

((2732, 55), (171, 55))

In [7]:
doc_train_augmented ['result_DOC_log'] = np.log1p (doc_train_augmented ['result_DOC'])
doc_test ['result_DOC_log'] = np.log1p (doc_test ['result_DOC'])
doc_train_augmented

,Unnamed: 0,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,...,B3_div_B2,ND_B4_B3,ND_B2_B3,ND_B6_B8,day_of_year,doy_sin,doy_cos,hour_sin,hour_cos,result_DOC_log
0,0,2024-05-08 14:00:00,0.037800,0.168600,0.105100,0.040100,0.063600,0.050700,0.094400,0.220200,...,1.585995,-0.112860,-0.226613,-0.130503,129,0.796183,-0.605056,-0.500000,-0.866025,0.741937
1,1,2019-08-20 15:00:00,0.068100,0.144400,0.130300,0.057300,0.075900,0.073100,0.098200,0.105800,...,1.324584,-0.018792,-0.139639,0.109596,232,-0.752667,-0.658402,-0.707107,-0.707107,1.308333
2,2,2022-02-01 20:55:00,0.015100,0.165100,0.131400,0.033200,0.053800,0.056300,0.095100,0.146200,...,1.620433,0.022706,-0.236779,-0.071156,32,0.523416,0.852078,-0.866025,0.500000,0.741937
3,3,2018-11-06 21:25:00,0.007100,0.026500,0.019000,0.019100,0.030400,0.022600,0.023400,0.014200,...,1.591540,-0.147167,-0.228278,-0.080904,310,-0.811539,0.584298,-0.707107,0.707107,1.481605
4,4,2018-11-06 19:20:00,0.001400,0.010400,0.010300,0.013300,0.020300,0.008900,0.006200,0.000000,...,1.526201,-0.390398,-0.208327,0.000000,310,-0.811539,0.584298,-0.965926,0.258819,1.193922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,2727,2019-08-20 16:00:00,0.160048,0.347841,0.301870,0.194634,0.206942,0.225023,0.253643,0.254485,...,1.063231,0.041857,-0.030649,-0.043629,232,-0.752667,-0.658402,-0.866025,-0.500000,1.536867
2728,2728,2021-08-17 15:45:00,0.106466,0.173790,0.156926,0.132880,0.156900,0.169819,0.182550,0.194755,...,1.180757,0.039542,-0.082891,0.040882,229,-0.717677,-0.696376,-0.707107,-0.707107,1.547563
2729,2729,2023-05-24 17:43:00,0.041518,0.115512,0.094602,0.046671,0.063934,0.065133,0.090442,0.112315,...,1.369847,0.009291,-0.156073,-0.035528,144,0.615285,-0.788305,-0.965926,-0.258819,1.410987
2730,2730,2018-06-19 19:24:00,0.051536,0.046751,0.038356,0.069572,0.074987,0.053739,0.051703,0.041847,...,1.077817,-0.165069,-0.037458,-0.020389,170,0.213521,-0.976938,-0.965926,0.258819,1.029619
2731,2731,2019-09-17 15:50:00,0.048440,0.116872,0.101207,0.040520,0.053809,0.062569,0.082519,0.073375,...,1.327936,0.075266,-0.140880,0.122702,260,-0.972118,-0.234491,-0.707107,-0.707107,1.280934

In [8]:
TARGET = "result_DOC_log" #FOR DOC
TARGET1 = "result_DOC"

input_features_noMeteo = ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 
                'B9',
               "B4_minus_B3",
               "B4_div_B3", 
               "ND_B4_B3", 
               #'Temperature', 'DewPoint', 'v10n', #'Precipitation(mm)',
               'doy_sin', 'doy_cos',  
               'latitude', 'longitude'
               ]

X_train = doc_train_augmented[input_features_noMeteo]
y_train = doc_train_augmented[TARGET]

X_test = doc_test[input_features_noMeteo]
y_test = doc_test[TARGET]

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2732, 16), (2732,), (171, 16), (171,))

In [9]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
import catboost 
from catboost import CatBoostRegressor

print(catboost.__version__)

1.2.7

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
baseline_CBR = CatBoostRegressor(
    iterations=3600,         # baseline, can increase later
    learning_rate=0.03,      # baseline
    depth=4,                 # baseline
    l2_leaf_reg=3,            # L2 regularization, prevents overfitting
    
    task_type="CPU",         # CPU training
    devices='0',             # first GPU
    random_seed=42,
    verbose=100              # log progress every 100 iterations
)

baseline_CBR.fit(X_train_scaled, y_train)

y_pred = baseline_CBR.predict(X_test_scaled)

print("R² for DOC for log scaled | CatBoost Regressor:", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | CatBoost Regressor:", r2_score(y_test_real, y_pred_orig))



# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

0:	learn: 0.3691605	total: 3.63ms	remaining: 13.1s
100:	learn: 0.2502993	total: 95.3ms	remaining: 3.3s
200:	learn: 0.2198953	total: 161ms	remaining: 2.71s
300:	learn: 0.1994864	total: 227ms	remaining: 2.48s
400:	learn: 0.1843317	total: 290ms	remaining: 2.31s
500:	learn: 0.1699692	total: 351ms	remaining: 2.17s
600:	learn: 0.1581993	total: 413ms	remaining: 2.06s
700:	learn: 0.1477763	total: 477ms	remaining: 1.97s
800:	learn: 0.1386793	total: 539ms	remaining: 1.88s
900:	learn: 0.1312787	total: 600ms	remaining: 1.8s
1000:	learn: 0.1237911	total: 663ms	remaining: 1.72s
1100:	learn: 0.1174252	total: 727ms	remaining: 1.65s
1200:	learn: 0.1108414	total: 791ms	remaining: 1.58s
1300:	learn: 0.1048852	total: 854ms	remaining: 1.51s
1400:	learn: 0.0994749	total: 917ms	remaining: 1.44s
1500:	learn: 0.0944967	total: 981ms	remaining: 1.37s
1600:	learn: 0.0901682	total: 1.04s	remaining: 1.3s
1700:	learn: 0.0861060	total: 1.11s	remaining: 1.24s
1800:	learn: 0.0823240	total: 1.17s	remaining: 1.17s
1900:	learn: 0.0788200	total: 1.24s	remaining: 1.11s
2000:	learn: 0.0755943	total: 1.32s	remaining: 1.05s
2100:	learn: 0.0724711	total: 1.38s	remaining: 986ms
2200:	learn: 0.0694032	total: 1.45s	remaining: 919ms
2300:	learn: 0.0666456	total: 1.51s	remaining: 853ms
2400:	learn: 0.0640839	total: 1.57s	remaining: 786ms
2500:	learn: 0.0615560	total: 1.64s	remaining: 719ms
2600:	learn: 0.0594647	total: 1.7s	remaining: 654ms
2700:	learn: 0.0576374	total: 1.76s	remaining: 588ms
2800:	learn: 0.0557503	total: 1.83s	remaining: 522ms
2900:	learn: 0.0538776	total: 1.89s	remaining: 456ms
3000:	learn: 0.0519190	total: 1.96s	remaining: 391ms
3100:	learn: 0.0502298	total: 2.02s	remaining: 325ms
3200:	learn: 0.0486512	total: 2.08s	remaining: 260ms
3300:	learn: 0.0470570	total: 2.15s	remaining: 194ms
3400:	learn: 0.0456412	total: 2.21s	remaining: 129ms
3500:	learn: 0.0442833	total: 2.28s	remaining: 64.4ms
3599:	learn: 0.0430043	total: 2.34s	remaining: 0us
R² for DOC for log scaled | CatBoost Regressor: 0.6245236705403374
R² for DOC on normal scaled | CatBoost Regressor: 0.4894973919073493
R² for DOC on normal: 0.4894973919073493
Final metrics on NORMAL scale (after inverse log):
R²   : 0.4895
MSE  : 1.5920
RMSE : 1.2617
MAE  : 0.7351

In [ ]:
#HyperParam tuning with Optuna - for no Meteo

In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
import optuna 
scaler = StandardScaler()
X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

d:\Miniconda3\envs\PyTorchVirtualEnv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [12]:
kf = KFold(n_splits=3, shuffle=True, random_state=42)

def objective_Kfold_withScaled_NM(trial):
    # Hyperparameters to tune
    params = {
        'iterations': trial.suggest_int('iterations', 1800, 3900, step=100),
        'learning_rate': trial.suggest_float('learning_rate', 0.02, 0.04, log=True),
        
        'depth': 4,
        
        'l2_leaf_reg': trial.suggest_int('l2_leaf_reg', 1, 10),
        
        
        'task_type': 'CPU',   
        'verbose': 0,
        'random_seed': 42
    }
    
    # Manual CV loop
    r2_scores = []
    for train_idx, valid_idx in kf.split(X_train_scaled):
        X_tr, X_val = X_train_scaled[train_idx], X_train_scaled[valid_idx]
        y_tr, y_val = y_train[train_idx], y_train[valid_idx]

        model = CatBoostRegressor(**params)
        model.fit(
            X_tr, y_tr,
            eval_set=(X_val, y_val),
            early_stopping_rounds=100,
            verbose=0
        )

        y_pred = model.predict(X_val)
        r2_scores.append(r2_score(y_val, y_pred))

    return np.mean(r2_scores)

In [13]:
study = optuna.create_study(direction="maximize", study_name = "Catboost_study_CPU", sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective_Kfold_withScaled_NM, n_trials=50, show_progress_bar=True, n_jobs=-1)

[I 2026-05-31 18:44:07,722] A new study created in memory with name: Catboost_study_CPU
Best trial: 7. Best value: 0.858627:   2%|▏         | 1/50 [00:13<10:40, 13.08s/it]

[I 2026-05-31 18:44:20,798] Trial 7 finished with value: 0.8586270694131782 and parameters: {'iterations': 1800, 'learning_rate': 0.029411236759469463, 'l2_leaf_reg': 8}. Best is trial 7 with value: 0.8586270694131782.

Best trial: 7. Best value: 0.858627:   4%|▍         | 2/50 [00:15<05:18,  6.63s/it]

[I 2026-05-31 18:44:22,906] Trial 14 finished with value: 0.8443185808299053 and parameters: {'iterations': 2000, 'learning_rate': 0.024398439424132026, 'l2_leaf_reg': 10}. Best is trial 7 with value: 0.8586270694131782.

Best trial: 11. Best value: 0.911496:   6%|▌         | 3/50 [00:19<04:11,  5.35s/it]

[I 2026-05-31 18:44:26,748] Trial 11 finished with value: 0.9114959152565336 and parameters: {'iterations': 1800, 'learning_rate': 0.03964146778308108, 'l2_leaf_reg': 2}. Best is trial 11 with value: 0.9114959152565336.

Best trial: 11. Best value: 0.911496:   8%|▊         | 4/50 [00:21<03:19,  4.34s/it]

[I 2026-05-31 18:44:29,523] Trial 9 finished with value: 0.8685404906943007 and parameters: {'iterations': 2100, 'learning_rate': 0.029119884036258585, 'l2_leaf_reg': 9}. Best is trial 11 with value: 0.9114959152565336.

Best trial: 11. Best value: 0.911496:  10%|█         | 5/50 [00:23<02:33,  3.40s/it]

[I 2026-05-31 18:44:31,265] Trial 4 finished with value: 0.8977824297369358 and parameters: {'iterations': 2200, 'learning_rate': 0.03327899201945715, 'l2_leaf_reg': 5}. Best is trial 11 with value: 0.9114959152565336.

Best trial: 11. Best value: 0.911496:  12%|█▏        | 6/50 [00:24<01:45,  2.40s/it]

[I 2026-05-31 18:44:31,737] Trial 6 finished with value: 0.8844449696932281 and parameters: {'iterations': 3100, 'learning_rate': 0.021550691551248342, 'l2_leaf_reg': 7}. Best is trial 11 with value: 0.9114959152565336.

Best trial: 11. Best value: 0.911496:  14%|█▍        | 7/50 [00:24<01:19,  1.85s/it]

[I 2026-05-31 18:44:32,441] Trial 2 finished with value: 0.8949952322899953 and parameters: {'iterations': 2300, 'learning_rate': 0.027762798176425133, 'l2_leaf_reg': 4}. Best is trial 11 with value: 0.9114959152565336.

Best trial: 0. Best value: 0.914511:  16%|█▌        | 8/50 [00:26<01:21,  1.94s/it]

[I 2026-05-31 18:44:34,563] Trial 0 finished with value: 0.9145114512989116 and parameters: {'iterations': 3200, 'learning_rate': 0.029485524874566762, 'l2_leaf_reg': 6}. Best is trial 0 with value: 0.9145114512989116.

Best trial: 15. Best value: 0.923439:  18%|█▊        | 9/50 [00:27<01:00,  1.47s/it]

[I 2026-05-31 18:44:35,000] Trial 15 finished with value: 0.9234393859361266 and parameters: {'iterations': 3500, 'learning_rate': 0.03738283979169174, 'l2_leaf_reg': 9}. Best is trial 15 with value: 0.9234393859361266.

Best trial: 13. Best value: 0.931912:  20%|██        | 10/50 [00:28<00:55,  1.38s/it]

[I 2026-05-31 18:44:36,201] Trial 12 finished with value: 0.8670787917262714 and parameters: {'iterations': 2700, 'learning_rate': 0.020331461619553494, 'l2_leaf_reg': 7}. Best is trial 15 with value: 0.9234393859361266.
[I 2026-05-31 18:44:36,261] Trial 13 finished with value: 0.9319121498307812 and parameters: {'iterations': 3700, 'learning_rate': 0.02955772240529082, 'l2_leaf_reg': 3}. Best is trial 13 with value: 0.9319121498307812.

Best trial: 5. Best value: 0.937847:  24%|██▍       | 12/50 [00:30<00:43,  1.15s/it]

[I 2026-05-31 18:44:37,966] Trial 5 finished with value: 0.9378467184781396 and parameters: {'iterations': 3900, 'learning_rate': 0.03390515485693444, 'l2_leaf_reg': 3}. Best is trial 5 with value: 0.9378467184781396.

Best trial: 5. Best value: 0.937847:  26%|██▌       | 13/50 [00:31<00:39,  1.08s/it]

[I 2026-05-31 18:44:38,823] Trial 10 finished with value: 0.8949983572062195 and parameters: {'iterations': 2600, 'learning_rate': 0.033491340501763854, 'l2_leaf_reg': 10}. Best is trial 5 with value: 0.9378467184781396.

Best trial: 5. Best value: 0.937847:  28%|██▊       | 14/50 [00:32<00:45,  1.27s/it]

[I 2026-05-31 18:44:40,643] Trial 16 finished with value: 0.862863359812192 and parameters: {'iterations': 2600, 'learning_rate': 0.02018967434240707, 'l2_leaf_reg': 7}. Best is trial 5 with value: 0.9378467184781396.

Best trial: 5. Best value: 0.937847:  30%|███       | 15/50 [00:33<00:34,  1.01it/s]

[I 2026-05-31 18:44:40,900] Trial 1 finished with value: 0.9241587676630131 and parameters: {'iterations': 3800, 'learning_rate': 0.025995685741079105, 'l2_leaf_reg': 4}. Best is trial 5 with value: 0.9378467184781396.
[I 2026-05-31 18:44:40,953] Trial 17 finished with value: 0.8586164035972566 and parameters: {'iterations': 2300, 'learning_rate': 0.024492770629825085, 'l2_leaf_reg': 10}. Best is trial 5 with value: 0.9378467184781396.

Best trial: 5. Best value: 0.937847:  34%|███▍      | 17/50 [00:34<00:25,  1.32it/s]

[I 2026-05-31 18:44:41,816] Trial 3 finished with value: 0.9262738571087527 and parameters: {'iterations': 3200, 'learning_rate': 0.02837025983160289, 'l2_leaf_reg': 2}. Best is trial 5 with value: 0.9378467184781396.

Best trial: 8. Best value: 0.939856:  36%|███▌      | 18/50 [00:40<01:04,  2.01s/it]

[I 2026-05-31 18:44:47,798] Trial 8 finished with value: 0.9398558832102637 and parameters: {'iterations': 3600, 'learning_rate': 0.030364687460801152, 'l2_leaf_reg': 1}. Best is trial 8 with value: 0.9398558832102637.

Best trial: 8. Best value: 0.939856:  38%|███▊      | 19/50 [00:42<01:01,  2.00s/it]

[I 2026-05-31 18:44:49,773] Trial 19 finished with value: 0.8995517234577176 and parameters: {'iterations': 1900, 'learning_rate': 0.028606971582619004, 'l2_leaf_reg': 1}. Best is trial 8 with value: 0.9398558832102637.

Best trial: 8. Best value: 0.939856:  40%|████      | 20/50 [00:44<01:00,  2.01s/it]

[I 2026-05-31 18:44:51,815] Trial 18 finished with value: 0.8949613190331828 and parameters: {'iterations': 2400, 'learning_rate': 0.029960728205838127, 'l2_leaf_reg': 6}. Best is trial 8 with value: 0.9398558832102637.

Best trial: 8. Best value: 0.939856:  42%|████▏     | 21/50 [00:46<00:59,  2.06s/it]

[I 2026-05-31 18:44:53,990] Trial 21 finished with value: 0.8636376281347514 and parameters: {'iterations': 2800, 'learning_rate': 0.02040142522653452, 'l2_leaf_reg': 9}. Best is trial 8 with value: 0.9398558832102637.

Best trial: 8. Best value: 0.939856:  44%|████▍     | 22/50 [00:47<00:49,  1.77s/it]

[I 2026-05-31 18:44:55,033] Trial 24 finished with value: 0.910717199339565 and parameters: {'iterations': 2500, 'learning_rate': 0.024802172420774184, 'l2_leaf_reg': 1}. Best is trial 8 with value: 0.9398558832102637.

Best trial: 8. Best value: 0.939856:  46%|████▌     | 23/50 [00:58<02:03,  4.57s/it]

[I 2026-05-31 18:45:06,550] Trial 23 finished with value: 0.9353257921123476 and parameters: {'iterations': 3500, 'learning_rate': 0.036387558764107326, 'l2_leaf_reg': 4}. Best is trial 8 with value: 0.9398558832102637.

Best trial: 26. Best value: 0.949012:  48%|████▊     | 24/50 [00:59<01:30,  3.49s/it]

[I 2026-05-31 18:45:07,389] Trial 26 finished with value: 0.9490123409427623 and parameters: {'iterations': 3900, 'learning_rate': 0.03845776446563157, 'l2_leaf_reg': 1}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  50%|█████     | 25/50 [01:01<01:15,  3.03s/it]

[I 2026-05-31 18:45:09,309] Trial 27 finished with value: 0.9455941513615339 and parameters: {'iterations': 3900, 'learning_rate': 0.03385396620806845, 'l2_leaf_reg': 1}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  52%|█████▏    | 26/50 [01:03<01:03,  2.64s/it]

[I 2026-05-31 18:45:11,045] Trial 29 finished with value: 0.945910984536556 and parameters: {'iterations': 3800, 'learning_rate': 0.03371715098244401, 'l2_leaf_reg': 1}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  54%|█████▍    | 27/50 [01:04<00:53,  2.33s/it]

[I 2026-05-31 18:45:12,620] Trial 31 finished with value: 0.945450451160688 and parameters: {'iterations': 3900, 'learning_rate': 0.0328826069127469, 'l2_leaf_reg': 1}. Best is trial 26 with value: 0.9490123409427623.
[I 2026-05-31 18:45:12,707] Trial 20 finished with value: 0.9255629322991835 and parameters: {'iterations': 3600, 'learning_rate': 0.02885551606633762, 'l2_leaf_reg': 4}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  58%|█████▊    | 29/50 [01:08<00:43,  2.06s/it]

[I 2026-05-31 18:45:16,106] Trial 22 finished with value: 0.9127663004625335 and parameters: {'iterations': 3800, 'learning_rate': 0.024600950643751375, 'l2_leaf_reg': 6}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  60%|██████    | 30/50 [01:10<00:39,  1.97s/it]

[I 2026-05-31 18:45:17,785] Trial 30 finished with value: 0.9442790301343326 and parameters: {'iterations': 3900, 'learning_rate': 0.03304195077344048, 'l2_leaf_reg': 1}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  62%|██████▏   | 31/50 [01:12<00:40,  2.11s/it]

[I 2026-05-31 18:45:20,290] Trial 25 finished with value: 0.9482532585428546 and parameters: {'iterations': 3900, 'learning_rate': 0.03675005074847215, 'l2_leaf_reg': 1}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  64%|██████▍   | 32/50 [01:15<00:40,  2.24s/it]

[I 2026-05-31 18:45:22,875] Trial 28 finished with value: 0.9443324501489431 and parameters: {'iterations': 3800, 'learning_rate': 0.033506614705838204, 'l2_leaf_reg': 1}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  66%|██████▌   | 33/50 [01:19<00:46,  2.76s/it]

[I 2026-05-31 18:45:26,969] Trial 33 finished with value: 0.9426856015827932 and parameters: {'iterations': 3500, 'learning_rate': 0.03358001680754748, 'l2_leaf_reg': 1}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  68%|██████▊   | 34/50 [01:20<00:37,  2.37s/it]

[I 2026-05-31 18:45:28,362] Trial 36 finished with value: 0.9361269534393725 and parameters: {'iterations': 3900, 'learning_rate': 0.03230294948202178, 'l2_leaf_reg': 3}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  70%|███████   | 35/50 [01:21<00:28,  1.89s/it]

[I 2026-05-31 18:45:29,079] Trial 34 finished with value: 0.941431911206373 and parameters: {'iterations': 3500, 'learning_rate': 0.033460505427460104, 'l2_leaf_reg': 1}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  72%|███████▏  | 36/50 [01:21<00:20,  1.44s/it]

[I 2026-05-31 18:45:29,445] Trial 37 finished with value: 0.9369777337416014 and parameters: {'iterations': 3900, 'learning_rate': 0.032023924554671096, 'l2_leaf_reg': 3}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  74%|███████▍  | 37/50 [01:21<00:14,  1.08s/it]

[I 2026-05-31 18:45:29,668] Trial 32 finished with value: 0.9447994914305822 and parameters: {'iterations': 3900, 'learning_rate': 0.033155430006287144, 'l2_leaf_reg': 1}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  76%|███████▌  | 38/50 [01:38<01:07,  5.60s/it]

[I 2026-05-31 18:45:45,986] Trial 35 finished with value: 0.9455346070004382 and parameters: {'iterations': 3900, 'learning_rate': 0.03313469365256521, 'l2_leaf_reg': 1}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  78%|███████▊  | 39/50 [01:41<00:54,  4.96s/it]

[I 2026-05-31 18:45:49,448] Trial 39 finished with value: 0.9416510828361185 and parameters: {'iterations': 3900, 'learning_rate': 0.03351389109838827, 'l2_leaf_reg': 2}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  80%|████████  | 40/50 [01:42<00:35,  3.58s/it]

[I 2026-05-31 18:45:49,772] Trial 40 finished with value: 0.9410474975676402 and parameters: {'iterations': 3600, 'learning_rate': 0.0315731465468454, 'l2_leaf_reg': 1}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  84%|████████▍ | 42/50 [01:43<00:15,  1.97s/it]

[I 2026-05-31 18:45:50,543] Trial 42 finished with value: 0.9391489223131244 and parameters: {'iterations': 3400, 'learning_rate': 0.03563957736488874, 'l2_leaf_reg': 2}. Best is trial 26 with value: 0.9490123409427623.
[I 2026-05-31 18:45:50,721] Trial 38 finished with value: 0.9352981154598221 and parameters: {'iterations': 3500, 'learning_rate': 0.033544078165902436, 'l2_leaf_reg': 3}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  86%|████████▌ | 43/50 [01:44<00:13,  1.95s/it]

[I 2026-05-31 18:45:52,605] Trial 41 finished with value: 0.9432109703017558 and parameters: {'iterations': 3900, 'learning_rate': 0.03618358019534686, 'l2_leaf_reg': 2}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  88%|████████▊ | 44/50 [01:46<00:10,  1.80s/it]

[I 2026-05-31 18:45:54,045] Trial 43 finished with value: 0.9373504165479777 and parameters: {'iterations': 3400, 'learning_rate': 0.035847385962586485, 'l2_leaf_reg': 2}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  90%|█████████ | 45/50 [01:47<00:07,  1.48s/it]

[I 2026-05-31 18:45:54,778] Trial 44 finished with value: 0.9371754433919764 and parameters: {'iterations': 3300, 'learning_rate': 0.03556149982805907, 'l2_leaf_reg': 2}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  92%|█████████▏| 46/50 [01:48<00:06,  1.59s/it]

[I 2026-05-31 18:45:56,643] Trial 45 finished with value: 0.9380289779057055 and parameters: {'iterations': 3300, 'learning_rate': 0.03573346357330754, 'l2_leaf_reg': 2}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  94%|█████████▍| 47/50 [01:49<00:03,  1.29s/it]

[I 2026-05-31 18:45:57,236] Trial 46 finished with value: 0.9386839029967913 and parameters: {'iterations': 3400, 'learning_rate': 0.03561139113319779, 'l2_leaf_reg': 2}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  96%|█████████▌| 48/50 [01:50<00:02,  1.12s/it]

[I 2026-05-31 18:45:57,937] Trial 47 finished with value: 0.9403087864694086 and parameters: {'iterations': 3400, 'learning_rate': 0.036278298236798276, 'l2_leaf_reg': 2}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012:  98%|█████████▊| 49/50 [01:50<00:00,  1.06it/s]

[I 2026-05-31 18:45:58,493] Trial 49 finished with value: 0.9397913339989001 and parameters: {'iterations': 3300, 'learning_rate': 0.03634075922600949, 'l2_leaf_reg': 2}. Best is trial 26 with value: 0.9490123409427623.

Best trial: 26. Best value: 0.949012: 100%|██████████| 50/50 [01:51<00:00,  2.22s/it]

[I 2026-05-31 18:45:58,794] Trial 48 finished with value: 0.9380268002258072 and parameters: {'iterations': 3300, 'learning_rate': 0.036373597901737886, 'l2_leaf_reg': 2}. Best is trial 26 with value: 0.9490123409427623.

In [18]:
print("Best mean CV R²:", study.best_value)
print("Best hyperparameters:", study.best_params)
best_params_NM = study.best_params

Best mean CV R²: 0.9490123409427623
Best hyperparameters: {'iterations': 3900, 'learning_rate': 0.03845776446563157, 'l2_leaf_reg': 1}

In [19]:
best_params = best_params_NM

FinalCatBoostModel_NM = CatBoostRegressor(
    **best_params,
    depth=4, 
    task_type= 'CPU',   # use 'CPU' for stable CV, switch to 'GPU' if desired
    verbose= 100,
    random_seed= 42,
)

FinalCatBoostModel_NM.fit(X_train_scaled, y_train)

y_pred_log = FinalCatBoostModel_NM.predict(X_test_scaled)

import numpy as np
from sklearn.metrics import r2_score

y_pred_real = np.expm1(y_pred_log)
y_test_real = np.expm1(y_test)

print("Final R² (log scale) | After hyperparameter tuning | CatBoost Regressor :", r2_score(y_test, y_pred_log))
print("Final R² (real scale) | After hyperparameter tuning | CatBoost Regressor:", r2_score(y_test_real, y_pred_real))


# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred_log)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

0:	learn: 0.3680436	total: 1.25ms	remaining: 4.87s
100:	learn: 0.2395790	total: 91.3ms	remaining: 3.43s
200:	learn: 0.2062319	total: 158ms	remaining: 2.9s
300:	learn: 0.1816416	total: 227ms	remaining: 2.72s
400:	learn: 0.1634370	total: 292ms	remaining: 2.55s
500:	learn: 0.1485972	total: 356ms	remaining: 2.41s
600:	learn: 0.1362694	total: 427ms	remaining: 2.34s
700:	learn: 0.1260025	total: 506ms	remaining: 2.31s
800:	learn: 0.1166945	total: 582ms	remaining: 2.25s
900:	learn: 0.1077821	total: 659ms	remaining: 2.19s
1000:	learn: 0.0994732	total: 745ms	remaining: 2.16s
1100:	learn: 0.0924631	total: 820ms	remaining: 2.08s
1200:	learn: 0.0862358	total: 889ms	remaining: 2s
1300:	learn: 0.0804715	total: 960ms	remaining: 1.92s
1400:	learn: 0.0753346	total: 1.03s	remaining: 1.83s
1500:	learn: 0.0707080	total: 1.09s	remaining: 1.75s
1600:	learn: 0.0662564	total: 1.16s	remaining: 1.67s
1700:	learn: 0.0624742	total: 1.23s	remaining: 1.59s
1800:	learn: 0.0588785	total: 1.29s	remaining: 1.51s
1900:	learn: 0.0560311	total: 1.36s	remaining: 1.43s
2000:	learn: 0.0532080	total: 1.43s	remaining: 1.35s
2100:	learn: 0.0505653	total: 1.49s	remaining: 1.28s
2200:	learn: 0.0482184	total: 1.56s	remaining: 1.21s
2300:	learn: 0.0461938	total: 1.63s	remaining: 1.13s
2400:	learn: 0.0441456	total: 1.7s	remaining: 1.06s
2500:	learn: 0.0422793	total: 1.76s	remaining: 985ms
2600:	learn: 0.0404832	total: 1.82s	remaining: 912ms
2700:	learn: 0.0387864	total: 1.9s	remaining: 842ms
2800:	learn: 0.0372966	total: 1.97s	remaining: 772ms
2900:	learn: 0.0358628	total: 2.03s	remaining: 700ms
3000:	learn: 0.0345820	total: 2.1s	remaining: 629ms
3100:	learn: 0.0333683	total: 2.17s	remaining: 559ms
3200:	learn: 0.0321758	total: 2.25s	remaining: 490ms
3300:	learn: 0.0311234	total: 2.31s	remaining: 420ms
3400:	learn: 0.0301534	total: 2.38s	remaining: 350ms
3500:	learn: 0.0292268	total: 2.46s	remaining: 280ms
3600:	learn: 0.0284031	total: 2.53s	remaining: 210ms
3700:	learn: 0.0276080	total: 2.59s	remaining: 139ms
3800:	learn: 0.0268840	total: 2.67s	remaining: 69.5ms
3899:	learn: 0.0261716	total: 2.74s	remaining: 0us
Final R² (log scale) | After hyperparameter tuning | CatBoost Regressor : 0.62284949516482
Final R² (real scale) | After hyperparameter tuning | CatBoost Regressor: 0.4853041917905164
R² for DOC on normal: 0.4853041917905164
Final metrics on NORMAL scale (after inverse log):
R²   : 0.4853
MSE  : 1.6051
RMSE : 1.2669
MAE  : 0.7359

In [ ]:
#Done Completed