In [2]:
#FOR AUGMENTED_NEW

import pandas as pd
import numpy as np

aug_factor = 3 #augmented has been done initially for aug_factor = 2, then for aug_factor = 3

doc_train_augmented = pd.read_csv (f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TRAIN_AUG{aug_factor}.csv")
doc_test = pd.read_csv(f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TEST_AUG{aug_factor}.csv")

doc_train_augmented.shape, doc_test.shape

((2732, 55), (171, 55))

In [3]:
doc_train_augmented ['result_DOC_log'] = np.log1p (doc_train_augmented ['result_DOC'])
doc_test ['result_DOC_log'] = np.log1p (doc_test ['result_DOC'])
doc_train_augmented

,Unnamed: 0,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,...,B3_div_B2,ND_B4_B3,ND_B2_B3,ND_B6_B8,day_of_year,doy_sin,doy_cos,hour_sin,hour_cos,result_DOC_log
0,0,2024-05-08 14:00:00,0.037800,0.168600,0.105100,0.040100,0.063600,0.050700,0.094400,0.220200,...,1.585995,-0.112860,-0.226613,-0.130503,129,0.796183,-0.605056,-0.500000,-0.866025,0.741937
1,1,2019-08-20 15:00:00,0.068100,0.144400,0.130300,0.057300,0.075900,0.073100,0.098200,0.105800,...,1.324584,-0.018792,-0.139639,0.109596,232,-0.752667,-0.658402,-0.707107,-0.707107,1.308333
2,2,2022-02-01 20:55:00,0.015100,0.165100,0.131400,0.033200,0.053800,0.056300,0.095100,0.146200,...,1.620433,0.022706,-0.236779,-0.071156,32,0.523416,0.852078,-0.866025,0.500000,0.741937
3,3,2018-11-06 21:25:00,0.007100,0.026500,0.019000,0.019100,0.030400,0.022600,0.023400,0.014200,...,1.591540,-0.147167,-0.228278,-0.080904,310,-0.811539,0.584298,-0.707107,0.707107,1.481605
4,4,2018-11-06 19:20:00,0.001400,0.010400,0.010300,0.013300,0.020300,0.008900,0.006200,0.000000,...,1.526201,-0.390398,-0.208327,0.000000,310,-0.811539,0.584298,-0.965926,0.258819,1.193922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,2727,2019-08-20 16:00:00,0.160048,0.347841,0.301870,0.194634,0.206942,0.225023,0.253643,0.254485,...,1.063231,0.041857,-0.030649,-0.043629,232,-0.752667,-0.658402,-0.866025,-0.500000,1.536867
2728,2728,2021-08-17 15:45:00,0.106466,0.173790,0.156926,0.132880,0.156900,0.169819,0.182550,0.194755,...,1.180757,0.039542,-0.082891,0.040882,229,-0.717677,-0.696376,-0.707107,-0.707107,1.547563
2729,2729,2023-05-24 17:43:00,0.041518,0.115512,0.094602,0.046671,0.063934,0.065133,0.090442,0.112315,...,1.369847,0.009291,-0.156073,-0.035528,144,0.615285,-0.788305,-0.965926,-0.258819,1.410987
2730,2730,2018-06-19 19:24:00,0.051536,0.046751,0.038356,0.069572,0.074987,0.053739,0.051703,0.041847,...,1.077817,-0.165069,-0.037458,-0.020389,170,0.213521,-0.976938,-0.965926,0.258819,1.029619
2731,2731,2019-09-17 15:50:00,0.048440,0.116872,0.101207,0.040520,0.053809,0.062569,0.082519,0.073375,...,1.327936,0.075266,-0.140880,0.122702,260,-0.972118,-0.234491,-0.707107,-0.707107,1.280934

In [4]:
TARGET = "result_DOC_log" #FOR DOC
TARGET1 = "result_DOC"

input_features = ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 
                'B9',
               "B4_minus_B3",
               "B4_div_B3", 
               "ND_B4_B3", 
               'Temperature', 'DewPoint', 'v10n', 
               'doy_sin', 'doy_cos', 
               'latitude', 'longitude'
               ]

X_train = doc_train_augmented[input_features]
y_train = doc_train_augmented[TARGET]

X_test = doc_test[input_features]
y_test = doc_test[TARGET]

X_train.shape, y_train.shape, X_test.shape, y_test.shape

#y_test

((2732, 19), (2732,), (171, 19), (171,))

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(GradientBoostingRegressor.__module__)

sklearn.ensemble._gb

In [5]:
gbr_base_WM = GradientBoostingRegressor(
    n_estimators=1800,
    learning_rate=0.03,
    max_depth=4,
    subsample=0.8,
    random_state=42
)

gbr_base_WM.fit(X_train_scaled, y_train)
y_pred = gbr_base_WM.predict(X_test_scaled)
print("R² for DOC for log scaled | Baseline GB Regressor | WM:", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | Baseline GB Regressor | WM:", r2_score(y_test_real, y_pred_orig))


# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)

print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC for log scaled | Baseline GB Regressor | WM: 0.6834426853561297
R² for DOC on normal scaled | Baseline GB Regressor | WM: 0.5742313214591405
R² for DOC on normal: 0.5742313214591405
Final metrics on NORMAL scale (after inverse log):
R²   : 0.5742
MSE  : 1.3277
RMSE : 1.1523
MAE  : 0.6867

In [7]:
#HyperParam Tuning
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score, make_scorer
from sklearn.model_selection import RepeatedKFold, cross_val_score
import numpy as np
import optuna

#kf = KFold(n_splits=3, shuffle=True, random_state=42)

In [8]:

def objective_GBRcv_WM(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 600, 2100),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.05, log=True),
        "max_depth": trial.suggest_int("max_depth", 2, 5),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 10),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "random_state": 42
    }

    model = GradientBoostingRegressor(**params)

    # Repeated 5-fold CV, 3 repeats to reduce variance
    #rkf = RepeatedKFold(n_splits=5, n_repeats=3, random_state=42)
    r2_scorer = make_scorer(r2_score)

    scores = cross_val_score(model, X_train_scaled, y_train, cv=3, scoring=r2_scorer)
    mean_r2 = np.mean(scores)
    return mean_r2

In [9]:
study_gbr_WM = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42),
    study_name="GBR_withCV_WM"
)

study_gbr_WM.optimize(objective_GBRcv_WM, n_trials=50, show_progress_bar=True, n_jobs=-1)

[I 2026-05-31 17:59:10,219] A new study created in memory with name: GBR_withCV_WM
Best trial: 10. Best value: 0.955027:   2%|▏         | 1/50 [00:24<20:16, 24.82s/it]

[I 2026-05-31 17:59:35,035] Trial 10 finished with value: 0.9550274950343193 and parameters: {'n_estimators': 672, 'learning_rate': 0.04465283583429327, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 7, 'subsample': 0.6574258305045101}. Best is trial 10 with value: 0.9550274950343193.
[I 2026-05-31 17:59:35,085] Trial 7 finished with value: 0.759764699850364 and parameters: {'n_estimators': 658, 'learning_rate': 0.013234873176061283, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 2, 'subsample': 0.9436878951009382}. Best is trial 10 with value: 0.9550274950343193.

Best trial: 10. Best value: 0.955027:   6%|▌         | 3/50 [00:42<10:11, 13.02s/it]

[I 2026-05-31 17:59:52,808] Trial 15 finished with value: 0.9400219800854899 and parameters: {'n_estimators': 1228, 'learning_rate': 0.040396616861105336, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 6, 'subsample': 0.6818560585087862}. Best is trial 10 with value: 0.9550274950343193.

Best trial: 10. Best value: 0.955027:   8%|▊         | 4/50 [00:43<06:41,  8.73s/it]

[I 2026-05-31 17:59:53,438] Trial 9 finished with value: 0.9208314973692747 and parameters: {'n_estimators': 1158, 'learning_rate': 0.01218914521476501, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 1, 'subsample': 0.6324788066155185}. Best is trial 10 with value: 0.9550274950343193.

Best trial: 3. Best value: 0.966779:  12%|█▏        | 6/50 [00:44<03:07,  4.26s/it]

[I 2026-05-31 17:59:54,556] Trial 3 finished with value: 0.9667793095071643 and parameters: {'n_estimators': 1214, 'learning_rate': 0.03743735984784957, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 7, 'subsample': 0.6136690622705786}. Best is trial 3 with value: 0.9667793095071643.
[I 2026-05-31 17:59:54,667] Trial 13 finished with value: 0.9188088144975514 and parameters: {'n_estimators': 1211, 'learning_rate': 0.02771990020343461, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 3, 'subsample': 0.812101676108041}. Best is trial 3 with value: 0.9667793095071643.

Best trial: 3. Best value: 0.966779:  14%|█▍        | 7/50 [00:49<03:13,  4.50s/it]

[I 2026-05-31 17:59:59,690] Trial 1 finished with value: 0.8752654597787348 and parameters: {'n_estimators': 1583, 'learning_rate': 0.045665649556575455, 'max_depth': 2, 'min_samples_split': 10, 'min_samples_leaf': 3, 'subsample': 0.7236954380324465}. Best is trial 3 with value: 0.9667793095071643.

Best trial: 3. Best value: 0.966779:  16%|█▌        | 8/50 [00:53<02:56,  4.21s/it]

[I 2026-05-31 18:00:03,259] Trial 11 finished with value: 0.856438872200599 and parameters: {'n_estimators': 1491, 'learning_rate': 0.0129852530104519, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 10, 'subsample': 0.7693588532932817}. Best is trial 3 with value: 0.9667793095071643.

Best trial: 3. Best value: 0.966779:  18%|█▊        | 9/50 [00:53<02:04,  3.05s/it]

[I 2026-05-31 18:00:03,675] Trial 12 finished with value: 0.9504632904354403 and parameters: {'n_estimators': 1230, 'learning_rate': 0.020279863707344473, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 1, 'subsample': 0.8983085726604634}. Best is trial 3 with value: 0.9667793095071643.

Best trial: 3. Best value: 0.966779:  20%|██        | 10/50 [00:55<01:46,  2.67s/it]

[I 2026-05-31 18:00:05,494] Trial 4 finished with value: 0.8813403004127695 and parameters: {'n_estimators': 1516, 'learning_rate': 0.015149854831383787, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 6, 'subsample': 0.8021785668588322}. Best is trial 3 with value: 0.9667793095071643.

Best trial: 3. Best value: 0.966779:  22%|██▏       | 11/50 [00:56<01:28,  2.27s/it]

[I 2026-05-31 18:00:06,844] Trial 17 finished with value: 0.8895347073034925 and parameters: {'n_estimators': 830, 'learning_rate': 0.012634956104427211, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 4, 'subsample': 0.6326885299285893}. Best is trial 3 with value: 0.9667793095071643.

Best trial: 3. Best value: 0.966779:  24%|██▍       | 12/50 [01:01<01:50,  2.91s/it]

[I 2026-05-31 18:00:11,238] Trial 0 finished with value: 0.9539314067234518 and parameters: {'n_estimators': 1751, 'learning_rate': 0.0409556374400306, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 6, 'subsample': 0.6714431035405777}. Best is trial 3 with value: 0.9667793095071643.

Best trial: 14. Best value: 0.98021:  26%|██▌       | 13/50 [01:02<01:30,  2.45s/it]

[I 2026-05-31 18:00:12,615] Trial 14 finished with value: 0.9802097760926006 and parameters: {'n_estimators': 1393, 'learning_rate': 0.02726417045518881, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 2, 'subsample': 0.7674363894368126}. Best is trial 14 with value: 0.9802097760926006.

Best trial: 14. Best value: 0.98021:  28%|██▊       | 14/50 [01:03<01:11,  1.97s/it]

[I 2026-05-31 18:00:13,480] Trial 16 finished with value: 0.7579012801362707 and parameters: {'n_estimators': 1112, 'learning_rate': 0.023838404376772877, 'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 5, 'subsample': 0.9583558017998839}. Best is trial 14 with value: 0.9802097760926006.

Best trial: 14. Best value: 0.98021:  30%|███       | 15/50 [01:13<02:34,  4.40s/it]

[I 2026-05-31 18:00:23,529] Trial 2 finished with value: 0.9788396342637498 and parameters: {'n_estimators': 1686, 'learning_rate': 0.017528522426046435, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 1, 'subsample': 0.6819278966644384}. Best is trial 14 with value: 0.9802097760926006.

Best trial: 14. Best value: 0.98021:  32%|███▏      | 16/50 [01:18<02:35,  4.58s/it]

[I 2026-05-31 18:00:28,528] Trial 8 finished with value: 0.8868276588293812 and parameters: {'n_estimators': 2033, 'learning_rate': 0.012817385510002431, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 9, 'subsample': 0.845459857361645}. Best is trial 14 with value: 0.9802097760926006.

Best trial: 14. Best value: 0.98021:  34%|███▍      | 17/50 [01:23<02:32,  4.62s/it]

[I 2026-05-31 18:00:33,247] Trial 22 finished with value: 0.6321766373526396 and parameters: {'n_estimators': 929, 'learning_rate': 0.011634623212261382, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 6, 'subsample': 0.9936436754612192}. Best is trial 14 with value: 0.9802097760926006.

Best trial: 5. Best value: 0.981358:  36%|███▌      | 18/50 [01:23<01:47,  3.36s/it]

[I 2026-05-31 18:00:33,674] Trial 5 finished with value: 0.9813584869066299 and parameters: {'n_estimators': 1810, 'learning_rate': 0.04065879306216845, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 1, 'subsample': 0.77294204353164}. Best is trial 5 with value: 0.9813584869066299.

Best trial: 5. Best value: 0.981358:  38%|███▊      | 19/50 [01:29<02:10,  4.20s/it]

[I 2026-05-31 18:00:39,836] Trial 21 finished with value: 0.8116626020921945 and parameters: {'n_estimators': 1038, 'learning_rate': 0.014098513372533277, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 10, 'subsample': 0.9800542224153899}. Best is trial 5 with value: 0.9813584869066299.

Best trial: 5. Best value: 0.981358:  40%|████      | 20/50 [01:36<02:33,  5.10s/it]

[I 2026-05-31 18:00:47,028] Trial 6 finished with value: 0.9660890296945688 and parameters: {'n_estimators': 2090, 'learning_rate': 0.01929391022383507, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2, 'subsample': 0.9292136910313368}. Best is trial 5 with value: 0.9813584869066299.

Best trial: 5. Best value: 0.981358:  42%|████▏     | 21/50 [01:43<02:39,  5.50s/it]

[I 2026-05-31 18:00:53,464] Trial 27 finished with value: 0.9700761633932498 and parameters: {'n_estimators': 930, 'learning_rate': 0.0316115066750257, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 9, 'subsample': 0.611699312175905}. Best is trial 5 with value: 0.9813584869066299.

Best trial: 5. Best value: 0.981358:  44%|████▍     | 22/50 [01:58<03:52,  8.30s/it]

[I 2026-05-31 18:01:08,297] Trial 20 finished with value: 0.8648304410908176 and parameters: {'n_estimators': 2048, 'learning_rate': 0.03340596352778535, 'max_depth': 2, 'min_samples_split': 4, 'min_samples_leaf': 4, 'subsample': 0.8820906438067647}. Best is trial 5 with value: 0.9813584869066299.

Best trial: 5. Best value: 0.981358:  46%|████▌     | 23/50 [02:06<03:46,  8.39s/it]

[I 2026-05-31 18:01:16,901] Trial 19 finished with value: 0.9793083485344719 and parameters: {'n_estimators': 1588, 'learning_rate': 0.02282504796012552, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 2, 'subsample': 0.822066083843652}. Best is trial 5 with value: 0.9813584869066299.

Best trial: 5. Best value: 0.981358:  48%|████▊     | 24/50 [02:08<02:46,  6.42s/it]

[I 2026-05-31 18:01:18,710] Trial 18 finished with value: 0.948080035611631 and parameters: {'n_estimators': 2016, 'learning_rate': 0.012579754683938123, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 8, 'subsample': 0.6685854623698201}. Best is trial 5 with value: 0.9813584869066299.

Best trial: 5. Best value: 0.981358:  50%|█████     | 25/50 [02:27<04:15, 10.20s/it]

[I 2026-05-31 18:01:37,741] Trial 23 finished with value: 0.9640970527608242 and parameters: {'n_estimators': 2084, 'learning_rate': 0.015071895688298264, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 1, 'subsample': 0.7167438358670146}. Best is trial 5 with value: 0.9813584869066299.

Best trial: 5. Best value: 0.981358:  52%|█████▏    | 26/50 [02:28<03:01,  7.57s/it]

[I 2026-05-31 18:01:39,171] Trial 25 finished with value: 0.9794694075710737 and parameters: {'n_estimators': 2052, 'learning_rate': 0.03046003129309266, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 9, 'subsample': 0.602137482205184}. Best is trial 5 with value: 0.9813584869066299.

Best trial: 24. Best value: 0.981495:  54%|█████▍    | 27/50 [02:29<02:07,  5.54s/it]

[I 2026-05-31 18:01:39,978] Trial 24 finished with value: 0.9814947044902634 and parameters: {'n_estimators': 2001, 'learning_rate': 0.02308141551066924, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 2, 'subsample': 0.6589362874675136}. Best is trial 24 with value: 0.9814947044902634.

Best trial: 24. Best value: 0.981495:  56%|█████▌    | 28/50 [02:30<01:29,  4.06s/it]

[I 2026-05-31 18:01:40,581] Trial 26 finished with value: 0.9798203369003945 and parameters: {'n_estimators': 2043, 'learning_rate': 0.0331438904102104, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 8, 'subsample': 0.601306883632241}. Best is trial 24 with value: 0.9814947044902634.

Best trial: 24. Best value: 0.981495:  58%|█████▊    | 29/50 [02:52<03:18,  9.44s/it]

[I 2026-05-31 18:02:02,568] Trial 29 finished with value: 0.9795529013853684 and parameters: {'n_estimators': 1944, 'learning_rate': 0.030338520185905514, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 8, 'subsample': 0.8498084262333991}. Best is trial 24 with value: 0.9814947044902634.

Best trial: 24. Best value: 0.981495:  60%|██████    | 30/50 [02:55<02:29,  7.48s/it]

[I 2026-05-31 18:02:05,468] Trial 31 finished with value: 0.9801623227934941 and parameters: {'n_estimators': 1880, 'learning_rate': 0.01856802644909035, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2, 'subsample': 0.7158999016708525}. Best is trial 24 with value: 0.9814947044902634.

Best trial: 24. Best value: 0.981495:  62%|██████▏   | 31/50 [02:57<01:54,  6.02s/it]

[I 2026-05-31 18:02:08,094] Trial 32 finished with value: 0.9785983471060503 and parameters: {'n_estimators': 1815, 'learning_rate': 0.017279104497802945, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2, 'subsample': 0.7426907526203879}. Best is trial 24 with value: 0.9814947044902634.

Best trial: 24. Best value: 0.981495:  64%|██████▍   | 32/50 [02:58<01:21,  4.54s/it]

[I 2026-05-31 18:02:09,171] Trial 28 finished with value: 0.9788880965264651 and parameters: {'n_estimators': 2014, 'learning_rate': 0.029006937092575468, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 8, 'subsample': 0.8864752913099894}. Best is trial 24 with value: 0.9814947044902634.

Best trial: 24. Best value: 0.981495:  66%|██████▌   | 33/50 [03:03<01:17,  4.57s/it]

[I 2026-05-31 18:02:13,813] Trial 30 finished with value: 0.9808427463417769 and parameters: {'n_estimators': 2099, 'learning_rate': 0.018644355290114187, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'subsample': 0.7404877030569564}. Best is trial 24 with value: 0.9814947044902634.

Best trial: 24. Best value: 0.981495:  68%|██████▊   | 34/50 [03:08<01:12,  4.53s/it]

[I 2026-05-31 18:02:18,262] Trial 33 finished with value: 0.9809165307920747 and parameters: {'n_estimators': 1965, 'learning_rate': 0.031521608076804604, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'subsample': 0.752817094615258}. Best is trial 24 with value: 0.9814947044902634.

Best trial: 24. Best value: 0.981495:  70%|███████   | 35/50 [03:13<01:14,  4.95s/it]

[I 2026-05-31 18:02:24,192] Trial 34 finished with value: 0.9810722929515799 and parameters: {'n_estimators': 1934, 'learning_rate': 0.03203886838254921, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'subsample': 0.7503200323353023}. Best is trial 24 with value: 0.9814947044902634.

Best trial: 35. Best value: 0.981531:  72%|███████▏  | 36/50 [03:16<00:59,  4.25s/it]

[I 2026-05-31 18:02:26,804] Trial 35 finished with value: 0.981530736100073 and parameters: {'n_estimators': 1866, 'learning_rate': 0.03338406968671982, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'subsample': 0.7454280398307638}. Best is trial 35 with value: 0.981530736100073.

Best trial: 35. Best value: 0.981531:  74%|███████▍  | 37/50 [03:18<00:46,  3.56s/it]

[I 2026-05-31 18:02:28,744] Trial 36 finished with value: 0.9779281796398879 and parameters: {'n_estimators': 1800, 'learning_rate': 0.017317575527953787, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 1, 'subsample': 0.7333614796167625}. Best is trial 35 with value: 0.981530736100073.

Best trial: 35. Best value: 0.981531:  76%|███████▌  | 38/50 [03:50<02:25, 12.11s/it]

[I 2026-05-31 18:03:00,820] Trial 37 finished with value: 0.977862125836093 and parameters: {'n_estimators': 1815, 'learning_rate': 0.017285483761150352, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 1, 'subsample': 0.7277994956899297}. Best is trial 35 with value: 0.981530736100073.

Best trial: 35. Best value: 0.981531:  78%|███████▊  | 39/50 [04:20<03:10, 17.36s/it]

[I 2026-05-31 18:03:30,413] Trial 39 finished with value: 0.9806421709693369 and parameters: {'n_estimators': 1823, 'learning_rate': 0.02515557227365477, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 2, 'subsample': 0.7534542377769248}. Best is trial 35 with value: 0.981530736100073.

Best trial: 35. Best value: 0.981531:  80%|████████  | 40/50 [04:24<02:14, 13.41s/it]

[I 2026-05-31 18:03:34,613] Trial 38 finished with value: 0.9812670498194741 and parameters: {'n_estimators': 1894, 'learning_rate': 0.02644338509290967, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 2, 'subsample': 0.750605330027639}. Best is trial 35 with value: 0.981530736100073.

Best trial: 35. Best value: 0.981531:  82%|████████▏ | 41/50 [04:35<01:55, 12.80s/it]

[I 2026-05-31 18:03:45,987] Trial 40 finished with value: 0.9809382437658852 and parameters: {'n_estimators': 1836, 'learning_rate': 0.02595018883858975, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 2, 'subsample': 0.7636217929384319}. Best is trial 35 with value: 0.981530736100073.

Best trial: 35. Best value: 0.981531:  84%|████████▍ | 42/50 [04:37<01:15,  9.43s/it]

[I 2026-05-31 18:03:47,564] Trial 41 finished with value: 0.9806544636861908 and parameters: {'n_estimators': 1864, 'learning_rate': 0.029017118349635242, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'subsample': 0.7590812847606203}. Best is trial 35 with value: 0.981530736100073.

Best trial: 35. Best value: 0.981531:  88%|████████▊ | 44/50 [04:37<00:28,  4.76s/it]

[I 2026-05-31 18:03:47,998] Trial 43 finished with value: 0.980327366036938 and parameters: {'n_estimators': 1860, 'learning_rate': 0.025826790169759802, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3, 'subsample': 0.7547930618953724}. Best is trial 35 with value: 0.981530736100073.
[I 2026-05-31 18:03:48,161] Trial 42 finished with value: 0.9805161720261943 and parameters: {'n_estimators': 1869, 'learning_rate': 0.026235722126675427, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3, 'subsample': 0.7625376539034618}. Best is trial 35 with value: 0.981530736100073.

Best trial: 35. Best value: 0.981531:  90%|█████████ | 45/50 [04:54<00:41,  8.36s/it]

[I 2026-05-31 18:04:04,905] Trial 44 finished with value: 0.9803170321688128 and parameters: {'n_estimators': 1878, 'learning_rate': 0.04962043577699763, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'subsample': 0.768694421753058}. Best is trial 35 with value: 0.981530736100073.

Best trial: 35. Best value: 0.981531:  92%|█████████▏| 46/50 [04:55<00:24,  6.12s/it]

[I 2026-05-31 18:04:05,801] Trial 45 finished with value: 0.9804230681430224 and parameters: {'n_estimators': 1864, 'learning_rate': 0.024636294230002263, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3, 'subsample': 0.7608796740583881}. Best is trial 35 with value: 0.981530736100073.
[I 2026-05-31 18:04:05,975] Trial 48 finished with value: 0.9802075349444781 and parameters: {'n_estimators': 1722, 'learning_rate': 0.026022188907820775, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3, 'subsample': 0.7675698909380004}. Best is trial 35 with value: 0.981530736100073.

Best trial: 35. Best value: 0.981531:  94%|█████████▍| 47/50 [04:55<00:13,  4.33s/it]

[I 2026-05-31 18:04:06,015] Trial 46 finished with value: 0.9802239200982331 and parameters: {'n_estimators': 1834, 'learning_rate': 0.025589470924868647, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3, 'subsample': 0.7540852140093028}. Best is trial 35 with value: 0.981530736100073.

Best trial: 35. Best value: 0.981531:  98%|█████████▊| 49/50 [04:56<00:02,  2.58s/it]

[I 2026-05-31 18:04:07,044] Trial 47 finished with value: 0.9804885842354993 and parameters: {'n_estimators': 1857, 'learning_rate': 0.026224769048508678, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3, 'subsample': 0.7579969906259203}. Best is trial 35 with value: 0.981530736100073.

Best trial: 35. Best value: 0.981531: 100%|██████████| 50/50 [04:57<00:00,  5.96s/it]

[I 2026-05-31 18:04:08,108] Trial 49 finished with value: 0.9654030530402499 and parameters: {'n_estimators': 1744, 'learning_rate': 0.010228463559691519, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3, 'subsample': 0.7701042278024717}. Best is trial 35 with value: 0.981530736100073.

In [10]:
print(study_gbr_WM.best_params)
print(study_gbr_WM.best_value)

{'n_estimators': 1866, 'learning_rate': 0.03338406968671982, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'subsample': 0.7454280398307638}
0.981530736100073

In [11]:
best_params_WM = study_gbr_WM.best_params
print(best_params_WM)

{'n_estimators': 1866, 'learning_rate': 0.03338406968671982, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'subsample': 0.7454280398307638}

In [12]:
best_params = best_params_WM

best_gbr_WM = GradientBoostingRegressor(
    **best_params,
    random_state=42
)

best_gbr_WM.fit(X_train_scaled, y_train)
y_pred = best_gbr_WM.predict(X_test_scaled)

print("R² for DOC for log scaled | GBR With Meteo:", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | GBR With meteo:", r2_score(y_test_real, y_pred_orig))



# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))


# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC for log scaled | GBR With Meteo: 0.6706543028759859
R² for DOC on normal scaled | GBR With meteo: 0.5385103841547108
R² for DOC on normal: 0.5385103841547108
Final metrics on NORMAL scale (after inverse log):
R²   : 0.5385
MSE  : 1.4391
RMSE : 1.1996
MAE  : 0.7045

In [ ]:
#NoMeteo

In [6]:
#FOR AUGMENTED_NEW

import pandas as pd
import numpy as np

aug_factor = 3 #augmented has been done initially for aug_factor = 2, then for aug_factor = 3

doc_train_augmented = pd.read_csv (f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TRAIN_AUG{aug_factor}.csv")
doc_test = pd.read_csv(f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TEST_AUG{aug_factor}.csv")

doc_train_augmented.shape, doc_test.shape

((2732, 55), (171, 55))

In [7]:
doc_train_augmented ['result_DOC_log'] = np.log1p (doc_train_augmented ['result_DOC'])
doc_test ['result_DOC_log'] = np.log1p (doc_test ['result_DOC'])
doc_train_augmented

,Unnamed: 0,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,...,B3_div_B2,ND_B4_B3,ND_B2_B3,ND_B6_B8,day_of_year,doy_sin,doy_cos,hour_sin,hour_cos,result_DOC_log
0,0,2024-05-08 14:00:00,0.037800,0.168600,0.105100,0.040100,0.063600,0.050700,0.094400,0.220200,...,1.585995,-0.112860,-0.226613,-0.130503,129,0.796183,-0.605056,-0.500000,-0.866025,0.741937
1,1,2019-08-20 15:00:00,0.068100,0.144400,0.130300,0.057300,0.075900,0.073100,0.098200,0.105800,...,1.324584,-0.018792,-0.139639,0.109596,232,-0.752667,-0.658402,-0.707107,-0.707107,1.308333
2,2,2022-02-01 20:55:00,0.015100,0.165100,0.131400,0.033200,0.053800,0.056300,0.095100,0.146200,...,1.620433,0.022706,-0.236779,-0.071156,32,0.523416,0.852078,-0.866025,0.500000,0.741937
3,3,2018-11-06 21:25:00,0.007100,0.026500,0.019000,0.019100,0.030400,0.022600,0.023400,0.014200,...,1.591540,-0.147167,-0.228278,-0.080904,310,-0.811539,0.584298,-0.707107,0.707107,1.481605
4,4,2018-11-06 19:20:00,0.001400,0.010400,0.010300,0.013300,0.020300,0.008900,0.006200,0.000000,...,1.526201,-0.390398,-0.208327,0.000000,310,-0.811539,0.584298,-0.965926,0.258819,1.193922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,2727,2019-08-20 16:00:00,0.160048,0.347841,0.301870,0.194634,0.206942,0.225023,0.253643,0.254485,...,1.063231,0.041857,-0.030649,-0.043629,232,-0.752667,-0.658402,-0.866025,-0.500000,1.536867
2728,2728,2021-08-17 15:45:00,0.106466,0.173790,0.156926,0.132880,0.156900,0.169819,0.182550,0.194755,...,1.180757,0.039542,-0.082891,0.040882,229,-0.717677,-0.696376,-0.707107,-0.707107,1.547563
2729,2729,2023-05-24 17:43:00,0.041518,0.115512,0.094602,0.046671,0.063934,0.065133,0.090442,0.112315,...,1.369847,0.009291,-0.156073,-0.035528,144,0.615285,-0.788305,-0.965926,-0.258819,1.410987
2730,2730,2018-06-19 19:24:00,0.051536,0.046751,0.038356,0.069572,0.074987,0.053739,0.051703,0.041847,...,1.077817,-0.165069,-0.037458,-0.020389,170,0.213521,-0.976938,-0.965926,0.258819,1.029619
2731,2731,2019-09-17 15:50:00,0.048440,0.116872,0.101207,0.040520,0.053809,0.062569,0.082519,0.073375,...,1.327936,0.075266,-0.140880,0.122702,260,-0.972118,-0.234491,-0.707107,-0.707107,1.280934

In [8]:
TARGET = "result_DOC_log" #FOR DOC
TARGET1 = "result_DOC"

input_features_noMeteo = ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 
                'B9',
               "B4_minus_B3",
               "B4_div_B3", 
               "ND_B4_B3", 
               
               #'Temperature', 'DewPoint', 'v10n', #'Precipitation(mm)',
               'doy_sin', 'doy_cos', 
               'latitude', 'longitude'
               ]

X_train = doc_train_augmented[input_features_noMeteo]
y_train = doc_train_augmented[TARGET]

X_test = doc_test[input_features_noMeteo]
y_test = doc_test[TARGET]

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2732, 16), (2732,), (171, 16), (171,))

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(GradientBoostingRegressor.__module__)

sklearn.ensemble._gb

In [20]:
gbr_base_NM = GradientBoostingRegressor(
     n_estimators=1800,
    learning_rate=0.03,
    max_depth=4,
    subsample=1.0,
    random_state=42,
)

gbr_base_NM.fit(X_train, y_train)
y_pred = gbr_base_NM.predict(X_test)
print("R² for DOC for log scaled | Baseline GB Regressor | NM:", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | Baseline GB Regressor | NM:", r2_score(y_test_real, y_pred_orig))


# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)

print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC for log scaled | Baseline GB Regressor | NM: 0.6423082688185041
R² for DOC on normal scaled | Baseline GB Regressor | NM: 0.5200194422764177
R² for DOC on normal: 0.5200194422764177
Final metrics on NORMAL scale (after inverse log):
R²   : 0.5200
MSE  : 1.4968
RMSE : 1.2234
MAE  : 0.6958

In [11]:
#HyperParam Tuning
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score, make_scorer
from sklearn.model_selection import RepeatedKFold, cross_val_score
import numpy as np
import optuna

#kf = KFold(n_splits=3, shuffle=True, random_state=42)

In [12]:
def objective_GBRcv_NM(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 600, 2100),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.05, log=True),
        "max_depth": trial.suggest_int("max_depth", 2, 5),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 10),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "random_state": 42
    }

    model = GradientBoostingRegressor(**params)
    r2_scorer = make_scorer(r2_score)

    scores = cross_val_score(model, X_train_scaled, y_train, cv=3, scoring=r2_scorer)
    mean_r2 = np.mean(scores)
    return mean_r2

In [13]:
study_gbr_NM = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42),
    study_name="GBR_withCV_NM"
)

study_gbr_NM.optimize(objective_GBRcv_NM, n_trials=50, show_progress_bar=True, n_jobs=-1)

[I 2026-05-31 18:36:17,805] A new study created in memory with name: GBR_withCV_NM
Best trial: 11. Best value: 0.797734:   2%|▏         | 1/50 [00:24<19:52, 24.33s/it]

[I 2026-05-31 18:36:42,104] Trial 11 finished with value: 0.7977342465952196 and parameters: {'n_estimators': 791, 'learning_rate': 0.04771608710648337, 'max_depth': 2, 'min_samples_split': 3, 'min_samples_leaf': 6, 'subsample': 0.678229146142738}. Best is trial 11 with value: 0.7977342465952196.

Best trial: 11. Best value: 0.797734:   4%|▍         | 2/50 [00:24<08:11, 10.24s/it]

[I 2026-05-31 18:36:42,499] Trial 4 finished with value: 0.7526276866695691 and parameters: {'n_estimators': 825, 'learning_rate': 0.031488811537033784, 'max_depth': 2, 'min_samples_split': 3, 'min_samples_leaf': 7, 'subsample': 0.6626847498778725}. Best is trial 11 with value: 0.7977342465952196.

Best trial: 11. Best value: 0.797734:   6%|▌         | 3/50 [00:25<04:38,  5.93s/it]

[I 2026-05-31 18:36:43,297] Trial 13 finished with value: 0.773469364671008 and parameters: {'n_estimators': 713, 'learning_rate': 0.016217608233979764, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 7, 'subsample': 0.9743130366117032}. Best is trial 11 with value: 0.7977342465952196.

Best trial: 2. Best value: 0.861881:   8%|▊         | 4/50 [00:37<06:27,  8.43s/it]

[I 2026-05-31 18:36:55,554] Trial 2 finished with value: 0.8618814980142991 and parameters: {'n_estimators': 1050, 'learning_rate': 0.02116826794660613, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 6, 'subsample': 0.8676088480972036}. Best is trial 2 with value: 0.8618814980142991.

Best trial: 2. Best value: 0.861881:  10%|█         | 5/50 [00:38<04:11,  5.59s/it]

[I 2026-05-31 18:36:56,102] Trial 14 finished with value: 0.683832720370436 and parameters: {'n_estimators': 1208, 'learning_rate': 0.013286491325275514, 'max_depth': 2, 'min_samples_split': 4, 'min_samples_leaf': 10, 'subsample': 0.8320601918768065}. Best is trial 2 with value: 0.8618814980142991.

Best trial: 0. Best value: 0.967707:  12%|█▏        | 6/50 [00:45<04:31,  6.17s/it]

[I 2026-05-31 18:37:03,326] Trial 0 finished with value: 0.9677072813042495 and parameters: {'n_estimators': 1055, 'learning_rate': 0.023894136675026892, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2, 'subsample': 0.7541254616464466}. Best is trial 0 with value: 0.9677072813042495.
[I 2026-05-31 18:37:03,425] Trial 15 finished with value: 0.8077455627639205 and parameters: {'n_estimators': 1402, 'learning_rate': 0.029735125007635133, 'max_depth': 2, 'min_samples_split': 10, 'min_samples_leaf': 6, 'subsample': 0.7619514357505706}. Best is trial 0 with value: 0.9677072813042495.

Best trial: 0. Best value: 0.967707:  16%|█▌        | 8/50 [00:59<04:40,  6.67s/it]

[I 2026-05-31 18:37:17,791] Trial 1 finished with value: 0.699748941971769 and parameters: {'n_estimators': 1737, 'learning_rate': 0.010080436200589335, 'max_depth': 2, 'min_samples_split': 8, 'min_samples_leaf': 4, 'subsample': 0.7798811837066977}. Best is trial 0 with value: 0.9677072813042495.

Best trial: 5. Best value: 0.974127:  18%|█▊        | 9/50 [01:01<03:42,  5.42s/it]

[I 2026-05-31 18:37:19,652] Trial 5 finished with value: 0.9741273085965828 and parameters: {'n_estimators': 1449, 'learning_rate': 0.046496903033891444, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 5, 'subsample': 0.6140133446196306}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  20%|██        | 10/50 [01:03<02:53,  4.33s/it]

[I 2026-05-31 18:37:21,038] Trial 18 finished with value: 0.9328980133423302 and parameters: {'n_estimators': 761, 'learning_rate': 0.016207253138266407, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 6, 'subsample': 0.6915533671689855}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  22%|██▏       | 11/50 [01:09<03:12,  4.93s/it]

[I 2026-05-31 18:37:27,535] Trial 6 finished with value: 0.9373764174011509 and parameters: {'n_estimators': 1847, 'learning_rate': 0.0324795996252894, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 7, 'subsample': 0.6972905825744243}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  24%|██▍       | 12/50 [01:10<02:16,  3.60s/it]

[I 2026-05-31 18:37:27,804] Trial 16 finished with value: 0.9290505683219795 and parameters: {'n_estimators': 959, 'learning_rate': 0.020993642418082298, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 4, 'subsample': 0.8464574449876376}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  26%|██▌       | 13/50 [01:11<01:46,  2.87s/it]

[I 2026-05-31 18:37:28,871] Trial 10 finished with value: 0.9509101956215874 and parameters: {'n_estimators': 1876, 'learning_rate': 0.0414779275877963, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 2, 'subsample': 0.728798345920688}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  28%|██▊       | 14/50 [01:12<01:30,  2.52s/it]

[I 2026-05-31 18:37:30,544] Trial 17 finished with value: 0.8824408243964541 and parameters: {'n_estimators': 1011, 'learning_rate': 0.011446626519557327, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 3, 'subsample': 0.8870543351163225}. Best is trial 5 with value: 0.9741273085965828.
[I 2026-05-31 18:37:30,603] Trial 3 finished with value: 0.9442533481400958 and parameters: {'n_estimators': 1877, 'learning_rate': 0.03609540983516467, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 6, 'subsample': 0.8212342003908556}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  32%|███▏      | 16/50 [01:15<01:08,  2.02s/it]

[I 2026-05-31 18:37:33,379] Trial 12 finished with value: 0.9492704922845102 and parameters: {'n_estimators': 2058, 'learning_rate': 0.03867123624929257, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 4, 'subsample': 0.6301302460888372}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  34%|███▍      | 17/50 [01:17<01:04,  1.95s/it]

[I 2026-05-31 18:37:35,112] Trial 22 finished with value: 0.8018394040449746 and parameters: {'n_estimators': 869, 'learning_rate': 0.04503798481106738, 'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 3, 'subsample': 0.759518927700553}. Best is trial 5 with value: 0.9741273085965828.
[I 2026-05-31 18:37:35,205] Trial 9 finished with value: 0.9545645546327587 and parameters: {'n_estimators': 1729, 'learning_rate': 0.011081825986090655, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 6, 'subsample': 0.7426847884687761}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  38%|███▊      | 19/50 [01:19<00:49,  1.60s/it]

[I 2026-05-31 18:37:37,320] Trial 8 finished with value: 0.9724996659021224 and parameters: {'n_estimators': 1785, 'learning_rate': 0.01837658824075666, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 2, 'subsample': 0.6813584834454365}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  40%|████      | 20/50 [01:20<00:44,  1.47s/it]

[I 2026-05-31 18:37:38,346] Trial 7 finished with value: 0.956079712797315 and parameters: {'n_estimators': 1638, 'learning_rate': 0.016123959566831637, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 10, 'subsample': 0.9206663229886274}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  42%|████▏     | 21/50 [01:51<04:12,  8.72s/it]

[I 2026-05-31 18:38:09,393] Trial 21 finished with value: 0.9397973563381008 and parameters: {'n_estimators': 1491, 'learning_rate': 0.01448688754317918, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 1, 'subsample': 0.7168698887925077}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  44%|████▍     | 22/50 [01:57<03:46,  8.10s/it]

[I 2026-05-31 18:38:15,726] Trial 20 finished with value: 0.9640179466761954 and parameters: {'n_estimators': 1820, 'learning_rate': 0.03039353824975825, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 6, 'subsample': 0.6523068298375266}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  46%|████▌     | 23/50 [01:58<02:41,  6.00s/it]

[I 2026-05-31 18:38:16,040] Trial 19 finished with value: 0.9673904687011031 and parameters: {'n_estimators': 1830, 'learning_rate': 0.042728050232867756, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 7, 'subsample': 0.6580128634187293}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  48%|████▊     | 24/50 [02:02<02:23,  5.51s/it]

[I 2026-05-31 18:38:20,296] Trial 24 finished with value: 0.8690303123189533 and parameters: {'n_estimators': 1780, 'learning_rate': 0.04059429513112537, 'max_depth': 2, 'min_samples_split': 4, 'min_samples_leaf': 2, 'subsample': 0.6065995318908884}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  50%|█████     | 25/50 [02:07<02:15,  5.42s/it]

[I 2026-05-31 18:38:25,482] Trial 23 finished with value: 0.923904121974585 and parameters: {'n_estimators': 1609, 'learning_rate': 0.033694758157634966, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 10, 'subsample': 0.9492815347491006}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 5. Best value: 0.974127:  52%|█████▏    | 26/50 [02:14<02:19,  5.83s/it]

[I 2026-05-31 18:38:32,305] Trial 28 finished with value: 0.9725626179192761 and parameters: {'n_estimators': 1419, 'learning_rate': 0.026160059264355624, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'subsample': 0.6008647071612538}. Best is trial 5 with value: 0.9741273085965828.

Best trial: 27. Best value: 0.975276:  54%|█████▍    | 27/50 [02:15<01:42,  4.47s/it]

[I 2026-05-31 18:38:33,512] Trial 27 finished with value: 0.9752760211411627 and parameters: {'n_estimators': 1448, 'learning_rate': 0.04953110623778672, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'subsample': 0.6216638078288265}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  56%|█████▌    | 28/50 [02:19<01:30,  4.13s/it]

[I 2026-05-31 18:38:36,808] Trial 26 finished with value: 0.9748144782079518 and parameters: {'n_estimators': 1542, 'learning_rate': 0.04583285022463259, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'subsample': 0.604754512060604}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  58%|█████▊    | 29/50 [02:19<01:03,  3.02s/it]

[I 2026-05-31 18:38:37,199] Trial 31 finished with value: 0.9722647169934665 and parameters: {'n_estimators': 1415, 'learning_rate': 0.026765418474110753, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'subsample': 0.6093884712516434}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  60%|██████    | 30/50 [02:21<00:53,  2.66s/it]

[I 2026-05-31 18:38:39,020] Trial 30 finished with value: 0.972025105946709 and parameters: {'n_estimators': 1511, 'learning_rate': 0.02377932338075336, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'subsample': 0.6188565653198681}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  62%|██████▏   | 31/50 [02:23<00:46,  2.47s/it]

[I 2026-05-31 18:38:41,046] Trial 34 finished with value: 0.9601704415380058 and parameters: {'n_estimators': 1479, 'learning_rate': 0.02472261307395224, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 1, 'subsample': 0.6210247512562941}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  66%|██████▌   | 33/50 [02:24<00:25,  1.48s/it]

[I 2026-05-31 18:38:42,070] Trial 25 finished with value: 0.9687841407115446 and parameters: {'n_estimators': 1932, 'learning_rate': 0.045314495582663344, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 1, 'subsample': 0.6018340103024581}. Best is trial 27 with value: 0.9752760211411627.
[I 2026-05-31 18:38:42,239] Trial 29 finished with value: 0.9730632544641115 and parameters: {'n_estimators': 1584, 'learning_rate': 0.026046174237416293, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'subsample': 0.6125685481810118}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  68%|██████▊   | 34/50 [02:24<00:17,  1.07s/it]

[I 2026-05-31 18:38:42,354] Trial 32 finished with value: 0.9726997400859281 and parameters: {'n_estimators': 1467, 'learning_rate': 0.027406995275078117, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'subsample': 0.6013554238845522}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  70%|███████   | 35/50 [02:24<00:12,  1.22it/s]

[I 2026-05-31 18:38:42,586] Trial 35 finished with value: 0.9611231407312745 and parameters: {'n_estimators': 1492, 'learning_rate': 0.02563920491751923, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 1, 'subsample': 0.6053962144052509}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  72%|███████▏  | 36/50 [02:25<00:09,  1.45it/s]

[I 2026-05-31 18:38:42,977] Trial 33 finished with value: 0.971803724297394 and parameters: {'n_estimators': 1468, 'learning_rate': 0.02342784954051505, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'subsample': 0.6076624966530204}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  74%|███████▍  | 37/50 [02:48<01:38,  7.55s/it]

[I 2026-05-31 18:39:06,551] Trial 36 finished with value: 0.9697073480281643 and parameters: {'n_estimators': 1222, 'learning_rate': 0.02424712222910612, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'subsample': 0.6061558843359226}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  76%|███████▌  | 38/50 [02:52<01:16,  6.35s/it]

[I 2026-05-31 18:39:10,085] Trial 38 finished with value: 0.9703469073091543 and parameters: {'n_estimators': 1177, 'learning_rate': 0.025274389033071054, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'subsample': 0.6053594297156314}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  78%|███████▊  | 39/50 [02:52<00:50,  4.62s/it]

[I 2026-05-31 18:39:10,684] Trial 37 finished with value: 0.9650757334098556 and parameters: {'n_estimators': 1194, 'learning_rate': 0.01910209036093183, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'subsample': 0.6132905676580787}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  80%|████████  | 40/50 [02:59<00:53,  5.35s/it]

[I 2026-05-31 18:39:17,743] Trial 39 finished with value: 0.9711721250773785 and parameters: {'n_estimators': 1285, 'learning_rate': 0.025226666143075442, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'subsample': 0.6198758059672801}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  82%|████████▏ | 41/50 [03:00<00:35,  3.89s/it]

[I 2026-05-31 18:39:18,228] Trial 40 finished with value: 0.9704232554420228 and parameters: {'n_estimators': 1193, 'learning_rate': 0.024044233901292712, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'subsample': 0.616694223654677}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  84%|████████▍ | 42/50 [03:08<00:40,  5.03s/it]

[I 2026-05-31 18:39:25,918] Trial 41 finished with value: 0.9714520619356678 and parameters: {'n_estimators': 1318, 'learning_rate': 0.025847574467026443, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'subsample': 0.6049991125005512}. Best is trial 27 with value: 0.9752760211411627.
[I 2026-05-31 18:39:25,970] Trial 44 finished with value: 0.9738567324580921 and parameters: {'n_estimators': 1207, 'learning_rate': 0.04961665358230739, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 3, 'subsample': 0.6266575787120094}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  88%|████████▊ | 44/50 [03:08<00:17,  2.84s/it]

[I 2026-05-31 18:39:26,472] Trial 42 finished with value: 0.9710960510906005 and parameters: {'n_estimators': 1325, 'learning_rate': 0.02528354058238485, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 1, 'subsample': 0.6002018343309949}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  90%|█████████ | 45/50 [03:09<00:11,  2.34s/it]

[I 2026-05-31 18:39:27,294] Trial 43 finished with value: 0.9707517946898827 and parameters: {'n_estimators': 1265, 'learning_rate': 0.04854073303049401, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 9, 'subsample': 0.6345831247157558}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  92%|█████████▏| 46/50 [03:10<00:07,  1.99s/it]

[I 2026-05-31 18:39:28,319] Trial 46 finished with value: 0.9738260580277628 and parameters: {'n_estimators': 1216, 'learning_rate': 0.045130756770029624, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 3, 'subsample': 0.6418308299568489}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  94%|█████████▍| 47/50 [03:10<00:04,  1.58s/it]

[I 2026-05-31 18:39:28,797] Trial 45 finished with value: 0.9711124631542657 and parameters: {'n_estimators': 1284, 'learning_rate': 0.04964999195191972, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 9, 'subsample': 0.6520213630557925}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276:  96%|█████████▌| 48/50 [03:11<00:02,  1.25s/it]

[I 2026-05-31 18:39:29,188] Trial 49 finished with value: 0.9745128869386618 and parameters: {'n_estimators': 1233, 'learning_rate': 0.03763150657251105, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 3, 'subsample': 0.643028855699224}. Best is trial 27 with value: 0.9752760211411627.

Best trial: 27. Best value: 0.975276: 100%|██████████| 50/50 [03:11<00:00,  3.84s/it]

[I 2026-05-31 18:39:29,634] Trial 48 finished with value: 0.974320173423724 and parameters: {'n_estimators': 1265, 'learning_rate': 0.049057264003382554, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 3, 'subsample': 0.6412019033451641}. Best is trial 27 with value: 0.9752760211411627.
[I 2026-05-31 18:39:29,694] Trial 47 finished with value: 0.9735370307791021 and parameters: {'n_estimators': 1260, 'learning_rate': 0.049751016925567264, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 3, 'subsample': 0.6472178528422614}. Best is trial 27 with value: 0.9752760211411627.

In [14]:
print(study_gbr_NM.best_params)
print(study_gbr_NM.best_value)

{'n_estimators': 1448, 'learning_rate': 0.04953110623778672, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'subsample': 0.6216638078288265}
0.9752760211411627

In [15]:
best_params_NM = study_gbr_NM.best_params
print(best_params_NM)

{'n_estimators': 1448, 'learning_rate': 0.04953110623778672, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'subsample': 0.6216638078288265}

In [16]:
best_params = best_params_NM

best_gbr_NM = GradientBoostingRegressor(
    **best_params,
    random_state=42
)

best_gbr_NM.fit(X_train_scaled, y_train)
y_pred = best_gbr_NM.predict(X_test_scaled)

print("R² for DOC for log scaled | GBR With no Meteo:", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | GBR With no meteo:", r2_score(y_test_real, y_pred_orig))



# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))


# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC for log scaled | GBR With no Meteo: 0.6488844034170084
R² for DOC on normal scaled | GBR With no meteo: 0.5182612472419021
R² for DOC on normal: 0.5182612472419021
Final metrics on NORMAL scale (after inverse log):
R²   : 0.5183
MSE  : 1.5023
RMSE : 1.2257
MAE  : 0.7076

In [ ]:
#Completed