In [2]:
#FOR AUGMENTED_NEW

import pandas as pd
import numpy as np

aug_factor = 3 #augmented has been done initially for aug_factor = 2, then for aug_factor = 3

doc_train_augmented = pd.read_csv (f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TRAIN_AUG{aug_factor}.csv")
doc_test = pd.read_csv(f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TEST_AUG{aug_factor}.csv")

doc_train_augmented.shape, doc_test.shape

((2732, 55), (171, 55))

In [1]:
print("Hello world")

Hello world

In [3]:
doc_train_augmented ['result_DOC_log'] = np.log1p (doc_train_augmented ['result_DOC'])
doc_test ['result_DOC_log'] = np.log1p (doc_test ['result_DOC'])
doc_train_augmented

,Unnamed: 0,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,...,B3_div_B2,ND_B4_B3,ND_B2_B3,ND_B6_B8,day_of_year,doy_sin,doy_cos,hour_sin,hour_cos,result_DOC_log
0,0,2024-05-08 14:00:00,0.037800,0.168600,0.105100,0.040100,0.063600,0.050700,0.094400,0.220200,...,1.585995,-0.112860,-0.226613,-0.130503,129,0.796183,-0.605056,-0.500000,-0.866025,0.741937
1,1,2019-08-20 15:00:00,0.068100,0.144400,0.130300,0.057300,0.075900,0.073100,0.098200,0.105800,...,1.324584,-0.018792,-0.139639,0.109596,232,-0.752667,-0.658402,-0.707107,-0.707107,1.308333
2,2,2022-02-01 20:55:00,0.015100,0.165100,0.131400,0.033200,0.053800,0.056300,0.095100,0.146200,...,1.620433,0.022706,-0.236779,-0.071156,32,0.523416,0.852078,-0.866025,0.500000,0.741937
3,3,2018-11-06 21:25:00,0.007100,0.026500,0.019000,0.019100,0.030400,0.022600,0.023400,0.014200,...,1.591540,-0.147167,-0.228278,-0.080904,310,-0.811539,0.584298,-0.707107,0.707107,1.481605
4,4,2018-11-06 19:20:00,0.001400,0.010400,0.010300,0.013300,0.020300,0.008900,0.006200,0.000000,...,1.526201,-0.390398,-0.208327,0.000000,310,-0.811539,0.584298,-0.965926,0.258819,1.193922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,2727,2019-08-20 16:00:00,0.160048,0.347841,0.301870,0.194634,0.206942,0.225023,0.253643,0.254485,...,1.063231,0.041857,-0.030649,-0.043629,232,-0.752667,-0.658402,-0.866025,-0.500000,1.536867
2728,2728,2021-08-17 15:45:00,0.106466,0.173790,0.156926,0.132880,0.156900,0.169819,0.182550,0.194755,...,1.180757,0.039542,-0.082891,0.040882,229,-0.717677,-0.696376,-0.707107,-0.707107,1.547563
2729,2729,2023-05-24 17:43:00,0.041518,0.115512,0.094602,0.046671,0.063934,0.065133,0.090442,0.112315,...,1.369847,0.009291,-0.156073,-0.035528,144,0.615285,-0.788305,-0.965926,-0.258819,1.410987
2730,2730,2018-06-19 19:24:00,0.051536,0.046751,0.038356,0.069572,0.074987,0.053739,0.051703,0.041847,...,1.077817,-0.165069,-0.037458,-0.020389,170,0.213521,-0.976938,-0.965926,0.258819,1.029619
2731,2731,2019-09-17 15:50:00,0.048440,0.116872,0.101207,0.040520,0.053809,0.062569,0.082519,0.073375,...,1.327936,0.075266,-0.140880,0.122702,260,-0.972118,-0.234491,-0.707107,-0.707107,1.280934

In [4]:
TARGET = "result_DOC_log" #FOR DOC
TARGET1 = "result_DOC"

input_features = ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 
                'B9',
               "B4_minus_B3",
               "B4_div_B3", 
               "ND_B4_B3", 
               'Temperature', 'DewPoint', 'v10n', 
               'doy_sin', 'doy_cos', 
               'latitude', 'longitude'
               ]

X_train = doc_train_augmented[input_features]
y_train = doc_train_augmented[TARGET]

X_test = doc_test[input_features]
y_test = doc_test[TARGET]

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2732, 19), (2732,), (171, 19), (171,))

In [5]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
from sklearn.ensemble import RandomForestRegressor 

print(RandomForestRegressor.__module__)

sklearn.ensemble._forest

In [29]:
baseline_RF = RandomForestRegressor(
    n_estimators=1800,
    max_depth= 20,
    min_samples_leaf=9,
    min_samples_split = 3,
    random_state=42,
    criterion='squared_error',
    n_jobs=-1
)

baseline_RF.fit(X_train, y_train)

y_pred = baseline_RF.predict(X_test)

print("R² for DOC for log scaled | Baseline Random Forest Regressor:", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | Baseline Random Forest Regressor:", r2_score(y_test_real, y_pred_orig))



# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC for log scaled | Baseline Random Forest Regressor: 0.6475368905861247
R² for DOC on normal scaled | Baseline Random Forest Regressor: 0.5479910049871333
R² for DOC on normal: 0.5479910049871333
Final metrics on NORMAL scale (after inverse log):
R²   : 0.5480
MSE  : 1.4096
RMSE : 1.1873
MAE  : 0.7074

In [7]:
#Hyper Paramater tuning using Optuna
from sklearn.model_selection import KFold
import numpy as np
import optuna
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [8]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score

def objective_rf_cv_WM(trial):
    # Define hyperparameter search space
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 1000, 3000),
        "max_depth": trial.suggest_int("max_depth", 5, 30),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 10),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 6),
        "random_state": 42,
        "n_jobs": -1
    }

    # Initialize model
    #model = RandomForestRegressor(**params)
    
    model = Pipeline([
        ("scaler", StandardScaler()),
        ("rf", RandomForestRegressor(**params))
    ])

    scores = cross_val_score(
        model,
        X_train,  
        y_train,
        cv=3,
        scoring="r2",
        n_jobs=-1
    )

    # Return mean R² as Optuna objective
    return scores.mean()

In [9]:
study_rf_WM = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42),
    study_name="RF_StandardScaled_withCV"
)

study_rf_WM.optimize(
    objective_rf_cv_WM,
    n_trials=50,
    show_progress_bar=True
)

[I 2026-05-31 18:54:12,576] A new study created in memory with name: RF_StandardScaled_withCV
Best trial: 0. Best value: 0.922129:   2%|▏         | 1/50 [00:08<06:46,  8.29s/it]

[I 2026-05-31 18:54:20,864] Trial 0 finished with value: 0.9221289583931092 and parameters: {'n_estimators': 1749, 'max_depth': 29, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9221289583931092.

Best trial: 0. Best value: 0.922129:   4%|▍         | 2/50 [00:13<05:19,  6.65s/it]

[I 2026-05-31 18:54:26,361] Trial 1 finished with value: 0.8508530458620145 and parameters: {'n_estimators': 1312, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.9221289583931092.

Best trial: 0. Best value: 0.922129:   6%|▌         | 3/50 [00:22<06:04,  7.76s/it]

[I 2026-05-31 18:54:35,455] Trial 2 finished with value: 0.8878979932776908 and parameters: {'n_estimators': 2202, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.9221289583931092.

Best trial: 0. Best value: 0.922129:   8%|▊         | 4/50 [00:33<06:53,  8.98s/it]

[I 2026-05-31 18:54:46,294] Trial 3 finished with value: 0.9165657846742211 and parameters: {'n_estimators': 2665, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9221289583931092.

Best trial: 4. Best value: 0.952528:  10%|█         | 5/50 [00:45<07:28,  9.96s/it]

[I 2026-05-31 18:54:58,008] Trial 4 finished with value: 0.9525281753659106 and parameters: {'n_estimators': 1608, 'max_depth': 18, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 4 with value: 0.9525281753659106.

Best trial: 4. Best value: 0.952528:  12%|█▏        | 6/50 [00:54<07:03,  9.62s/it]

[I 2026-05-31 18:55:06,972] Trial 5 finished with value: 0.854300234567989 and parameters: {'n_estimators': 2224, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 4 with value: 0.9525281753659106.

Best trial: 4. Best value: 0.952528:  14%|█▍        | 7/50 [01:01<06:21,  8.87s/it]

[I 2026-05-31 18:55:14,299] Trial 6 finished with value: 0.9222447858645223 and parameters: {'n_estimators': 1912, 'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 4 with value: 0.9525281753659106.

Best trial: 4. Best value: 0.952528:  16%|█▌        | 8/50 [01:07<05:28,  7.81s/it]

[I 2026-05-31 18:55:19,846] Trial 7 finished with value: 0.7546956299075394 and parameters: {'n_estimators': 2185, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 4 with value: 0.9525281753659106.

Best trial: 4. Best value: 0.952528:  18%|█▊        | 9/50 [01:11<04:40,  6.83s/it]

[I 2026-05-31 18:55:24,513] Trial 8 finished with value: 0.9051902027343542 and parameters: {'n_estimators': 1130, 'max_depth': 29, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 4 with value: 0.9525281753659106.

Best trial: 4. Best value: 0.952528:  20%|██        | 10/50 [01:17<04:19,  6.48s/it]

[I 2026-05-31 18:55:30,218] Trial 9 finished with value: 0.8055993419236839 and parameters: {'n_estimators': 1609, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 4 with value: 0.9525281753659106.

Best trial: 10. Best value: 0.956218:  22%|██▏       | 11/50 [01:33<06:00,  9.25s/it]

[I 2026-05-31 18:55:45,750] Trial 10 finished with value: 0.9562177496840132 and parameters: {'n_estimators': 2891, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.9562177496840132.

Best trial: 11. Best value: 0.957938:  24%|██▍       | 12/50 [01:49<07:08, 11.29s/it]

[I 2026-05-31 18:56:01,686] Trial 11 finished with value: 0.95793832946247 and parameters: {'n_estimators': 2872, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.95793832946247.

Best trial: 11. Best value: 0.957938:  26%|██▌       | 13/50 [02:05<07:56, 12.87s/it]

[I 2026-05-31 18:56:18,196] Trial 12 finished with value: 0.9515265045841855 and parameters: {'n_estimators': 2963, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.95793832946247.

Best trial: 13. Best value: 0.957942:  28%|██▊       | 14/50 [02:21<08:18, 13.85s/it]

[I 2026-05-31 18:56:34,308] Trial 13 finished with value: 0.9579417676591179 and parameters: {'n_estimators': 2700, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 13 with value: 0.9579417676591179.

Best trial: 13. Best value: 0.957942:  30%|███       | 15/50 [02:37<08:28, 14.52s/it]

[I 2026-05-31 18:56:50,401] Trial 14 finished with value: 0.9555732664290592 and parameters: {'n_estimators': 2567, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 13 with value: 0.9579417676591179.

Best trial: 13. Best value: 0.957942:  32%|███▏      | 16/50 [02:53<08:29, 15.00s/it]

[I 2026-05-31 18:57:06,497] Trial 15 finished with value: 0.9528391327346234 and parameters: {'n_estimators': 2563, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 13 with value: 0.9579417676591179.

Best trial: 13. Best value: 0.957942:  34%|███▍      | 17/50 [03:13<08:55, 16.24s/it]

[I 2026-05-31 18:57:25,617] Trial 16 finished with value: 0.9534954758140309 and parameters: {'n_estimators': 2729, 'max_depth': 21, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 13 with value: 0.9579417676591179.

Best trial: 13. Best value: 0.957942:  36%|███▌      | 18/50 [03:29<08:38, 16.21s/it]

[I 2026-05-31 18:57:41,769] Trial 17 finished with value: 0.9263843238222008 and parameters: {'n_estimators': 2443, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 13 with value: 0.9579417676591179.

Best trial: 13. Best value: 0.957942:  38%|███▊      | 19/50 [03:49<09:05, 17.59s/it]

[I 2026-05-31 18:58:02,575] Trial 18 finished with value: 0.9337046665362765 and parameters: {'n_estimators': 2834, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 13 with value: 0.9579417676591179.

Best trial: 13. Best value: 0.957942:  40%|████      | 20/50 [04:38<13:22, 26.76s/it]

[I 2026-05-31 18:58:50,701] Trial 19 finished with value: 0.9400142697618626 and parameters: {'n_estimators': 2390, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 13 with value: 0.9579417676591179.

Best trial: 13. Best value: 0.957942:  42%|████▏     | 21/50 [05:21<15:18, 31.66s/it]

[I 2026-05-31 18:59:33,770] Trial 20 finished with value: 0.9051386313345894 and parameters: {'n_estimators': 2998, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 13 with value: 0.9579417676591179.

Best trial: 21. Best value: 0.957953:  44%|████▍     | 22/50 [05:40<13:06, 28.10s/it]

[I 2026-05-31 18:59:53,567] Trial 21 finished with value: 0.9579529132536936 and parameters: {'n_estimators': 2822, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 21 with value: 0.9579529132536936.

Best trial: 22. Best value: 0.95904:  46%|████▌     | 23/50 [06:03<11:56, 26.54s/it]

[I 2026-05-31 19:00:16,494] Trial 22 finished with value: 0.9590400383524035 and parameters: {'n_estimators': 2748, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 22 with value: 0.9590400383524035.

Best trial: 22. Best value: 0.95904:  48%|████▊     | 24/50 [06:25<10:49, 24.99s/it]

[I 2026-05-31 19:00:37,846] Trial 23 finished with value: 0.949055807657491 and parameters: {'n_estimators': 2699, 'max_depth': 22, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 22 with value: 0.9590400383524035.

Best trial: 24. Best value: 0.966939:  50%|█████     | 25/50 [06:45<09:50, 23.63s/it]

[I 2026-05-31 19:00:58,321] Trial 24 finished with value: 0.9669394509299729 and parameters: {'n_estimators': 2440, 'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 24 with value: 0.9669394509299729.

Best trial: 25. Best value: 0.96696:  52%|█████▏    | 26/50 [07:30<12:01, 30.08s/it]

[I 2026-05-31 19:01:43,450] Trial 25 finished with value: 0.9669597591317572 and parameters: {'n_estimators': 2411, 'max_depth': 26, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 25 with value: 0.9669597591317572.

Best trial: 25. Best value: 0.96696:  54%|█████▍    | 27/50 [08:23<14:06, 36.79s/it]

[I 2026-05-31 19:02:35,884] Trial 26 finished with value: 0.9570629877542305 and parameters: {'n_estimators': 2379, 'max_depth': 26, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 25 with value: 0.9669597591317572.

Best trial: 25. Best value: 0.96696:  56%|█████▌    | 28/50 [08:41<11:24, 31.11s/it]

[I 2026-05-31 19:02:53,760] Trial 27 finished with value: 0.9401651808899003 and parameters: {'n_estimators': 2086, 'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 25 with value: 0.9669597591317572.

Best trial: 25. Best value: 0.96696:  58%|█████▊    | 29/50 [08:52<08:47, 25.13s/it]

[I 2026-05-31 19:03:04,931] Trial 28 finished with value: 0.9669042528439883 and parameters: {'n_estimators': 2476, 'max_depth': 24, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 25 with value: 0.9669597591317572.

Best trial: 25. Best value: 0.96696:  60%|██████    | 30/50 [09:00<06:38, 19.95s/it]

[I 2026-05-31 19:03:12,790] Trial 29 finished with value: 0.9221930941255154 and parameters: {'n_estimators': 1854, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 25 with value: 0.9669597591317572.

Best trial: 25. Best value: 0.96696:  62%|██████▏   | 31/50 [09:13<05:40, 17.91s/it]

[I 2026-05-31 19:03:25,927] Trial 30 finished with value: 0.9569607110206038 and parameters: {'n_estimators': 2323, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 25 with value: 0.9669597591317572.

Best trial: 25. Best value: 0.96696:  64%|██████▍   | 32/50 [09:28<05:07, 17.09s/it]

[I 2026-05-31 19:03:41,101] Trial 31 finished with value: 0.9646919348491642 and parameters: {'n_estimators': 2511, 'max_depth': 27, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 25 with value: 0.9669597591317572.

Best trial: 25. Best value: 0.96696:  66%|██████▌   | 33/50 [09:44<04:42, 16.63s/it]

[I 2026-05-31 19:03:56,661] Trial 32 finished with value: 0.9646833927104749 and parameters: {'n_estimators': 2519, 'max_depth': 28, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 25 with value: 0.9669597591317572.

Best trial: 33. Best value: 0.966978:  68%|██████▊   | 34/50 [09:57<04:12, 15.77s/it]

[I 2026-05-31 19:04:10,431] Trial 33 finished with value: 0.9669777696358746 and parameters: {'n_estimators': 2077, 'max_depth': 28, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  70%|███████   | 35/50 [10:10<03:44, 14.96s/it]

[I 2026-05-31 19:04:23,493] Trial 34 finished with value: 0.9569445277374075 and parameters: {'n_estimators': 2038, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  72%|███████▏  | 36/50 [10:27<03:37, 15.52s/it]

[I 2026-05-31 19:04:40,336] Trial 35 finished with value: 0.9669628029657131 and parameters: {'n_estimators': 2306, 'max_depth': 28, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  74%|███████▍  | 37/50 [10:45<03:31, 16.23s/it]

[I 2026-05-31 19:04:58,219] Trial 36 finished with value: 0.9570475968843645 and parameters: {'n_estimators': 2269, 'max_depth': 30, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  76%|███████▌  | 38/50 [11:01<03:12, 16.07s/it]

[I 2026-05-31 19:05:13,897] Trial 37 finished with value: 0.8879730603724519 and parameters: {'n_estimators': 2126, 'max_depth': 28, 'min_samples_split': 3, 'min_samples_leaf': 6}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  78%|███████▊  | 39/50 [11:18<03:01, 16.48s/it]

[I 2026-05-31 19:05:31,349] Trial 38 finished with value: 0.966936118908392 and parameters: {'n_estimators': 1917, 'max_depth': 27, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  80%|████████  | 40/50 [11:30<02:30, 15.03s/it]

[I 2026-05-31 19:05:42,989] Trial 39 finished with value: 0.9051997018517212 and parameters: {'n_estimators': 1721, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  82%|████████▏ | 41/50 [11:46<02:18, 15.37s/it]

[I 2026-05-31 19:05:59,160] Trial 40 finished with value: 0.9401388664846947 and parameters: {'n_estimators': 2196, 'max_depth': 29, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  84%|████████▍ | 42/50 [12:03<02:05, 15.74s/it]

[I 2026-05-31 19:06:15,760] Trial 41 finished with value: 0.9669384622413899 and parameters: {'n_estimators': 1922, 'max_depth': 27, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  86%|████████▌ | 43/50 [12:20<01:53, 16.17s/it]

[I 2026-05-31 19:06:32,931] Trial 42 finished with value: 0.9668310333905626 and parameters: {'n_estimators': 1469, 'max_depth': 27, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  88%|████████▊ | 44/50 [13:03<02:24, 24.13s/it]

[I 2026-05-31 19:07:15,631] Trial 43 finished with value: 0.9569910623586825 and parameters: {'n_estimators': 1975, 'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  90%|█████████ | 45/50 [13:41<02:22, 28.47s/it]

[I 2026-05-31 19:07:54,216] Trial 44 finished with value: 0.9646453185657248 and parameters: {'n_estimators': 1817, 'max_depth': 29, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  92%|█████████▏| 46/50 [14:28<02:15, 33.85s/it]

[I 2026-05-31 19:08:40,620] Trial 45 finished with value: 0.956944012376756 and parameters: {'n_estimators': 2143, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  94%|█████████▍| 47/50 [15:19<01:57, 39.08s/it]

[I 2026-05-31 19:09:31,914] Trial 46 finished with value: 0.9669375856490948 and parameters: {'n_estimators': 2285, 'max_depth': 28, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  96%|█████████▌| 48/50 [15:29<01:00, 30.48s/it]

[I 2026-05-31 19:09:42,337] Trial 47 finished with value: 0.9646584189559194 and parameters: {'n_estimators': 2036, 'max_depth': 26, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 33. Best value: 0.966978:  98%|█████████▊| 49/50 [15:36<00:23, 23.51s/it]

[I 2026-05-31 19:09:49,568] Trial 48 finished with value: 0.9569928889284353 and parameters: {'n_estimators': 1697, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 33 with value: 0.9669777696358746.

Best trial: 49. Best value: 0.967663: 100%|██████████| 50/50 [15:47<00:00, 18.96s/it]

[I 2026-05-31 19:10:00,437] Trial 49 finished with value: 0.9676634258287992 and parameters: {'n_estimators': 2339, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 49 with value: 0.9676634258287992.

In [10]:
print(study_rf_WM.best_params)
print(study_rf_WM.best_value)

{'n_estimators': 2339, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 1}
0.9676634258287992

In [11]:
best_params_WM = study_rf_WM.best_params
print(best_params_WM)

{'n_estimators': 2339, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 1}

In [12]:
best_params = best_params_WM

best_rf_scaled = Pipeline(
    steps=[
        ("scaler", StandardScaler()),
        ("rf", RandomForestRegressor(
            **best_params,
            random_state=42,
            n_jobs=-1
        ))
    ]
)

best_rf_scaled.fit(X_train, y_train)
y_pred = best_rf_scaled.predict(X_test)

print("R² for DOC for log scaled | Random Forest Regressor:", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | Random Forest Regressor:", r2_score(y_test_real, y_pred_orig))




# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC for log scaled | Random Forest Regressor: 0.6125067711573633
R² for DOC on normal scaled | Random Forest Regressor: 0.46403129910193486
R² for DOC on normal: 0.46403129910193486
Final metrics on NORMAL scale (after inverse log):
R²   : 0.4640
MSE  : 1.6714
RMSE : 1.2928
MAE  : 0.7373

In [ ]:
#No meteo features

In [13]:
#FOR AUGMENTED_NEW

import pandas as pd
import numpy as np

aug_factor = 3 #augmented has been done initially for aug_factor = 2, then for aug_factor = 3

doc_train_augmented = pd.read_csv (f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TRAIN_AUG{aug_factor}.csv")
doc_test = pd.read_csv(f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TEST_AUG{aug_factor}.csv")

doc_train_augmented.shape, doc_test.shape

((2732, 55), (171, 55))

In [14]:
doc_train_augmented ['result_DOC_log'] = np.log1p (doc_train_augmented ['result_DOC'])
doc_test ['result_DOC_log'] = np.log1p (doc_test ['result_DOC'])
doc_train_augmented

,Unnamed: 0,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,...,B3_div_B2,ND_B4_B3,ND_B2_B3,ND_B6_B8,day_of_year,doy_sin,doy_cos,hour_sin,hour_cos,result_DOC_log
0,0,2024-05-08 14:00:00,0.037800,0.168600,0.105100,0.040100,0.063600,0.050700,0.094400,0.220200,...,1.585995,-0.112860,-0.226613,-0.130503,129,0.796183,-0.605056,-0.500000,-0.866025,0.741937
1,1,2019-08-20 15:00:00,0.068100,0.144400,0.130300,0.057300,0.075900,0.073100,0.098200,0.105800,...,1.324584,-0.018792,-0.139639,0.109596,232,-0.752667,-0.658402,-0.707107,-0.707107,1.308333
2,2,2022-02-01 20:55:00,0.015100,0.165100,0.131400,0.033200,0.053800,0.056300,0.095100,0.146200,...,1.620433,0.022706,-0.236779,-0.071156,32,0.523416,0.852078,-0.866025,0.500000,0.741937
3,3,2018-11-06 21:25:00,0.007100,0.026500,0.019000,0.019100,0.030400,0.022600,0.023400,0.014200,...,1.591540,-0.147167,-0.228278,-0.080904,310,-0.811539,0.584298,-0.707107,0.707107,1.481605
4,4,2018-11-06 19:20:00,0.001400,0.010400,0.010300,0.013300,0.020300,0.008900,0.006200,0.000000,...,1.526201,-0.390398,-0.208327,0.000000,310,-0.811539,0.584298,-0.965926,0.258819,1.193922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,2727,2019-08-20 16:00:00,0.160048,0.347841,0.301870,0.194634,0.206942,0.225023,0.253643,0.254485,...,1.063231,0.041857,-0.030649,-0.043629,232,-0.752667,-0.658402,-0.866025,-0.500000,1.536867
2728,2728,2021-08-17 15:45:00,0.106466,0.173790,0.156926,0.132880,0.156900,0.169819,0.182550,0.194755,...,1.180757,0.039542,-0.082891,0.040882,229,-0.717677,-0.696376,-0.707107,-0.707107,1.547563
2729,2729,2023-05-24 17:43:00,0.041518,0.115512,0.094602,0.046671,0.063934,0.065133,0.090442,0.112315,...,1.369847,0.009291,-0.156073,-0.035528,144,0.615285,-0.788305,-0.965926,-0.258819,1.410987
2730,2730,2018-06-19 19:24:00,0.051536,0.046751,0.038356,0.069572,0.074987,0.053739,0.051703,0.041847,...,1.077817,-0.165069,-0.037458,-0.020389,170,0.213521,-0.976938,-0.965926,0.258819,1.029619
2731,2731,2019-09-17 15:50:00,0.048440,0.116872,0.101207,0.040520,0.053809,0.062569,0.082519,0.073375,...,1.327936,0.075266,-0.140880,0.122702,260,-0.972118,-0.234491,-0.707107,-0.707107,1.280934

In [15]:
TARGET = "result_DOC_log" #FOR DOC
TARGET1 = "result_DOC"

input_features_noMeteo = ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 
                'B9',
               "B4_minus_B3",
               "B4_div_B3",  
               "ND_B4_B3", 
               #'Temperature', 'DewPoint', 'v10n', #'Precipitation(mm)',
               'doy_sin', 'doy_cos',  
               'latitude', 'longitude'
               ]

X_train = doc_train_augmented[input_features_noMeteo]
y_train = doc_train_augmented[TARGET]

X_test = doc_test[input_features_noMeteo]
y_test = doc_test[TARGET]

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2732, 16), (2732,), (171, 16), (171,))

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
from sklearn.ensemble import RandomForestRegressor 

print(RandomForestRegressor.__module__)

sklearn.ensemble._forest

In [42]:

baseline_RF_NM = RandomForestRegressor(
    n_estimators=1800,
    max_depth= 20,
    min_samples_leaf=9,
    min_samples_split = 3,
    random_state=42,
    criterion='squared_error',
    n_jobs=-1
)

baseline_RF_NM.fit(X_train, y_train)

y_pred = baseline_RF_NM.predict(X_test)

print("R² for DOC for log scaled | Baseline Random Forest Regressor | No Meteo", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | Baseline Random Forest Regressor | No Meteo ", r2_score(y_test_real, y_pred_orig))




# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC for log scaled | Baseline Random Forest Regressor | No Meteo 0.6294628973291008
R² for DOC on normal scaled | Baseline Random Forest Regressor | No Meteo  0.5404027435571124
R² for DOC on normal: 0.5404027435571124
Final metrics on NORMAL scale (after inverse log):
R²   : 0.5404
MSE  : 1.4332
RMSE : 1.1972
MAE  : 0.7207

In [7]:
#HyperParam Tuning

In [17]:
#Hyper Paramater tuning using Optuna
from sklearn.model_selection import KFold
import numpy as np
import optuna
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [20]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score

def objective_rf_cv_NM(trial):
    # Define hyperparameter search space
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 1000, 3000),
        "max_depth": trial.suggest_int("max_depth", 5, 30),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 10),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 6),
        "random_state": 42,
        "n_jobs": -1
    }

    # Initialize model
    #model = RandomForestRegressor(**params)
    model = Pipeline([
        ("scaler", StandardScaler()),
        ("rf", RandomForestRegressor(**params))
       
    ])
    

    # 3-fold cross-validation on scaled features
    scores = cross_val_score(
        model,
        X_train, 
        y_train,
        cv=3,
        scoring="r2",
        n_jobs=-1
    )

    # Return mean R² as Optuna objective
    return scores.mean()

In [21]:
study_rf_noNM = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42),
    study_name="RF_withCV_NM"
)

study_rf_noNM.optimize(
    objective_rf_cv_NM,
    n_trials=50,
    show_progress_bar=True
)

[I 2026-05-31 19:12:33,395] A new study created in memory with name: RF_withCV_NM
Best trial: 0. Best value: 0.910498:   2%|▏         | 1/50 [00:19<16:00, 19.59s/it]

[I 2026-05-31 19:12:52,990] Trial 0 finished with value: 0.9104976101227539 and parameters: {'n_estimators': 1749, 'max_depth': 29, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9104976101227539.

Best trial: 0. Best value: 0.910498:   4%|▍         | 2/50 [00:33<12:49, 16.03s/it]

[I 2026-05-31 19:13:06,518] Trial 1 finished with value: 0.8402706083344822 and parameters: {'n_estimators': 1312, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.9104976101227539.

Best trial: 0. Best value: 0.910498:   6%|▌         | 3/50 [01:04<18:13, 23.26s/it]

[I 2026-05-31 19:13:38,378] Trial 2 finished with value: 0.8733803983139782 and parameters: {'n_estimators': 2202, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.9104976101227539.

Best trial: 3. Best value: 0.912747:   8%|▊         | 4/50 [01:36<20:25, 26.65s/it]

[I 2026-05-31 19:14:10,218] Trial 3 finished with value: 0.9127469108230765 and parameters: {'n_estimators': 2665, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 3 with value: 0.9127469108230765.

Best trial: 4. Best value: 0.946465:  10%|█         | 5/50 [01:43<14:42, 19.62s/it]

[I 2026-05-31 19:14:17,393] Trial 4 finished with value: 0.946465066061359 and parameters: {'n_estimators': 1608, 'max_depth': 18, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 4 with value: 0.946465066061359.

Best trial: 4. Best value: 0.946465:  12%|█▏        | 6/50 [01:49<10:54, 14.87s/it]

[I 2026-05-31 19:14:23,029] Trial 5 finished with value: 0.8498957658087828 and parameters: {'n_estimators': 2224, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 4 with value: 0.946465066061359.

Best trial: 4. Best value: 0.946465:  14%|█▍        | 7/50 [01:55<08:34, 11.96s/it]

[I 2026-05-31 19:14:29,015] Trial 6 finished with value: 0.9105703978705458 and parameters: {'n_estimators': 1912, 'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 4 with value: 0.946465066061359.

Best trial: 4. Best value: 0.946465:  16%|█▌        | 8/50 [02:00<06:45,  9.65s/it]

[I 2026-05-31 19:14:33,723] Trial 7 finished with value: 0.7511781061227002 and parameters: {'n_estimators': 2185, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 4 with value: 0.946465066061359.

Best trial: 4. Best value: 0.946465:  18%|█▊        | 9/50 [02:03<05:16,  7.71s/it]

[I 2026-05-31 19:14:37,163] Trial 8 finished with value: 0.8920081837419312 and parameters: {'n_estimators': 1130, 'max_depth': 29, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 4 with value: 0.946465066061359.

Best trial: 4. Best value: 0.946465:  20%|██        | 10/50 [02:07<04:20,  6.52s/it]

[I 2026-05-31 19:14:41,019] Trial 9 finished with value: 0.8027843457016872 and parameters: {'n_estimators': 1609, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 4 with value: 0.946465066061359.

Best trial: 10. Best value: 0.951786:  22%|██▏       | 11/50 [02:17<04:56,  7.61s/it]

[I 2026-05-31 19:14:51,098] Trial 10 finished with value: 0.9517858385655614 and parameters: {'n_estimators': 2891, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.9517858385655614.

Best trial: 11. Best value: 0.953413:  24%|██▍       | 12/50 [02:27<05:18,  8.38s/it]

[I 2026-05-31 19:15:01,225] Trial 11 finished with value: 0.9534130957707632 and parameters: {'n_estimators': 2872, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.9534130957707632.

Best trial: 11. Best value: 0.953413:  26%|██▌       | 13/50 [02:38<05:40,  9.21s/it]

[I 2026-05-31 19:15:12,357] Trial 12 finished with value: 0.947102348582369 and parameters: {'n_estimators': 2963, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.9534130957707632.

Best trial: 13. Best value: 0.953443:  28%|██▊       | 14/50 [02:50<05:52,  9.80s/it]

[I 2026-05-31 19:15:23,515] Trial 13 finished with value: 0.9534430256333186 and parameters: {'n_estimators': 2700, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 13 with value: 0.9534430256333186.

Best trial: 13. Best value: 0.953443:  30%|███       | 15/50 [03:01<05:54, 10.14s/it]

[I 2026-05-31 19:15:34,432] Trial 14 finished with value: 0.9505620023580011 and parameters: {'n_estimators': 2567, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 13 with value: 0.9534430256333186.

Best trial: 13. Best value: 0.953443:  32%|███▏      | 16/50 [03:11<05:49, 10.28s/it]

[I 2026-05-31 19:15:45,045] Trial 15 finished with value: 0.9492660476276632 and parameters: {'n_estimators': 2563, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 13 with value: 0.9534430256333186.

Best trial: 13. Best value: 0.953443:  34%|███▍      | 17/50 [03:23<05:53, 10.73s/it]

[I 2026-05-31 19:15:56,809] Trial 16 finished with value: 0.9471773886868308 and parameters: {'n_estimators': 2729, 'max_depth': 21, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 13 with value: 0.9534430256333186.

Best trial: 13. Best value: 0.953443:  36%|███▌      | 18/50 [03:33<05:33, 10.41s/it]

[I 2026-05-31 19:16:06,487] Trial 17 finished with value: 0.9184156428597069 and parameters: {'n_estimators': 2443, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 13 with value: 0.9534430256333186.

Best trial: 13. Best value: 0.953443:  38%|███▊      | 19/50 [03:45<05:37, 10.88s/it]

[I 2026-05-31 19:16:18,467] Trial 18 finished with value: 0.9270837826460822 and parameters: {'n_estimators': 2834, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 13 with value: 0.9534430256333186.

Best trial: 13. Best value: 0.953443:  40%|████      | 20/50 [03:55<05:21, 10.72s/it]

[I 2026-05-31 19:16:28,809] Trial 19 finished with value: 0.9353459464224635 and parameters: {'n_estimators': 2390, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 13 with value: 0.9534430256333186.

Best trial: 13. Best value: 0.953443:  42%|████▏     | 21/50 [04:07<05:25, 11.23s/it]

[I 2026-05-31 19:16:41,215] Trial 20 finished with value: 0.8919175772653 and parameters: {'n_estimators': 2998, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 13 with value: 0.9534430256333186.

Best trial: 13. Best value: 0.953443:  44%|████▍     | 22/50 [04:21<05:36, 12.02s/it]

[I 2026-05-31 19:16:55,097] Trial 21 finished with value: 0.9534255267162947 and parameters: {'n_estimators': 2822, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 13 with value: 0.9534430256333186.

Best trial: 22. Best value: 0.954367:  46%|████▌     | 23/50 [04:35<05:39, 12.59s/it]

[I 2026-05-31 19:17:08,994] Trial 22 finished with value: 0.9543672113428263 and parameters: {'n_estimators': 2748, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 22 with value: 0.9543672113428263.

Best trial: 22. Best value: 0.954367:  48%|████▊     | 24/50 [04:49<05:36, 12.95s/it]

[I 2026-05-31 19:17:22,794] Trial 23 finished with value: 0.9427136093093992 and parameters: {'n_estimators': 2699, 'max_depth': 22, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 22 with value: 0.9543672113428263.

Best trial: 24. Best value: 0.962307:  50%|█████     | 25/50 [05:03<05:31, 13.25s/it]

[I 2026-05-31 19:17:36,742] Trial 24 finished with value: 0.9623067900747723 and parameters: {'n_estimators': 2440, 'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 24 with value: 0.9623067900747723.

Best trial: 24. Best value: 0.962307:  52%|█████▏    | 26/50 [05:17<05:27, 13.64s/it]

[I 2026-05-31 19:17:51,296] Trial 25 finished with value: 0.9622837589915206 and parameters: {'n_estimators': 2411, 'max_depth': 26, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 24 with value: 0.9623067900747723.

Best trial: 24. Best value: 0.962307:  54%|█████▍    | 27/50 [05:32<05:18, 13.84s/it]

[I 2026-05-31 19:18:05,603] Trial 26 finished with value: 0.9508444911641406 and parameters: {'n_estimators': 2379, 'max_depth': 26, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 24 with value: 0.9623067900747723.

Best trial: 24. Best value: 0.962307:  56%|█████▌    | 28/50 [05:44<04:57, 13.51s/it]

[I 2026-05-31 19:18:18,328] Trial 27 finished with value: 0.9306969781880919 and parameters: {'n_estimators': 2086, 'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 24 with value: 0.9623067900747723.

Best trial: 28. Best value: 0.962345:  58%|█████▊    | 29/50 [06:02<05:06, 14.59s/it]

[I 2026-05-31 19:18:35,462] Trial 28 finished with value: 0.9623453490250964 and parameters: {'n_estimators': 2476, 'max_depth': 24, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  60%|██████    | 30/50 [06:13<04:31, 13.56s/it]

[I 2026-05-31 19:18:46,601] Trial 29 finished with value: 0.9105922997674482 and parameters: {'n_estimators': 1854, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  62%|██████▏   | 31/50 [06:28<04:26, 14.01s/it]

[I 2026-05-31 19:19:01,665] Trial 30 finished with value: 0.9508424957473318 and parameters: {'n_estimators': 2323, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  64%|██████▍   | 32/50 [06:45<04:27, 14.87s/it]

[I 2026-05-31 19:19:18,543] Trial 31 finished with value: 0.9596826820704787 and parameters: {'n_estimators': 2511, 'max_depth': 27, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  66%|██████▌   | 33/50 [07:01<04:22, 15.44s/it]

[I 2026-05-31 19:19:35,306] Trial 32 finished with value: 0.9597015338447633 and parameters: {'n_estimators': 2519, 'max_depth': 28, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  68%|██████▊   | 34/50 [07:16<04:01, 15.06s/it]

[I 2026-05-31 19:19:49,494] Trial 33 finished with value: 0.9621891292327652 and parameters: {'n_estimators': 2077, 'max_depth': 29, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  70%|███████   | 35/50 [07:29<03:37, 14.51s/it]

[I 2026-05-31 19:20:02,701] Trial 34 finished with value: 0.950656863276007 and parameters: {'n_estimators': 2038, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  72%|███████▏  | 36/50 [07:44<03:27, 14.79s/it]

[I 2026-05-31 19:20:18,165] Trial 35 finished with value: 0.962267551227844 and parameters: {'n_estimators': 2306, 'max_depth': 28, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  74%|███████▍  | 37/50 [07:58<03:06, 14.36s/it]

[I 2026-05-31 19:20:31,499] Trial 36 finished with value: 0.9508203158824825 and parameters: {'n_estimators': 2198, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  76%|███████▌  | 38/50 [08:09<02:42, 13.50s/it]

[I 2026-05-31 19:20:43,017] Trial 37 finished with value: 0.8733442933548474 and parameters: {'n_estimators': 2274, 'max_depth': 27, 'min_samples_split': 3, 'min_samples_leaf': 6}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  78%|███████▊  | 39/50 [08:25<02:36, 14.27s/it]

[I 2026-05-31 19:20:59,058] Trial 38 finished with value: 0.9308015464085377 and parameters: {'n_estimators': 2603, 'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  80%|████████  | 40/50 [08:38<02:17, 13.75s/it]

[I 2026-05-31 19:21:11,603] Trial 39 finished with value: 0.8920745132971835 and parameters: {'n_estimators': 2453, 'max_depth': 30, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  82%|████████▏ | 41/50 [08:51<02:02, 13.64s/it]

[I 2026-05-31 19:21:24,989] Trial 40 finished with value: 0.9508263709220501 and parameters: {'n_estimators': 2301, 'max_depth': 22, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  84%|████████▍ | 42/50 [09:06<01:51, 13.90s/it]

[I 2026-05-31 19:21:39,480] Trial 41 finished with value: 0.9622430666947969 and parameters: {'n_estimators': 2131, 'max_depth': 28, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 28. Best value: 0.962345:  86%|████████▌ | 43/50 [09:19<01:35, 13.64s/it]

[I 2026-05-31 19:21:52,534] Trial 42 finished with value: 0.9622297089579911 and parameters: {'n_estimators': 1900, 'max_depth': 28, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 28 with value: 0.9623453490250964.

Best trial: 43. Best value: 0.963278:  88%|████████▊ | 44/50 [09:30<01:17, 12.87s/it]

[I 2026-05-31 19:22:03,593] Trial 43 finished with value: 0.9632781322000525 and parameters: {'n_estimators': 1688, 'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 43 with value: 0.9632781322000525.

Best trial: 43. Best value: 0.963278:  90%|█████████ | 45/50 [09:40<01:00, 12.11s/it]

[I 2026-05-31 19:22:13,941] Trial 44 finished with value: 0.963259946648598 and parameters: {'n_estimators': 1478, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 43 with value: 0.9632781322000525.

Best trial: 43. Best value: 0.963278:  92%|█████████▏| 46/50 [09:50<00:45, 11.34s/it]

[I 2026-05-31 19:22:23,491] Trial 45 finished with value: 0.9507207663790865 and parameters: {'n_estimators': 1479, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 43 with value: 0.9632781322000525.

Best trial: 43. Best value: 0.963278:  94%|█████████▍| 47/50 [10:00<00:33, 11.17s/it]

[I 2026-05-31 19:22:34,263] Trial 46 finished with value: 0.9632520519059086 and parameters: {'n_estimators': 1673, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 43 with value: 0.9632781322000525.

Best trial: 43. Best value: 0.963278:  96%|█████████▌| 48/50 [10:12<00:22, 11.18s/it]

[I 2026-05-31 19:22:45,477] Trial 47 finished with value: 0.9632333322082692 and parameters: {'n_estimators': 1667, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 43 with value: 0.9632781322000525.

Best trial: 43. Best value: 0.963278:  98%|█████████▊| 49/50 [10:21<00:10, 10.79s/it]

[I 2026-05-31 19:22:55,348] Trial 48 finished with value: 0.950707164831112 and parameters: {'n_estimators': 1635, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 43 with value: 0.9632781322000525.

Best trial: 43. Best value: 0.963278: 100%|██████████| 50/50 [10:30<00:00, 12.62s/it]

[I 2026-05-31 19:23:04,379] Trial 49 finished with value: 0.9628907406218324 and parameters: {'n_estimators': 1343, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 43 with value: 0.9632781322000525.

In [22]:
print(study_rf_noNM.best_params)
print(study_rf_noNM.best_value)

{'n_estimators': 1688, 'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 1}
0.9632781322000525

In [24]:
best_params_NM = {'n_estimators': 1688, 'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 1}
print(best_params_NM)

{'n_estimators': 1688, 'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 1}

In [25]:
best_params_NM = {'n_estimators': 1688, 'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 1}

In [26]:
best_params = best_params_NM

best_rf_scaled_NM = Pipeline(
    steps=[
        ("scaler", StandardScaler()),
        ("rf", RandomForestRegressor(
            **best_params,
            random_state=42,
            n_jobs=-1
        ))
    ]
)

best_rf_scaled_NM.fit(X_train, y_train)
y_pred = best_rf_scaled_NM.predict(X_test)

print("R² for DOC for log scaled | Random Forest Regressor | NM", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | Random Forest Regressor | NM", r2_score(y_test_real, y_pred_orig))


# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC for log scaled | Random Forest Regressor | NM 0.5989285305653615
R² for DOC on normal scaled | Random Forest Regressor | NM 0.4770366584452679
R² for DOC on normal: 0.4770366584452679
Final metrics on NORMAL scale (after inverse log):
R²   : 0.4770
MSE  : 1.6308
RMSE : 1.2770
MAE  : 0.7443

In [ ]:
#Completed