In [39]:
#FOR AUGMENTED_NEW

import pandas as pd
import numpy as np

aug_factor = 3 #augmented has been done initially for aug_factor = 2, then for aug_factor = 3


doc_train_augmented = pd.read_csv (f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TRAIN_AUG{aug_factor}.csv")
doc_test = pd.read_csv(f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TEST_AUG{aug_factor}.csv")

doc_train_augmented.shape, doc_test.shape

((2732, 55), (171, 55))

In [40]:
doc_train_augmented ['result_DOC_log'] = np.log1p (doc_train_augmented ['result_DOC'])
doc_test ['result_DOC_log'] = np.log1p (doc_test ['result_DOC'])
doc_train_augmented

,Unnamed: 0,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,...,B3_div_B2,ND_B4_B3,ND_B2_B3,ND_B6_B8,day_of_year,doy_sin,doy_cos,hour_sin,hour_cos,result_DOC_log
0,0,2024-05-08 14:00:00,0.037800,0.168600,0.105100,0.040100,0.063600,0.050700,0.094400,0.220200,...,1.585995,-0.112860,-0.226613,-0.130503,129,0.796183,-0.605056,-0.500000,-0.866025,0.741937
1,1,2019-08-20 15:00:00,0.068100,0.144400,0.130300,0.057300,0.075900,0.073100,0.098200,0.105800,...,1.324584,-0.018792,-0.139639,0.109596,232,-0.752667,-0.658402,-0.707107,-0.707107,1.308333
2,2,2022-02-01 20:55:00,0.015100,0.165100,0.131400,0.033200,0.053800,0.056300,0.095100,0.146200,...,1.620433,0.022706,-0.236779,-0.071156,32,0.523416,0.852078,-0.866025,0.500000,0.741937
3,3,2018-11-06 21:25:00,0.007100,0.026500,0.019000,0.019100,0.030400,0.022600,0.023400,0.014200,...,1.591540,-0.147167,-0.228278,-0.080904,310,-0.811539,0.584298,-0.707107,0.707107,1.481605
4,4,2018-11-06 19:20:00,0.001400,0.010400,0.010300,0.013300,0.020300,0.008900,0.006200,0.000000,...,1.526201,-0.390398,-0.208327,0.000000,310,-0.811539,0.584298,-0.965926,0.258819,1.193922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,2727,2019-08-20 16:00:00,0.160048,0.347841,0.301870,0.194634,0.206942,0.225023,0.253643,0.254485,...,1.063231,0.041857,-0.030649,-0.043629,232,-0.752667,-0.658402,-0.866025,-0.500000,1.536867
2728,2728,2021-08-17 15:45:00,0.106466,0.173790,0.156926,0.132880,0.156900,0.169819,0.182550,0.194755,...,1.180757,0.039542,-0.082891,0.040882,229,-0.717677,-0.696376,-0.707107,-0.707107,1.547563
2729,2729,2023-05-24 17:43:00,0.041518,0.115512,0.094602,0.046671,0.063934,0.065133,0.090442,0.112315,...,1.369847,0.009291,-0.156073,-0.035528,144,0.615285,-0.788305,-0.965926,-0.258819,1.410987
2730,2730,2018-06-19 19:24:00,0.051536,0.046751,0.038356,0.069572,0.074987,0.053739,0.051703,0.041847,...,1.077817,-0.165069,-0.037458,-0.020389,170,0.213521,-0.976938,-0.965926,0.258819,1.029619
2731,2731,2019-09-17 15:50:00,0.048440,0.116872,0.101207,0.040520,0.053809,0.062569,0.082519,0.073375,...,1.327936,0.075266,-0.140880,0.122702,260,-0.972118,-0.234491,-0.707107,-0.707107,1.280934

In [41]:
TARGET = "result_DOC_log" #FOR DOC
TARGET1 = "result_DOC"

input_features = ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 
                'B9',
               "B4_minus_B3",
               "B4_div_B3", 
               "ND_B4_B3", 
               'Temperature', 'DewPoint', 'v10n', 
               'doy_sin', 'doy_cos', 
               'latitude', 'longitude'
               ]

X_train = doc_train_augmented[input_features]
y_train = doc_train_augmented[TARGET]

X_test = doc_test[input_features]
y_test = doc_test[TARGET]

X_train.shape, y_train.shape, X_test.shape, y_test.shape

#y_test

((2732, 19), (2732,), (171, 19), (171,))

In [42]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

print(SVR.__module__)

sklearn.svm._classes

In [43]:
svr_base_WM = Pipeline([
    ("scaler", StandardScaler()),
    ("svr", SVR(
        kernel="rbf",
        ))
])

svr_base_WM.fit(X_train, y_train)
y_pred = svr_base_WM.predict(X_test)
print("R² for DOC for log scaled | Baseline SVM Regressor:", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | Baseline SVM Regressor:", r2_score(y_test_real, y_pred_orig))


# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)

print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC for log scaled | Baseline SVM Regressor: 0.43738098934622505
R² for DOC on normal scaled | Baseline SVM Regressor: 0.31449503704003734
R² for DOC on normal: 0.31449503704003734
Final metrics on NORMAL scale (after inverse log):
R²   : 0.3145
MSE  : 2.1377
RMSE : 1.4621
MAE  : 0.8924

In [ ]:
#Hyper Param tuning
from sklearn.model_selection import KFold
kf = KFold(n_splits=3, shuffle=True, random_state=42)

def objective_svr_WM(trial):

    params = {
        "C": trial.suggest_float("C", 1e-2, 1e3, log=True),
        "epsilon": trial.suggest_float("epsilon", 1e-3, 1.0, log=True),
        "gamma": trial.suggest_float("gamma", 1e-4, 1.0, log=True),
        "kernel": "rbf"
    }

    model = Pipeline([
        ("scaler", StandardScaler()),
        ("svr", SVR(**params))
    ])

    r2_scores = []

    for train_idx, val_idx in kf.split(X_train):
        X_tr, X_va = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_tr, y_va = y_train.iloc[train_idx], y_train.iloc[val_idx]

        model.fit(X_tr, y_tr)
        preds = model.predict(X_va)

        r2_scores.append(r2_score(y_va, preds))

    return np.mean(r2_scores)

In [18]:
import optuna

study_svr_WM = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42),
    study_name="SVR_withCV_WM"
)

study_svr_WM.optimize(objective_svr_WM, n_trials=50, show_progress_bar=True)

d:\Miniconda3\envs\PyTorchVirtualEnv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-02-09 10:40:53,164] A new study created in memory with name: SVR_withCV_WM
Best trial: 0. Best value: 0.183525:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-02-09 10:40:53,196] Trial 0 finished with value: 0.18352522453900852 and parameters: {'C': 0.7459343285726545, 'epsilon': 0.711447600934342, 'gamma': 0.08471801418819976}. Best is trial 0 with value: 0.18352522453900852.

Best trial: 2. Best value: 0.192438:   6%|▌         | 3/50 [00:00<00:09,  4.94it/s]

[I 2026-02-09 10:40:53,696] Trial 1 finished with value: 0.18258193677657708 and parameters: {'C': 9.846738873614559, 'epsilon': 0.0029380279387035343, 'gamma': 0.0004207053950287938}. Best is trial 0 with value: 0.18352522453900852.
[I 2026-02-09 10:40:53,811] Trial 2 finished with value: 0.19243842629458427 and parameters: {'C': 0.0195172246414495, 'epsilon': 0.39676050770529875, 'gamma': 0.02537815508265665}. Best is trial 2 with value: 0.19243842629458427.

Best trial: 3. Best value: 0.969651:   8%|▊         | 4/50 [00:01<00:19,  2.34it/s]

[I 2026-02-09 10:40:54,617] Trial 3 finished with value: 0.9696511791528426 and parameters: {'C': 34.70266988650411, 'epsilon': 0.00115279871282324, 'gamma': 0.7579479953348001}. Best is trial 3 with value: 0.9696511791528426.

Best trial: 3. Best value: 0.969651:  10%|█         | 5/50 [00:02<00:23,  1.93it/s]

[I 2026-02-09 10:40:55,306] Trial 4 finished with value: 0.3073562300291224 and parameters: {'C': 145.28246637516014, 'epsilon': 0.004335281794951566, 'gamma': 0.000533703276260396}. Best is trial 3 with value: 0.9696511791528426.

Best trial: 3. Best value: 0.969651:  12%|█▏        | 6/50 [00:02<00:22,  1.99it/s]

[I 2026-02-09 10:40:55,772] Trial 5 finished with value: 0.27223479742232626 and parameters: {'C': 0.08260808399079603, 'epsilon': 0.008179499475211672, 'gamma': 0.012561043700013555}. Best is trial 3 with value: 0.9696511791528426.

Best trial: 3. Best value: 0.969651:  14%|█▍        | 7/50 [00:03<00:22,  1.95it/s]

[I 2026-02-09 10:40:56,311] Trial 6 finished with value: 0.5326012395037404 and parameters: {'C': 1.4445251022763053, 'epsilon': 0.007476312062252299, 'gamma': 0.0280163515871626}. Best is trial 3 with value: 0.9696511791528426.

Best trial: 3. Best value: 0.969651:  16%|█▌        | 8/50 [00:03<00:21,  1.99it/s]

[I 2026-02-09 10:40:56,789] Trial 7 finished with value: 0.15765430311869133 and parameters: {'C': 0.04982752357076448, 'epsilon': 0.007523742884534853, 'gamma': 0.002920433847181412}. Best is trial 3 with value: 0.9696511791528426.

Best trial: 3. Best value: 0.969651:  18%|█▊        | 9/50 [00:03<00:17,  2.40it/s]

[I 2026-02-09 10:40:57,015] Trial 8 finished with value: 0.19915025762304597 and parameters: {'C': 1.9069966103000422, 'epsilon': 0.22673986523780384, 'gamma': 0.0006290644294586153}. Best is trial 3 with value: 0.9696511791528426.

Best trial: 3. Best value: 0.969651:  20%|██        | 10/50 [00:04<00:16,  2.42it/s]

[I 2026-02-09 10:40:57,421] Trial 9 finished with value: 0.16069057904078765 and parameters: {'C': 3.725393839578884, 'epsilon': 0.05987474910461398, 'gamma': 0.00015339162591163628}. Best is trial 3 with value: 0.9696511791528426.

Best trial: 3. Best value: 0.969651:  22%|██▏       | 11/50 [00:05<00:24,  1.59it/s]

[I 2026-02-09 10:40:58,540] Trial 10 finished with value: 0.9650909095984317 and parameters: {'C': 691.3375551009095, 'epsilon': 0.0010422971466648478, 'gamma': 0.7553503645583177}. Best is trial 3 with value: 0.9696511791528426.

Best trial: 3. Best value: 0.969651:  24%|██▍       | 12/50 [00:06<00:30,  1.23it/s]

[I 2026-02-09 10:40:59,771] Trial 11 finished with value: 0.9681401094821999 and parameters: {'C': 470.2366346292893, 'epsilon': 0.001105481056112165, 'gamma': 0.427227481622679}. Best is trial 3 with value: 0.9696511791528426.

Best trial: 3. Best value: 0.969651:  26%|██▌       | 13/50 [00:07<00:30,  1.20it/s]

[I 2026-02-09 10:41:00,651] Trial 12 finished with value: 0.9677310293040312 and parameters: {'C': 48.43892854257535, 'epsilon': 0.001078051418928534, 'gamma': 0.853405068076548}. Best is trial 3 with value: 0.9696511791528426.

Best trial: 13. Best value: 0.969781:  28%|██▊       | 14/50 [00:08<00:27,  1.33it/s]

[I 2026-02-09 10:41:01,213] Trial 13 finished with value: 0.9697805727175908 and parameters: {'C': 968.8484835500608, 'epsilon': 0.031418495581072174, 'gamma': 0.2002929230542149}. Best is trial 13 with value: 0.9697805727175908.

Best trial: 14. Best value: 0.970385:  30%|███       | 15/50 [00:08<00:24,  1.43it/s]

[I 2026-02-09 10:41:01,791] Trial 14 finished with value: 0.9703848184418887 and parameters: {'C': 45.4852979130446, 'epsilon': 0.03709371775969319, 'gamma': 0.16137610321187154}. Best is trial 14 with value: 0.9703848184418887.

Best trial: 14. Best value: 0.970385:  32%|███▏      | 16/50 [00:09<00:22,  1.49it/s]

[I 2026-02-09 10:41:02,402] Trial 15 finished with value: 0.9699903211767298 and parameters: {'C': 124.02408934866023, 'epsilon': 0.03719102868521415, 'gamma': 0.15587924148585036}. Best is trial 14 with value: 0.9703848184418887.

Best trial: 14. Best value: 0.970385:  34%|███▍      | 17/50 [00:10<00:24,  1.37it/s]

[I 2026-02-09 10:41:03,272] Trial 16 finished with value: 0.9639869883743328 and parameters: {'C': 87.82968957862889, 'epsilon': 0.04529796795685656, 'gamma': 0.10512376090280004}. Best is trial 14 with value: 0.9703848184418887.

Best trial: 14. Best value: 0.970385:  36%|███▌      | 18/50 [00:10<00:22,  1.43it/s]

[I 2026-02-09 10:41:03,902] Trial 17 finished with value: 0.39679009011651906 and parameters: {'C': 21.0591858919841, 'epsilon': 0.019296655135662144, 'gamma': 0.003235766254967104}. Best is trial 14 with value: 0.9703848184418887.

Best trial: 14. Best value: 0.970385:  38%|███▊      | 19/50 [00:11<00:21,  1.44it/s]

[I 2026-02-09 10:41:04,580] Trial 18 finished with value: 0.9099037573126717 and parameters: {'C': 210.22030105642162, 'epsilon': 0.12133535745096309, 'gamma': 0.06562595522088804}. Best is trial 14 with value: 0.9703848184418887.

Best trial: 14. Best value: 0.970385:  40%|████      | 20/50 [00:11<00:17,  1.76it/s]

[I 2026-02-09 10:41:04,850] Trial 19 finished with value: 0.9387543680478766 and parameters: {'C': 8.45365197346876, 'epsilon': 0.08975267671618097, 'gamma': 0.22058139918881067}. Best is trial 14 with value: 0.9703848184418887.

Best trial: 14. Best value: 0.970385:  42%|████▏     | 21/50 [00:12<00:15,  1.86it/s]

[I 2026-02-09 10:41:05,317] Trial 20 finished with value: 0.2631951813889145 and parameters: {'C': 0.32515118601847093, 'epsilon': 0.019425186604667233, 'gamma': 0.005930819198949863}. Best is trial 14 with value: 0.9703848184418887.

Best trial: 21. Best value: 0.970918:  44%|████▍     | 22/50 [00:12<00:15,  1.76it/s]

[I 2026-02-09 10:41:05,959] Trial 21 finished with value: 0.9709176834578669 and parameters: {'C': 983.0460116365967, 'epsilon': 0.026221986637738285, 'gamma': 0.20125183485916662}. Best is trial 21 with value: 0.9709176834578669.

Best trial: 22. Best value: 0.973946:  46%|████▌     | 23/50 [00:13<00:15,  1.72it/s]

[I 2026-02-09 10:41:06,571] Trial 22 finished with value: 0.9739463535898955 and parameters: {'C': 268.21237458901834, 'epsilon': 0.02175083379268976, 'gamma': 0.22255684840422923}. Best is trial 22 with value: 0.9739463535898955.

Best trial: 22. Best value: 0.973946:  48%|████▊     | 24/50 [00:21<01:13,  2.82s/it]

[I 2026-02-09 10:41:14,604] Trial 23 finished with value: 0.9366778593532886 and parameters: {'C': 322.53747403455594, 'epsilon': 0.017387706430988113, 'gamma': 0.04026351853278355}. Best is trial 22 with value: 0.9739463535898955.

Best trial: 22. Best value: 0.973946:  50%|█████     | 25/50 [00:21<00:50,  2.04s/it]

[I 2026-02-09 10:41:14,825] Trial 24 finished with value: 0.8932701243575929 and parameters: {'C': 297.0097765373707, 'epsilon': 0.1285680729083918, 'gamma': 0.4340591125092221}. Best is trial 22 with value: 0.9739463535898955.

Best trial: 25. Best value: 0.974212:  52%|█████▏    | 26/50 [00:22<00:38,  1.61s/it]

[I 2026-02-09 10:41:15,440] Trial 25 finished with value: 0.9742117621442908 and parameters: {'C': 61.818446220784054, 'epsilon': 0.023815095815874293, 'gamma': 0.20684554067405747}. Best is trial 25 with value: 0.9742117621442908.

Best trial: 25. Best value: 0.974212:  54%|█████▍    | 27/50 [00:22<00:30,  1.33s/it]

[I 2026-02-09 10:41:16,111] Trial 26 finished with value: 0.9697584804900238 and parameters: {'C': 777.1420161000641, 'epsilon': 0.012137060057549134, 'gamma': 0.37591863178273827}. Best is trial 25 with value: 0.9742117621442908.

Best trial: 25. Best value: 0.974212:  56%|█████▌    | 28/50 [00:23<00:25,  1.16s/it]

[I 2026-02-09 10:41:16,886] Trial 27 finished with value: 0.8712944966281962 and parameters: {'C': 15.257795419785152, 'epsilon': 0.0630074894582482, 'gamma': 0.057418952761444125}. Best is trial 25 with value: 0.9742117621442908.

Best trial: 25. Best value: 0.974212:  58%|█████▊    | 29/50 [00:25<00:30,  1.45s/it]

[I 2026-02-09 10:41:19,013] Trial 28 finished with value: 0.6240073307403861 and parameters: {'C': 86.01830116872463, 'epsilon': 0.0032851232917643003, 'gamma': 0.010792325879572993}. Best is trial 25 with value: 0.9742117621442908.

Best trial: 25. Best value: 0.974212:  60%|██████    | 30/50 [00:35<01:19,  3.98s/it]

[I 2026-02-09 10:41:28,881] Trial 29 finished with value: 0.9697258529828009 and parameters: {'C': 233.7942387535465, 'epsilon': 0.02403398167922826, 'gamma': 0.10023090624072645}. Best is trial 25 with value: 0.9742117621442908.

Best trial: 25. Best value: 0.974212:  62%|██████▏   | 31/50 [00:35<00:54,  2.85s/it]

[I 2026-02-09 10:41:29,094] Trial 30 finished with value: 0.16038246094159417 and parameters: {'C': 0.35764083361146487, 'epsilon': 0.675624432882769, 'gamma': 0.31303188113989217}. Best is trial 25 with value: 0.9742117621442908.

Best trial: 25. Best value: 0.974212:  64%|██████▍   | 32/50 [00:39<00:56,  3.16s/it]

[I 2026-02-09 10:41:32,994] Trial 31 finished with value: 0.9736332026018374 and parameters: {'C': 48.00401995805742, 'epsilon': 0.011384823139907746, 'gamma': 0.1321212355533838}. Best is trial 25 with value: 0.9742117621442908.

Best trial: 25. Best value: 0.974212:  66%|██████▌   | 33/50 [00:43<00:54,  3.19s/it]

[I 2026-02-09 10:41:36,249] Trial 32 finished with value: 0.9704572435020603 and parameters: {'C': 84.91904163709856, 'epsilon': 0.013112194189364799, 'gamma': 0.09800864218823496}. Best is trial 25 with value: 0.9742117621442908.

Best trial: 25. Best value: 0.974212:  68%|██████▊   | 34/50 [00:43<00:39,  2.46s/it]

[I 2026-02-09 10:41:37,008] Trial 33 finished with value: 0.6026571563956136 and parameters: {'C': 6.775418051948902, 'epsilon': 0.005360637386873247, 'gamma': 0.022811287575472034}. Best is trial 25 with value: 0.9742117621442908.

Best trial: 25. Best value: 0.974212:  70%|███████   | 35/50 [00:55<01:16,  5.13s/it]

[I 2026-02-09 10:41:48,359] Trial 34 finished with value: 0.9490679397798366 and parameters: {'C': 426.8425922584745, 'epsilon': 0.012079183837872699, 'gamma': 0.04649588941885596}. Best is trial 25 with value: 0.9742117621442908.

Best trial: 25. Best value: 0.974212:  72%|███████▏  | 36/50 [00:55<00:53,  3.82s/it]

[I 2026-02-09 10:41:49,114] Trial 35 finished with value: 0.9730806320837081 and parameters: {'C': 25.262077483893478, 'epsilon': 0.002261060637863493, 'gamma': 0.5295568970870198}. Best is trial 25 with value: 0.9742117621442908.

Best trial: 25. Best value: 0.974212:  74%|███████▍  | 37/50 [00:56<00:37,  2.89s/it]

[I 2026-02-09 10:41:49,852] Trial 36 finished with value: 0.9711451211003057 and parameters: {'C': 22.951369358692002, 'epsilon': 0.0018643272986890009, 'gamma': 0.6657866287376077}. Best is trial 25 with value: 0.9742117621442908.

Best trial: 37. Best value: 0.975386:  76%|███████▌  | 38/50 [00:57<00:28,  2.39s/it]

[I 2026-02-09 10:41:51,062] Trial 37 finished with value: 0.9753864012748843 and parameters: {'C': 54.826395525776185, 'epsilon': 0.0025897520857723773, 'gamma': 0.29444825880125647}. Best is trial 37 with value: 0.9753864012748843.

Best trial: 38. Best value: 0.975919:  78%|███████▊  | 39/50 [00:58<00:21,  1.94s/it]

[I 2026-02-09 10:41:51,970] Trial 38 finished with value: 0.9759190794640077 and parameters: {'C': 43.1558571666661, 'epsilon': 0.004752680680615191, 'gamma': 0.3096522957081244}. Best is trial 38 with value: 0.9759190794640077.

Best trial: 38. Best value: 0.975919:  80%|████████  | 40/50 [00:59<00:15,  1.58s/it]

[I 2026-02-09 10:41:52,688] Trial 39 finished with value: 0.9755992903790552 and parameters: {'C': 4.740466122188947, 'epsilon': 0.004827626249316009, 'gamma': 0.297103670332991}. Best is trial 38 with value: 0.9759190794640077.

Best trial: 38. Best value: 0.975919:  82%|████████▏ | 41/50 [01:00<00:11,  1.28s/it]

[I 2026-02-09 10:41:53,289] Trial 40 finished with value: 0.9669993671095263 and parameters: {'C': 13.570237783721618, 'epsilon': 0.005250837788612228, 'gamma': 0.9658318826868283}. Best is trial 38 with value: 0.9759190794640077.

Best trial: 38. Best value: 0.975919:  84%|████████▍ | 42/50 [01:01<00:09,  1.18s/it]

[I 2026-02-09 10:41:54,238] Trial 41 finished with value: 0.9756571466105916 and parameters: {'C': 6.66272690638426, 'epsilon': 0.002086713489290361, 'gamma': 0.2991872325618561}. Best is trial 38 with value: 0.9759190794640077.

Best trial: 38. Best value: 0.975919:  86%|████████▌ | 43/50 [01:01<00:07,  1.09s/it]

[I 2026-02-09 10:41:55,125] Trial 42 finished with value: 0.9748199753670597 and parameters: {'C': 4.280384813388145, 'epsilon': 0.001717788084031656, 'gamma': 0.3060725345526218}. Best is trial 38 with value: 0.9759190794640077.

Best trial: 38. Best value: 0.975919:  88%|████████▊ | 44/50 [01:02<00:06,  1.03s/it]

[I 2026-02-09 10:41:56,000] Trial 43 finished with value: 0.9751639963706523 and parameters: {'C': 4.576640013232386, 'epsilon': 0.0017674928976045988, 'gamma': 0.3261701093509469}. Best is trial 38 with value: 0.9759190794640077.

Best trial: 38. Best value: 0.975919:  90%|█████████ | 45/50 [01:03<00:04,  1.16it/s]

[I 2026-02-09 10:41:56,484] Trial 44 finished with value: 0.19649920491360603 and parameters: {'C': 1.6204101315038695, 'epsilon': 0.003077652187683796, 'gamma': 0.0011639010490358337}. Best is trial 38 with value: 0.9759190794640077.

Best trial: 38. Best value: 0.975919:  92%|█████████▏| 46/50 [01:03<00:03,  1.29it/s]

[I 2026-02-09 10:41:57,054] Trial 45 finished with value: 0.9723341585183501 and parameters: {'C': 2.3293852901466954, 'epsilon': 0.0042552952381568745, 'gamma': 0.5733484110735161}. Best is trial 38 with value: 0.9759190794640077.

Best trial: 38. Best value: 0.975919:  94%|█████████▍| 47/50 [01:04<00:02,  1.33it/s]

[I 2026-02-09 10:41:57,751] Trial 46 finished with value: 0.9645955249733499 and parameters: {'C': 0.9741034993904807, 'epsilon': 0.0014791803378808133, 'gamma': 0.9931213101841436}. Best is trial 38 with value: 0.9759190794640077.

Best trial: 38. Best value: 0.975919:  96%|█████████▌| 48/50 [01:05<00:01,  1.27it/s]

[I 2026-02-09 10:41:58,620] Trial 47 finished with value: 0.9754425231327474 and parameters: {'C': 5.1310600800916495, 'epsilon': 0.002481462266956343, 'gamma': 0.29605600958122313}. Best is trial 38 with value: 0.9759190794640077.

Best trial: 38. Best value: 0.975919:  98%|█████████▊| 49/50 [01:05<00:00,  1.43it/s]

[I 2026-02-09 10:41:59,115] Trial 48 finished with value: 0.13333285940637765 and parameters: {'C': 0.652617179551054, 'epsilon': 0.002514206766717188, 'gamma': 0.00019167808303473415}. Best is trial 38 with value: 0.9759190794640077.

Best trial: 38. Best value: 0.975919: 100%|██████████| 50/50 [01:06<00:00,  1.34s/it]

[I 2026-02-09 10:41:59,925] Trial 49 finished with value: 0.6295635295897036 and parameters: {'C': 7.071757800029679, 'epsilon': 0.004088948130935703, 'gamma': 0.025921297892045603}. Best is trial 38 with value: 0.9759190794640077.

In [44]:
print(study_svr_WM.best_params)
print(study_svr_WM.best_value)

{'C': 43.1558571666661, 'epsilon': 0.004752680680615191, 'gamma': 0.3096522957081244}
0.9759190794640077

In [45]:
best_params_WM = study_svr_WM.best_params
print(best_params_WM)

{'C': 43.1558571666661, 'epsilon': 0.004752680680615191, 'gamma': 0.3096522957081244}

In [46]:
best_params = best_params_WM

best_svr_WM = Pipeline([
    ("scaler", StandardScaler()),
    ("svr", SVR(**best_params, kernel="rbf"))
])


best_svr_WM.fit(X_train, y_train)
y_pred = best_svr_WM.predict(X_test)

print("R² for DOC for log scaled | SVR:", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | SVR:", r2_score(y_test_real, y_pred_orig))




# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC for log scaled | SVR: 0.381441609612687
R² for DOC on normal scaled | SVR: 0.3165146824425564
R² for DOC on normal: 0.3165146824425564
Final metrics on NORMAL scale (after inverse log):
R²   : 0.3165
MSE  : 2.1314
RMSE : 1.4599
MAE  : 0.9570

In [ ]:
#For without meteo

In [47]:
#FOR AUGMENTED_NEW

import pandas as pd
import numpy as np

aug_factor = 3 #augmented has been done initially for aug_factor = 2, then for aug_factor = 3

doc_train_augmented = pd.read_csv (f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TRAIN_AUG{aug_factor}.csv")
doc_test = pd.read_csv(f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TEST_AUG{aug_factor}.csv")

doc_train_augmented.shape, doc_test.shape

((2732, 55), (171, 55))

In [48]:
doc_train_augmented ['result_DOC_log'] = np.log1p (doc_train_augmented ['result_DOC'])
doc_test ['result_DOC_log'] = np.log1p (doc_test ['result_DOC'])
doc_train_augmented

,Unnamed: 0,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,...,B3_div_B2,ND_B4_B3,ND_B2_B3,ND_B6_B8,day_of_year,doy_sin,doy_cos,hour_sin,hour_cos,result_DOC_log
0,0,2024-05-08 14:00:00,0.037800,0.168600,0.105100,0.040100,0.063600,0.050700,0.094400,0.220200,...,1.585995,-0.112860,-0.226613,-0.130503,129,0.796183,-0.605056,-0.500000,-0.866025,0.741937
1,1,2019-08-20 15:00:00,0.068100,0.144400,0.130300,0.057300,0.075900,0.073100,0.098200,0.105800,...,1.324584,-0.018792,-0.139639,0.109596,232,-0.752667,-0.658402,-0.707107,-0.707107,1.308333
2,2,2022-02-01 20:55:00,0.015100,0.165100,0.131400,0.033200,0.053800,0.056300,0.095100,0.146200,...,1.620433,0.022706,-0.236779,-0.071156,32,0.523416,0.852078,-0.866025,0.500000,0.741937
3,3,2018-11-06 21:25:00,0.007100,0.026500,0.019000,0.019100,0.030400,0.022600,0.023400,0.014200,...,1.591540,-0.147167,-0.228278,-0.080904,310,-0.811539,0.584298,-0.707107,0.707107,1.481605
4,4,2018-11-06 19:20:00,0.001400,0.010400,0.010300,0.013300,0.020300,0.008900,0.006200,0.000000,...,1.526201,-0.390398,-0.208327,0.000000,310,-0.811539,0.584298,-0.965926,0.258819,1.193922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,2727,2019-08-20 16:00:00,0.160048,0.347841,0.301870,0.194634,0.206942,0.225023,0.253643,0.254485,...,1.063231,0.041857,-0.030649,-0.043629,232,-0.752667,-0.658402,-0.866025,-0.500000,1.536867
2728,2728,2021-08-17 15:45:00,0.106466,0.173790,0.156926,0.132880,0.156900,0.169819,0.182550,0.194755,...,1.180757,0.039542,-0.082891,0.040882,229,-0.717677,-0.696376,-0.707107,-0.707107,1.547563
2729,2729,2023-05-24 17:43:00,0.041518,0.115512,0.094602,0.046671,0.063934,0.065133,0.090442,0.112315,...,1.369847,0.009291,-0.156073,-0.035528,144,0.615285,-0.788305,-0.965926,-0.258819,1.410987
2730,2730,2018-06-19 19:24:00,0.051536,0.046751,0.038356,0.069572,0.074987,0.053739,0.051703,0.041847,...,1.077817,-0.165069,-0.037458,-0.020389,170,0.213521,-0.976938,-0.965926,0.258819,1.029619
2731,2731,2019-09-17 15:50:00,0.048440,0.116872,0.101207,0.040520,0.053809,0.062569,0.082519,0.073375,...,1.327936,0.075266,-0.140880,0.122702,260,-0.972118,-0.234491,-0.707107,-0.707107,1.280934

In [49]:
TARGET = "result_DOC_log" #FOR DOC
TARGET1 = "result_DOC"

input_features_noMeteo = ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 
                'B9',
               "B4_minus_B3",
               "B4_div_B3", 
               "ND_B4_B3", 
               
               #'Temperature', 'DewPoint', 'v10n', #'Precipitation(mm)',
               'doy_sin', 'doy_cos', 
               'latitude', 'longitude'
               ]

X_train = doc_train_augmented[input_features_noMeteo]
y_train = doc_train_augmented[TARGET]

X_test = doc_test[input_features_noMeteo]
y_test = doc_test[TARGET]

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2732, 16), (2732,), (171, 16), (171,))

In [50]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

print(SVR.__module__)

sklearn.svm._classes

In [51]:
svr_base_NM = Pipeline([
    ("scaler", StandardScaler()),
    ("svr", SVR(
        kernel="rbf",
        ))
])

svr_base_NM.fit(X_train, y_train)
y_pred = svr_base_NM.predict(X_test)
print("R² for DOC for log scaled | Baseline SVM Regressor:", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | Baseline SVM Regressor:", r2_score(y_test_real, y_pred_orig))


# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)

print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC for log scaled | Baseline SVM Regressor: 0.4635169797119849
R² for DOC on normal scaled | Baseline SVM Regressor: 0.34808861958344806
R² for DOC on normal: 0.34808861958344806
Final metrics on NORMAL scale (after inverse log):
R²   : 0.3481
MSE  : 2.0330
RMSE : 1.4258
MAE  : 0.8240

In [32]:
#Hyper Param tuning
from sklearn.model_selection import KFold
kf = KFold(n_splits=3, shuffle=True, random_state=42)

def objective_svr_NM(trial):

    params = {
        "C": trial.suggest_float("C", 1e-2, 1e3, log=True),
        "epsilon": trial.suggest_float("epsilon", 1e-3, 1.0, log=True),
        "gamma": trial.suggest_float("gamma", 1e-4, 1.0, log=True),
        "kernel": "rbf"
    }

    model = Pipeline([
        ("scaler", StandardScaler()),
        ("svr", SVR(**params))
    ])

    r2_scores = []

    for train_idx, val_idx in kf.split(X_train):
        X_tr, X_va = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_tr, y_va = y_train.iloc[train_idx], y_train.iloc[val_idx]

        model.fit(X_tr, y_tr)
        preds = model.predict(X_va)

        r2_scores.append(r2_score(y_va, preds))

    return np.mean(r2_scores)

In [33]:
import optuna

study_svr_NM = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42),
    study_name="SVR_withCV_WM"
)

study_svr_NM.optimize(objective_svr_NM, n_trials=50, show_progress_bar=True)

[I 2026-02-09 10:50:08,773] A new study created in memory with name: SVR_withCV_WM
Best trial: 0. Best value: 0.198228:   0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-02-09 10:50:08,805] Trial 0 finished with value: 0.19822753997936196 and parameters: {'C': 0.7459343285726545, 'epsilon': 0.711447600934342, 'gamma': 0.08471801418819976}. Best is trial 0 with value: 0.19822753997936196.

Best trial: 0. Best value: 0.198228:   6%|▌         | 3/50 [00:00<00:09,  5.01it/s]

[I 2026-02-09 10:50:09,291] Trial 1 finished with value: 0.17975294733073977 and parameters: {'C': 9.846738873614559, 'epsilon': 0.0029380279387035343, 'gamma': 0.0004207053950287938}. Best is trial 0 with value: 0.19822753997936196.
[I 2026-02-09 10:50:09,407] Trial 2 finished with value: 0.19417634995401736 and parameters: {'C': 0.0195172246414495, 'epsilon': 0.39676050770529875, 'gamma': 0.02537815508265665}. Best is trial 0 with value: 0.19822753997936196.

Best trial: 3. Best value: 0.965508:   8%|▊         | 4/50 [00:02<00:32,  1.40it/s]

[I 2026-02-09 10:50:10,986] Trial 3 finished with value: 0.9655082418965332 and parameters: {'C': 34.70266988650411, 'epsilon': 0.00115279871282324, 'gamma': 0.7579479953348001}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  10%|█         | 5/50 [00:02<00:30,  1.45it/s]

[I 2026-02-09 10:50:11,626] Trial 4 finished with value: 0.2802279522000631 and parameters: {'C': 145.28246637516014, 'epsilon': 0.004335281794951566, 'gamma': 0.000533703276260396}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  12%|█▏        | 6/50 [00:03<00:26,  1.63it/s]

[I 2026-02-09 10:50:12,085] Trial 5 finished with value: 0.2561655677179549 and parameters: {'C': 0.08260808399079603, 'epsilon': 0.008179499475211672, 'gamma': 0.012561043700013555}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  14%|█▍        | 7/50 [00:03<00:25,  1.70it/s]

[I 2026-02-09 10:50:12,619] Trial 6 finished with value: 0.45130200747624305 and parameters: {'C': 1.4445251022763053, 'epsilon': 0.007476312062252299, 'gamma': 0.0280163515871626}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  16%|█▌        | 8/50 [00:04<00:22,  1.83it/s]

[I 2026-02-09 10:50:13,079] Trial 7 finished with value: 0.15782280042422006 and parameters: {'C': 0.04982752357076448, 'epsilon': 0.007523742884534853, 'gamma': 0.002920433847181412}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  18%|█▊        | 9/50 [00:04<00:18,  2.26it/s]

[I 2026-02-09 10:50:13,289] Trial 8 finished with value: 0.19168817173699595 and parameters: {'C': 1.9069966103000422, 'epsilon': 0.22673986523780384, 'gamma': 0.0006290644294586153}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  20%|██        | 10/50 [00:04<00:17,  2.35it/s]

[I 2026-02-09 10:50:13,677] Trial 9 finished with value: 0.1623408922175615 and parameters: {'C': 3.725393839578884, 'epsilon': 0.05987474910461398, 'gamma': 0.00015339162591163628}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  22%|██▏       | 11/50 [00:07<00:37,  1.04it/s]

[I 2026-02-09 10:50:15,870] Trial 10 finished with value: 0.9623433634245483 and parameters: {'C': 691.3375551009095, 'epsilon': 0.0010422971466648478, 'gamma': 0.7553503645583177}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  24%|██▍       | 12/50 [00:11<01:17,  2.05s/it]

[I 2026-02-09 10:50:20,400] Trial 11 finished with value: 0.962373270954752 and parameters: {'C': 470.2366346292893, 'epsilon': 0.001105481056112165, 'gamma': 0.427227481622679}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  26%|██▌       | 13/50 [00:13<01:10,  1.91s/it]

[I 2026-02-09 10:50:21,985] Trial 12 finished with value: 0.96496722183413 and parameters: {'C': 48.43892854257535, 'epsilon': 0.001078051418928534, 'gamma': 0.853405068076548}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  28%|██▊       | 14/50 [00:14<01:06,  1.84s/it]

[I 2026-02-09 10:50:23,665] Trial 13 finished with value: 0.9129966365681451 and parameters: {'C': 38.246358342016684, 'epsilon': 0.0308956477810443, 'gamma': 0.13239858119957226}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  30%|███       | 15/50 [00:17<01:11,  2.04s/it]

[I 2026-02-09 10:50:26,183] Trial 14 finished with value: 0.9555528304481599 and parameters: {'C': 29.26139975269567, 'epsilon': 0.0021660903220607364, 'gamma': 0.2664464860984181}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  32%|███▏      | 16/50 [00:17<00:53,  1.58s/it]

[I 2026-02-09 10:50:26,673] Trial 15 finished with value: 0.9590494161002905 and parameters: {'C': 85.18710399776029, 'epsilon': 0.022831201329300246, 'gamma': 0.9905092592709058}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  34%|███▍      | 17/50 [00:18<00:42,  1.27s/it]

[I 2026-02-09 10:50:27,248] Trial 16 finished with value: 0.8229582578745426 and parameters: {'C': 10.178975488112311, 'epsilon': 0.08661025596666062, 'gamma': 0.113450591484286}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  36%|███▌      | 18/50 [00:18<00:32,  1.03s/it]

[I 2026-02-09 10:50:27,696] Trial 17 finished with value: 0.21731737047540658 and parameters: {'C': 0.40628977062674637, 'epsilon': 0.015233124806274636, 'gamma': 0.003235766254967104}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  38%|███▊      | 19/50 [00:25<01:24,  2.73s/it]

[I 2026-02-09 10:50:34,386] Trial 18 finished with value: 0.9550593743296463 and parameters: {'C': 210.22030105642162, 'epsilon': 0.002156642023063554, 'gamma': 0.2540531102691874}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  40%|████      | 20/50 [00:26<01:07,  2.27s/it]

[I 2026-02-09 10:50:35,575] Trial 19 finished with value: 0.6647653470259495 and parameters: {'C': 16.748375144726552, 'epsilon': 0.0013413535349979053, 'gamma': 0.04850614668462456}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  42%|████▏     | 21/50 [00:29<01:08,  2.35s/it]

[I 2026-02-09 10:50:38,125] Trial 20 finished with value: 0.9620619153020248 and parameters: {'C': 80.69098060632436, 'epsilon': 0.0045659116518418415, 'gamma': 0.35605902811440426}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  44%|████▍     | 22/50 [00:32<01:10,  2.51s/it]

[I 2026-02-09 10:50:41,005] Trial 21 finished with value: 0.963398956478064 and parameters: {'C': 919.0059246455335, 'epsilon': 0.0011598819286528963, 'gamma': 0.5805081705471652}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  46%|████▌     | 23/50 [00:33<01:00,  2.25s/it]

[I 2026-02-09 10:50:42,654] Trial 22 finished with value: 0.9544003312318657 and parameters: {'C': 858.5441180702796, 'epsilon': 0.001949971426367503, 'gamma': 0.9627809900329727}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  48%|████▊     | 24/50 [00:42<01:48,  4.19s/it]

[I 2026-02-09 10:50:51,359] Trial 23 finished with value: 0.9486330016451904 and parameters: {'C': 275.1414761836939, 'epsilon': 0.0037764143197852344, 'gamma': 0.19449297954383907}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  50%|█████     | 25/50 [00:43<01:22,  3.28s/it]

[I 2026-02-09 10:50:52,528] Trial 24 finished with value: 0.9629439470760716 and parameters: {'C': 6.2229013347032325, 'epsilon': 0.0014669942180154454, 'gamma': 0.46986080353457493}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  52%|█████▏    | 26/50 [00:45<01:09,  2.90s/it]

[I 2026-02-09 10:50:54,548] Trial 25 finished with value: 0.7827605226511632 and parameters: {'C': 40.64236814855052, 'epsilon': 0.01036899711602347, 'gamma': 0.06411537115031743}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  54%|█████▍    | 27/50 [00:47<00:59,  2.58s/it]

[I 2026-02-09 10:50:56,390] Trial 26 finished with value: 0.965494590519703 and parameters: {'C': 89.73768587982232, 'epsilon': 0.003162955448132076, 'gamma': 0.5387966257838959}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  56%|█████▌    | 28/50 [00:52<01:15,  3.41s/it]

[I 2026-02-09 10:51:01,739] Trial 27 finished with value: 0.9422910047346109 and parameters: {'C': 90.71860318456913, 'epsilon': 0.0026592105491091284, 'gamma': 0.16114178555514222}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  58%|█████▊    | 29/50 [00:53<00:54,  2.60s/it]

[I 2026-02-09 10:51:02,454] Trial 28 finished with value: 0.4159013655542334 and parameters: {'C': 25.919709958065187, 'epsilon': 0.005083246740677516, 'gamma': 0.00689739546210353}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  60%|██████    | 30/50 [00:54<00:38,  1.93s/it]

[I 2026-02-09 10:51:02,803] Trial 29 finished with value: 0.5219319445418245 and parameters: {'C': 0.30285649243951024, 'epsilon': 0.07726556738189391, 'gamma': 0.089955239417017}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  62%|██████▏   | 31/50 [00:55<00:31,  1.65s/it]

[I 2026-02-09 10:51:03,815] Trial 30 finished with value: 0.961800829891736 and parameters: {'C': 301.66952328811846, 'epsilon': 0.014665861669762486, 'gamma': 0.45463325341491034}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  64%|██████▍   | 32/50 [00:57<00:33,  1.86s/it]

[I 2026-02-09 10:51:06,171] Trial 31 finished with value: 0.9652800217235811 and parameters: {'C': 62.32110591312569, 'epsilon': 0.0010134256570315545, 'gamma': 0.5336632301652452}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  66%|██████▌   | 33/50 [00:58<00:29,  1.71s/it]

[I 2026-02-09 10:51:07,511] Trial 32 finished with value: 0.9638225972828298 and parameters: {'C': 66.15421591034878, 'epsilon': 0.0018477085200353032, 'gamma': 0.9923184159105707}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  68%|██████▊   | 34/50 [01:00<00:26,  1.67s/it]

[I 2026-02-09 10:51:09,086] Trial 33 finished with value: 0.9517287526759487 and parameters: {'C': 13.71194722561856, 'epsilon': 0.0030662718730674102, 'gamma': 0.2728357117299767}. Best is trial 3 with value: 0.9655082418965332.
[I 2026-02-09 10:51:09,116] Trial 34 finished with value: 0.0910684254437129 and parameters: {'C': 5.72337859350116, 'epsilon': 0.7864978751369727, 'gamma': 0.5646403993316382}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  72%|███████▏  | 36/50 [01:06<00:32,  2.34s/it]

[I 2026-02-09 10:51:15,330] Trial 35 finished with value: 0.7919234288487439 and parameters: {'C': 173.7307219984111, 'epsilon': 0.001540866006529841, 'gamma': 0.047661617291294055}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  74%|███████▍  | 37/50 [01:08<00:28,  2.22s/it]

[I 2026-02-09 10:51:17,187] Trial 36 finished with value: 0.9405100516987687 and parameters: {'C': 18.5105652754847, 'epsilon': 0.003475664113070134, 'gamma': 0.21152859607159624}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  76%|███████▌  | 38/50 [01:10<00:25,  2.13s/it]

[I 2026-02-09 10:51:19,081] Trial 37 finished with value: 0.6328071571012626 and parameters: {'C': 52.09962209129202, 'epsilon': 0.001016596025082786, 'gamma': 0.029278174077007914}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  78%|███████▊  | 39/50 [01:13<00:27,  2.50s/it]

[I 2026-02-09 10:51:22,556] Trial 38 finished with value: 0.9617813916989842 and parameters: {'C': 148.4288949252275, 'epsilon': 0.002604677462397512, 'gamma': 0.3751154672660929}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  80%|████████  | 40/50 [01:14<00:19,  1.93s/it]

[I 2026-02-09 10:51:23,027] Trial 39 finished with value: 0.19131124562762677 and parameters: {'C': 1.5523191113767187, 'epsilon': 0.00613505103986229, 'gamma': 0.0010772329494267326}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  82%|████████▏ | 41/50 [01:14<00:12,  1.43s/it]

[I 2026-02-09 10:51:23,217] Trial 40 finished with value: 0.8399408355620027 and parameters: {'C': 123.21401965320658, 'epsilon': 0.17265829281902684, 'gamma': 0.6878967659410089}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  84%|████████▍ | 42/50 [01:15<00:11,  1.41s/it]

[I 2026-02-09 10:51:24,562] Trial 41 finished with value: 0.9643326126462969 and parameters: {'C': 56.48954422911744, 'epsilon': 0.0018309269497440654, 'gamma': 0.9395121331061773}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  86%|████████▌ | 43/50 [01:18<00:11,  1.64s/it]

[I 2026-02-09 10:51:26,778] Trial 42 finished with value: 0.9649256759153136 and parameters: {'C': 358.1193497557859, 'epsilon': 0.0016684146822832225, 'gamma': 0.619280642384819}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  88%|████████▊ | 44/50 [01:36<00:39,  6.56s/it]

[I 2026-02-09 10:51:45,091] Trial 43 finished with value: 0.9389995310870048 and parameters: {'C': 488.1384018245723, 'epsilon': 0.001699348170177859, 'gamma': 0.148586447058104}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 3. Best value: 0.965508:  90%|█████████ | 45/50 [01:43<00:33,  6.66s/it]

[I 2026-02-09 10:51:51,999] Trial 44 finished with value: 0.9584634500983787 and parameters: {'C': 391.077903394452, 'epsilon': 0.00100423533427071, 'gamma': 0.3349108511189022}. Best is trial 3 with value: 0.9655082418965332.

Best trial: 45. Best value: 0.965789:  92%|█████████▏| 46/50 [01:44<00:20,  5.08s/it]

[I 2026-02-09 10:51:53,331] Trial 45 finished with value: 0.9657888200081398 and parameters: {'C': 25.581263740035503, 'epsilon': 0.002592363878590811, 'gamma': 0.6898899913178642}. Best is trial 45 with value: 0.9657888200081398.

Best trial: 45. Best value: 0.965789:  94%|█████████▍| 47/50 [01:45<00:11,  3.81s/it]

[I 2026-02-09 10:51:54,168] Trial 46 finished with value: 0.4764824448329601 and parameters: {'C': 24.929074358345968, 'epsilon': 0.0025601546674484115, 'gamma': 0.011656244505437714}. Best is trial 45 with value: 0.9657888200081398.

Best trial: 45. Best value: 0.965789:  96%|█████████▌| 48/50 [01:46<00:05,  2.87s/it]

[I 2026-02-09 10:51:54,816] Trial 47 finished with value: 0.9639587285949878 and parameters: {'C': 3.104558008146649, 'epsilon': 0.00859464620848121, 'gamma': 0.6504646161935417}. Best is trial 45 with value: 0.9657888200081398.

Best trial: 45. Best value: 0.965789: 100%|██████████| 50/50 [01:46<00:00,  2.13s/it]

[I 2026-02-09 10:51:55,290] Trial 48 finished with value: 0.16667188915910988 and parameters: {'C': 8.442626019932026, 'epsilon': 0.0055557620637177695, 'gamma': 0.00019167808303473415}. Best is trial 45 with value: 0.9657888200081398.
[I 2026-02-09 10:51:55,380] Trial 49 finished with value: 0.4560334437549198 and parameters: {'C': 27.801964268371755, 'epsilon': 0.466304126169473, 'gamma': 0.10868303341793496}. Best is trial 45 with value: 0.9657888200081398.

In [52]:
print(study_svr_NM.best_params)
print(study_svr_NM.best_value)

{'C': 25.581263740035503, 'epsilon': 0.002592363878590811, 'gamma': 0.6898899913178642}
0.9657888200081398

In [53]:
best_params_NM = study_svr_NM.best_params
print(best_params_NM)

{'C': 25.581263740035503, 'epsilon': 0.002592363878590811, 'gamma': 0.6898899913178642}

In [ ]:
best_params = best_params_NM

best_svr_NM = Pipeline([
    ("scaler", StandardScaler()),
    ("svr", SVR(**best_params, kernel="rbf"))
])


best_svr_NM.fit(X_train, y_train)
y_pred = best_svr_NM.predict(X_test)

print("R² for DOC for log scaled | SVR no Meteo:", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal scaled | SVR No meteo:", r2_score(y_test_real, y_pred_orig))



# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))


# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC for log scaled | SVR no Meteo: 0.41259190421362124
R² for DOC on normal scaled | SVR No meteo: 0.37804843050474335
R² for DOC on normal: 0.37804843050474335
Final metrics on NORMAL scale (after inverse log):
R²   : 0.3780
MSE  : 1.9395
RMSE : 1.3927
MAE  : 0.9363

In [ ]:
#Completed