In [ ]:
#FOR AUGMENTED_NEW

import pandas as pd
import numpy as np

aug_factor = 3 #augmented has been done initially for aug_factor = 2, then for aug_factor = 3

doc_train_augmented = pd.read_csv (f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TRAIN_AUG{aug_factor}.csv")
doc_test = pd.read_csv(f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TEST_AUG{aug_factor}.csv")

doc_train_augmented.shape, doc_test.shape

((2732, 55), (171, 55))

In [2]:
doc_train_augmented ['result_DOC_log'] = np.log1p (doc_train_augmented ['result_DOC'])
doc_test ['result_DOC_log'] = np.log1p (doc_test ['result_DOC'])
doc_train_augmented

,Unnamed: 0,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,...,B3_div_B2,ND_B4_B3,ND_B2_B3,ND_B6_B8,day_of_year,doy_sin,doy_cos,hour_sin,hour_cos,result_DOC_log
0,0,2024-05-08 14:00:00,0.037800,0.168600,0.105100,0.040100,0.063600,0.050700,0.094400,0.220200,...,1.585995,-0.112860,-0.226613,-0.130503,129,0.796183,-0.605056,-0.500000,-0.866025,0.741937
1,1,2019-08-20 15:00:00,0.068100,0.144400,0.130300,0.057300,0.075900,0.073100,0.098200,0.105800,...,1.324584,-0.018792,-0.139639,0.109596,232,-0.752667,-0.658402,-0.707107,-0.707107,1.308333
2,2,2022-02-01 20:55:00,0.015100,0.165100,0.131400,0.033200,0.053800,0.056300,0.095100,0.146200,...,1.620433,0.022706,-0.236779,-0.071156,32,0.523416,0.852078,-0.866025,0.500000,0.741937
3,3,2018-11-06 21:25:00,0.007100,0.026500,0.019000,0.019100,0.030400,0.022600,0.023400,0.014200,...,1.591540,-0.147167,-0.228278,-0.080904,310,-0.811539,0.584298,-0.707107,0.707107,1.481605
4,4,2018-11-06 19:20:00,0.001400,0.010400,0.010300,0.013300,0.020300,0.008900,0.006200,0.000000,...,1.526201,-0.390398,-0.208327,0.000000,310,-0.811539,0.584298,-0.965926,0.258819,1.193922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,2727,2019-08-20 16:00:00,0.160048,0.347841,0.301870,0.194634,0.206942,0.225023,0.253643,0.254485,...,1.063231,0.041857,-0.030649,-0.043629,232,-0.752667,-0.658402,-0.866025,-0.500000,1.536867
2728,2728,2021-08-17 15:45:00,0.106466,0.173790,0.156926,0.132880,0.156900,0.169819,0.182550,0.194755,...,1.180757,0.039542,-0.082891,0.040882,229,-0.717677,-0.696376,-0.707107,-0.707107,1.547563
2729,2729,2023-05-24 17:43:00,0.041518,0.115512,0.094602,0.046671,0.063934,0.065133,0.090442,0.112315,...,1.369847,0.009291,-0.156073,-0.035528,144,0.615285,-0.788305,-0.965926,-0.258819,1.410987
2730,2730,2018-06-19 19:24:00,0.051536,0.046751,0.038356,0.069572,0.074987,0.053739,0.051703,0.041847,...,1.077817,-0.165069,-0.037458,-0.020389,170,0.213521,-0.976938,-0.965926,0.258819,1.029619
2731,2731,2019-09-17 15:50:00,0.048440,0.116872,0.101207,0.040520,0.053809,0.062569,0.082519,0.073375,...,1.327936,0.075266,-0.140880,0.122702,260,-0.972118,-0.234491,-0.707107,-0.707107,1.280934

In [ ]:
TARGET = "result_DOC_log" #FOR DOC
TARGET1 = "result_DOC"

input_features = ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 
                'B9',
               "B4_minus_B3",
               "B4_div_B3", 
               "ND_B4_B3", 
               'Temperature', 'DewPoint', 'v10n', 
               'doy_sin', 'doy_cos', 
               'latitude', 'longitude'
               ]

X_train = doc_train_augmented[input_features]
y_train = doc_train_augmented[TARGET]

X_test = doc_test[input_features]
y_test = doc_test[TARGET]

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2732, 19), (2732,), (171, 19), (171,))

In [4]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
import xgboost as xgb
from xgboost import XGBRegressor

#Checking version of xgboost
print("XGBoost version:", xgb.__version__)

XGBoost version: 3.1.2

In [ ]:
model_doc_aug = XGBRegressor(
    tree_method="hist",   # histogram algorithm
    device="cuda",        # GPU
    n_estimators=1800,
    max_depth=4,
    learning_rate=0.03,
    subsample=0.8,
    min_child_weight=7,
    colsample_bytree=0.8,
    reg_lambda = 4,
    reg_alpha = 0,
    
    objective='reg:squarederror',
    random_state=42
)



model_doc_aug.fit(X_train, y_train)
y_pred = model_doc_aug.predict(X_test)

print("R² for DOC :", r2_score(y_test, y_pred))


# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)

#y_pred_orig = np.expm1(y_pred)
#y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC : 0.7000117904206494
R² for DOC on normal: 0.6219682519591032
Final metrics on NORMAL scale (after inverse log):
R²   : 0.6220
MSE  : 1.1789
RMSE : 1.0858
MAE  : 0.6649

In [ ]:
#HYPERPARAM TUNING WITH OPTUNA

In [ ]:
#using K fold
from sklearn.model_selection import RepeatedKFold, cross_val_score
from sklearn.metrics import make_scorer, r2_score
import optuna
import xgboost as xgb
from xgboost import XGBRegressor
from sklearn.preprocessing import StandardScaler

#Checking version of xgboost
print("XGBoost version:", xgb.__version__)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

XGBoost version: 3.1.2

In [ ]:
def objective_cv(trial):
    params = {

        "n_estimators": trial.suggest_int("n_estimators", 1000, 2500),
        "max_depth": trial.suggest_int("max_depth", 3, 6),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.08, log=True),

        "min_child_weight": trial.suggest_int("min_child_weight", 3, 12),
        "subsample": trial.suggest_float("subsample", 0.65, 0.9),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.65, 0.9),

        

        "reg_lambda": trial.suggest_float("reg_lambda", 0.5, 10.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 3.0),

        "tree_method": "hist",
        "device": "cuda",
        "objective": "reg:squarederror",
        "random_state": 42
    }

    model = XGBRegressor(**params)

    r2_scorer = make_scorer(r2_score)

    scores = cross_val_score(model, X_train_scaled, y_train, cv=3, scoring=r2_scorer)
    mean_r2 = np.mean(scores)
    return mean_r2

In [13]:
# 3️⃣ Run Optuna study
# --------------------------
study = optuna.create_study(direction="maximize", study_name = "xgboost_study_cuda", sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective_cv, n_trials=50, show_progress_bar=True, n_jobs=-1)

[I 2026-01-24 11:34:26,684] A new study created in memory with name: xgboost_study_cuda
Best trial: 3. Best value: 0.850101:   2%|▏         | 1/50 [01:13<59:47, 73.22s/it]

[I 2026-01-24 11:35:39,902] Trial 3 finished with value: 0.8501008253378708 and parameters: {'n_estimators': 1279, 'max_depth': 3, 'learning_rate': 0.0309834329987831, 'min_child_weight': 8, 'subsample': 0.8535419345464512, 'colsample_bytree': 0.6962748690993762, 'reg_lambda': 3.3578703878312783, 'reg_alpha': 2.890835667294872}. Best is trial 3 with value: 0.8501008253378708.

Best trial: 3. Best value: 0.850101:   4%|▍         | 2/50 [01:14<24:40, 30.85s/it]

[I 2026-01-24 11:35:41,090] Trial 7 finished with value: 0.83293081922104 and parameters: {'n_estimators': 1266, 'max_depth': 3, 'learning_rate': 0.021134009156218464, 'min_child_weight': 3, 'subsample': 0.8720043604332199, 'colsample_bytree': 0.7250296838231944, 'reg_lambda': 6.043335530425214, 'reg_alpha': 2.3280718823267903}. Best is trial 3 with value: 0.8501008253378708.

Best trial: 2. Best value: 0.939646:   6%|▌         | 3/50 [01:27<17:38, 22.53s/it]

[I 2026-01-24 11:35:53,711] Trial 2 finished with value: 0.9396455353436505 and parameters: {'n_estimators': 1307, 'max_depth': 4, 'learning_rate': 0.05625820635623458, 'min_child_weight': 7, 'subsample': 0.8789810953976178, 'colsample_bytree': 0.7738729222947069, 'reg_lambda': 5.451953412207738, 'reg_alpha': 1.6899311126087393}. Best is trial 2 with value: 0.9396455353436505.

Best trial: 2. Best value: 0.939646:   8%|▊         | 4/50 [01:30<11:26, 14.92s/it]

[I 2026-01-24 11:35:56,978] Trial 0 finished with value: 0.8991871555953618 and parameters: {'n_estimators': 1516, 'max_depth': 3, 'learning_rate': 0.03956643044531991, 'min_child_weight': 12, 'subsample': 0.7942601942438962, 'colsample_bytree': 0.8722494570908911, 'reg_lambda': 1.8053632287427028, 'reg_alpha': 1.9972201894531338}. Best is trial 2 with value: 0.9396455353436505.

Best trial: 12. Best value: 0.964699:  10%|█         | 5/50 [01:44<10:52, 14.49s/it]

[I 2026-01-24 11:36:10,704] Trial 12 finished with value: 0.964699049131017 and parameters: {'n_estimators': 1123, 'max_depth': 6, 'learning_rate': 0.02760451203825585, 'min_child_weight': 4, 'subsample': 0.7867151592727893, 'colsample_bytree': 0.7661626888379766, 'reg_lambda': 4.076322563460206, 'reg_alpha': 0.8196014995245802}. Best is trial 12 with value: 0.964699049131017.

Best trial: 12. Best value: 0.964699:  12%|█▏        | 6/50 [01:48<08:09, 11.13s/it]

[I 2026-01-24 11:36:15,301] Trial 4 finished with value: 0.8375113216015514 and parameters: {'n_estimators': 1929, 'max_depth': 3, 'learning_rate': 0.016836491232109126, 'min_child_weight': 6, 'subsample': 0.8407183023769362, 'colsample_bytree': 0.7873833674048931, 'reg_lambda': 6.108118835137628, 'reg_alpha': 2.7927596422872383}. Best is trial 12 with value: 0.964699049131017.

Best trial: 12. Best value: 0.964699:  14%|█▍        | 7/50 [01:58<07:45, 10.83s/it]

[I 2026-01-24 11:36:25,526] Trial 1 finished with value: 0.885915595223889 and parameters: {'n_estimators': 1703, 'max_depth': 4, 'learning_rate': 0.015920816334609313, 'min_child_weight': 6, 'subsample': 0.6954276206229929, 'colsample_bytree': 0.6809607269161936, 'reg_lambda': 7.606276671807688, 'reg_alpha': 2.035052948800839}. Best is trial 12 with value: 0.964699049131017.

Best trial: 12. Best value: 0.964699:  16%|█▌        | 8/50 [01:59<05:15,  7.51s/it]

[I 2026-01-24 11:36:25,932] Trial 15 finished with value: 0.9611459353071027 and parameters: {'n_estimators': 1487, 'max_depth': 5, 'learning_rate': 0.024135412521771715, 'min_child_weight': 8, 'subsample': 0.6721776311280239, 'colsample_bytree': 0.7398862893951028, 'reg_lambda': 8.849975476992114, 'reg_alpha': 0.5719854897422729}. Best is trial 12 with value: 0.964699049131017.

Best trial: 12. Best value: 0.964699:  18%|█▊        | 9/50 [02:03<04:25,  6.47s/it]

[I 2026-01-24 11:36:30,105] Trial 11 finished with value: 0.9437873695811207 and parameters: {'n_estimators': 2134, 'max_depth': 3, 'learning_rate': 0.030221098420342398, 'min_child_weight': 3, 'subsample': 0.8280665601028299, 'colsample_bytree': 0.7382597725302908, 'reg_lambda': 1.7979647698750911, 'reg_alpha': 0.501302234735581}. Best is trial 12 with value: 0.964699049131017.

Best trial: 12. Best value: 0.964699:  20%|██        | 10/50 [02:06<03:34,  5.37s/it]

[I 2026-01-24 11:36:33,019] Trial 9 finished with value: 0.9261890498200839 and parameters: {'n_estimators': 2115, 'max_depth': 3, 'learning_rate': 0.0291252777410336, 'min_child_weight': 9, 'subsample': 0.7481914886002725, 'colsample_bytree': 0.6846492698614826, 'reg_lambda': 6.115034287135775, 'reg_alpha': 0.7669829526552749}. Best is trial 12 with value: 0.964699049131017.

Best trial: 12. Best value: 0.964699:  22%|██▏       | 11/50 [02:07<02:43,  4.19s/it]

[I 2026-01-24 11:36:34,543] Trial 8 finished with value: 0.934860990622898 and parameters: {'n_estimators': 2151, 'max_depth': 3, 'learning_rate': 0.041779979615380936, 'min_child_weight': 10, 'subsample': 0.7973193028145225, 'colsample_bytree': 0.6664645797366845, 'reg_lambda': 9.134638334653097, 'reg_alpha': 0.9608542985898855}. Best is trial 12 with value: 0.964699049131017.

Best trial: 12. Best value: 0.964699:  24%|██▍       | 12/50 [02:09<02:07,  3.36s/it]

[I 2026-01-24 11:36:35,990] Trial 13 finished with value: 0.9473213811139471 and parameters: {'n_estimators': 2297, 'max_depth': 3, 'learning_rate': 0.02748441278320811, 'min_child_weight': 12, 'subsample': 0.7189861212924301, 'colsample_bytree': 0.888987671382811, 'reg_lambda': 1.4132769274000125, 'reg_alpha': 0.03710455765710097}. Best is trial 12 with value: 0.964699049131017.

Best trial: 12. Best value: 0.964699:  26%|██▌       | 13/50 [02:13<02:13,  3.62s/it]

[I 2026-01-24 11:36:40,210] Trial 5 finished with value: 0.953826475614656 and parameters: {'n_estimators': 2372, 'max_depth': 3, 'learning_rate': 0.06943698011996989, 'min_child_weight': 3, 'subsample': 0.880883143247293, 'colsample_bytree': 0.7374311138474797, 'reg_lambda': 8.00669012804828, 'reg_alpha': 0.943266431561283}. Best is trial 12 with value: 0.964699049131017.

Best trial: 6. Best value: 0.975974:  28%|██▊       | 14/50 [02:31<04:48,  8.03s/it]

[I 2026-01-24 11:36:58,418] Trial 6 finished with value: 0.9759739590007902 and parameters: {'n_estimators': 1682, 'max_depth': 5, 'learning_rate': 0.028674815031076634, 'min_child_weight': 4, 'subsample': 0.6765035985150453, 'colsample_bytree': 0.8052711459022822, 'reg_lambda': 1.2607105049770004, 'reg_alpha': 0.40223146823880374}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  30%|███       | 15/50 [02:39<04:34,  7.84s/it]

[I 2026-01-24 11:37:05,815] Trial 14 finished with value: 0.9452153012785489 and parameters: {'n_estimators': 2238, 'max_depth': 5, 'learning_rate': 0.04076058230315678, 'min_child_weight': 10, 'subsample': 0.774124457489799, 'colsample_bytree': 0.7316093196119754, 'reg_lambda': 4.637605259542862, 'reg_alpha': 1.8765152559225697}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  32%|███▏      | 16/50 [02:49<04:52,  8.60s/it]

[I 2026-01-24 11:37:16,193] Trial 10 finished with value: 0.9413064344948722 and parameters: {'n_estimators': 1762, 'max_depth': 6, 'learning_rate': 0.010324206243254542, 'min_child_weight': 9, 'subsample': 0.8775885048688701, 'colsample_bytree': 0.7692118792491051, 'reg_lambda': 7.398271784561947, 'reg_alpha': 1.2555332730966848}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  34%|███▍      | 17/50 [03:14<07:31, 13.67s/it]

[I 2026-01-24 11:37:41,664] Trial 20 finished with value: 0.9507511232332816 and parameters: {'n_estimators': 1091, 'max_depth': 5, 'learning_rate': 0.0222794477316347, 'min_child_weight': 10, 'subsample': 0.700481134645905, 'colsample_bytree': 0.80657612938026, 'reg_lambda': 1.2731872728818026, 'reg_alpha': 0.7870159739154883}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  36%|███▌      | 18/50 [03:42<09:30, 17.84s/it]

[I 2026-01-24 11:38:09,192] Trial 23 finished with value: 0.8691011163501677 and parameters: {'n_estimators': 1682, 'max_depth': 3, 'learning_rate': 0.03151422987161912, 'min_child_weight': 11, 'subsample': 0.6951373574214379, 'colsample_bytree': 0.7491735125703716, 'reg_lambda': 2.994591358657445, 'reg_alpha': 2.5868761853063362}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  38%|███▊      | 19/50 [03:46<07:08, 13.81s/it]

[I 2026-01-24 11:38:13,634] Trial 18 finished with value: 0.94792101644249 and parameters: {'n_estimators': 2195, 'max_depth': 3, 'learning_rate': 0.048612391456712804, 'min_child_weight': 7, 'subsample': 0.7913599952542432, 'colsample_bytree': 0.7403615316293611, 'reg_lambda': 4.069222782045161, 'reg_alpha': 0.8697469148463483}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  40%|████      | 20/50 [03:51<05:30, 11.03s/it]

[I 2026-01-24 11:38:18,167] Trial 22 finished with value: 0.9135668422529967 and parameters: {'n_estimators': 1764, 'max_depth': 3, 'learning_rate': 0.030672245501656793, 'min_child_weight': 12, 'subsample': 0.8193399618625066, 'colsample_bytree': 0.876354391260858, 'reg_lambda': 3.454893959522157, 'reg_alpha': 1.2092836784257632}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  42%|████▏     | 21/50 [03:54<04:06,  8.52s/it]

[I 2026-01-24 11:38:20,827] Trial 25 finished with value: 0.9511440613378032 and parameters: {'n_estimators': 1005, 'max_depth': 6, 'learning_rate': 0.010647342126989229, 'min_child_weight': 4, 'subsample': 0.7307657984606845, 'colsample_bytree': 0.8505438950444583, 'reg_lambda': 3.7590508325621417, 'reg_alpha': 0.0011061807533500057}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  44%|████▍     | 22/50 [03:56<03:08,  6.74s/it]

[I 2026-01-24 11:38:23,431] Trial 21 finished with value: 0.940371534461212 and parameters: {'n_estimators': 1374, 'max_depth': 6, 'learning_rate': 0.02607205208086549, 'min_child_weight': 8, 'subsample': 0.7848446644847873, 'colsample_bytree': 0.653429292846039, 'reg_lambda': 8.670643256173125, 'reg_alpha': 1.6791097394478718}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  46%|████▌     | 23/50 [03:58<02:19,  5.18s/it]

[I 2026-01-24 11:38:24,976] Trial 27 finished with value: 0.9140468618277944 and parameters: {'n_estimators': 1076, 'max_depth': 6, 'learning_rate': 0.011250106429889646, 'min_child_weight': 5, 'subsample': 0.6755500995048005, 'colsample_bytree': 0.7953915803047815, 'reg_lambda': 9.965963062239812, 'reg_alpha': 1.187357584174548}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  48%|████▊     | 24/50 [04:01<01:57,  4.53s/it]

[I 2026-01-24 11:38:27,991] Trial 26 finished with value: 0.95474057603947 and parameters: {'n_estimators': 1064, 'max_depth': 6, 'learning_rate': 0.011281369383308986, 'min_child_weight': 5, 'subsample': 0.6560979634992886, 'colsample_bytree': 0.824998563392091, 'reg_lambda': 3.509462723850496, 'reg_alpha': 0.010531396050963537}. Best is trial 6 with value: 0.9759739590007902.
[I 2026-01-24 11:38:28,088] Trial 28 finished with value: 0.9729347682970033 and parameters: {'n_estimators': 1045, 'max_depth': 6, 'learning_rate': 0.02111147808957565, 'min_child_weight': 5, 'subsample': 0.6739196785939947, 'colsample_bytree': 0.820671978354684, 'reg_lambda': 3.7743965673999105, 'reg_alpha': 0.21970159226685126}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  52%|█████▏    | 26/50 [04:12<02:01,  5.05s/it]

[I 2026-01-24 11:38:39,280] Trial 24 finished with value: 0.9706644915491206 and parameters: {'n_estimators': 1597, 'max_depth': 5, 'learning_rate': 0.07259657397958666, 'min_child_weight': 6, 'subsample': 0.7104421448635779, 'colsample_bytree': 0.8520050477622807, 'reg_lambda': 2.3284422570673664, 'reg_alpha': 0.8802081082630866}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  54%|█████▍    | 27/50 [04:28<02:55,  7.63s/it]

[I 2026-01-24 11:38:54,732] Trial 19 finished with value: 0.9646047874812508 and parameters: {'n_estimators': 1906, 'max_depth': 6, 'learning_rate': 0.04519361420308849, 'min_child_weight': 11, 'subsample': 0.7472356777019731, 'colsample_bytree': 0.6580004259553903, 'reg_lambda': 3.589320034079528, 'reg_alpha': 1.0546427470393316}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  56%|█████▌    | 28/50 [04:28<02:07,  5.79s/it]

[I 2026-01-24 11:38:55,331] Trial 30 finished with value: 0.9482046954638156 and parameters: {'n_estimators': 1036, 'max_depth': 6, 'learning_rate': 0.010247473553284309, 'min_child_weight': 5, 'subsample': 0.6599569544127806, 'colsample_bytree': 0.8370649447930065, 'reg_lambda': 3.2170088141012085, 'reg_alpha': 0.08832383113752396}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  58%|█████▊    | 29/50 [04:30<01:37,  4.63s/it]

[I 2026-01-24 11:38:56,862] Trial 17 finished with value: 0.8961088177543717 and parameters: {'n_estimators': 2299, 'max_depth': 5, 'learning_rate': 0.010683057990574351, 'min_child_weight': 5, 'subsample': 0.8357775900075968, 'colsample_bytree': 0.7566445266144498, 'reg_lambda': 6.155345253879597, 'reg_alpha': 2.8975301150873}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  60%|██████    | 30/50 [04:37<01:46,  5.30s/it]

[I 2026-01-24 11:39:03,892] Trial 29 finished with value: 0.9602003311546863 and parameters: {'n_estimators': 1073, 'max_depth': 6, 'learning_rate': 0.012071841542638765, 'min_child_weight': 5, 'subsample': 0.7495526767132271, 'colsample_bytree': 0.8376715681502303, 'reg_lambda': 3.5424577676733744, 'reg_alpha': 0.04454025593007305}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  62%|██████▏   | 31/50 [04:40<01:28,  4.68s/it]

[I 2026-01-24 11:39:07,015] Trial 31 finished with value: 0.9739572591773703 and parameters: {'n_estimators': 1056, 'max_depth': 6, 'learning_rate': 0.018435185157479626, 'min_child_weight': 5, 'subsample': 0.7363059152458904, 'colsample_bytree': 0.8266567301630934, 'reg_lambda': 3.69770741233386, 'reg_alpha': 0.00755684561959491}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  64%|██████▍   | 32/50 [04:47<01:35,  5.31s/it]

[I 2026-01-24 11:39:13,856] Trial 16 finished with value: 0.9267299598997694 and parameters: {'n_estimators': 2361, 'max_depth': 6, 'learning_rate': 0.014314199480431439, 'min_child_weight': 9, 'subsample': 0.8069898431000424, 'colsample_bytree': 0.6599355303681258, 'reg_lambda': 3.0276675466401164, 'reg_alpha': 2.288868372562299}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  66%|██████▌   | 33/50 [05:06<02:39,  9.39s/it]

[I 2026-01-24 11:39:33,107] Trial 32 finished with value: 0.9706953210170908 and parameters: {'n_estimators': 1066, 'max_depth': 6, 'learning_rate': 0.016292201950924554, 'min_child_weight': 5, 'subsample': 0.6546442821045696, 'colsample_bytree': 0.8389277220640018, 'reg_lambda': 3.246001514973882, 'reg_alpha': 0.024528573758529015}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  68%|██████▊   | 34/50 [05:31<03:44, 14.01s/it]

[I 2026-01-24 11:39:58,164] Trial 33 finished with value: 0.9646684752763468 and parameters: {'n_estimators': 1009, 'max_depth': 6, 'learning_rate': 0.014762365649065246, 'min_child_weight': 5, 'subsample': 0.6519333209715485, 'colsample_bytree': 0.828941906591306, 'reg_lambda': 3.4893073722694914, 'reg_alpha': 0.10687414962576802}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  70%|███████   | 35/50 [05:45<03:31, 14.08s/it]

[I 2026-01-24 11:40:12,409] Trial 40 finished with value: 0.9615038762944129 and parameters: {'n_estimators': 1142, 'max_depth': 5, 'learning_rate': 0.016863008893672156, 'min_child_weight': 4, 'subsample': 0.7555795425158287, 'colsample_bytree': 0.8412526670356064, 'reg_lambda': 0.6562390838303074, 'reg_alpha': 0.35602188558124154}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  72%|███████▏  | 36/50 [05:46<02:20, 10.05s/it]

[I 2026-01-24 11:40:12,936] Trial 35 finished with value: 0.975133173792825 and parameters: {'n_estimators': 1034, 'max_depth': 6, 'learning_rate': 0.016759645233771214, 'min_child_weight': 5, 'subsample': 0.6566408289040371, 'colsample_bytree': 0.8269097628687634, 'reg_lambda': 0.5507824856199912, 'reg_alpha': 0.012987519095540856}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  74%|███████▍  | 37/50 [05:48<01:41,  7.79s/it]

[I 2026-01-24 11:40:15,422] Trial 34 finished with value: 0.9724404343396132 and parameters: {'n_estimators': 1060, 'max_depth': 6, 'learning_rate': 0.017287215828974075, 'min_child_weight': 5, 'subsample': 0.7474050660732752, 'colsample_bytree': 0.8306157817150599, 'reg_lambda': 2.7812852736669043, 'reg_alpha': 0.17880148591464062}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  76%|███████▌  | 38/50 [06:04<02:03, 10.26s/it]

[I 2026-01-24 11:40:31,474] Trial 36 finished with value: 0.962471718198587 and parameters: {'n_estimators': 1414, 'max_depth': 5, 'learning_rate': 0.02237440541338626, 'min_child_weight': 5, 'subsample': 0.650625253253076, 'colsample_bytree': 0.8181131582835263, 'reg_lambda': 9.794949192505264, 'reg_alpha': 0.42558534907770285}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  78%|███████▊  | 39/50 [06:06<01:25,  7.76s/it]

[I 2026-01-24 11:40:33,376] Trial 37 finished with value: 0.9664482964196814 and parameters: {'n_estimators': 1486, 'max_depth': 5, 'learning_rate': 0.018475519226468326, 'min_child_weight': 5, 'subsample': 0.6504368719419864, 'colsample_bytree': 0.8248582332436732, 'reg_lambda': 2.430555280570832, 'reg_alpha': 0.3808334745363382}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  80%|████████  | 40/50 [06:10<01:05,  6.55s/it]

[I 2026-01-24 11:40:37,111] Trial 38 finished with value: 0.9707623434433187 and parameters: {'n_estimators': 1533, 'max_depth': 5, 'learning_rate': 0.017955259473945284, 'min_child_weight': 5, 'subsample': 0.6501016198538888, 'colsample_bytree': 0.8364947692318456, 'reg_lambda': 0.5556027542175291, 'reg_alpha': 0.29568816216170657}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  82%|████████▏ | 41/50 [06:15<00:55,  6.18s/it]

[I 2026-01-24 11:40:42,417] Trial 39 finished with value: 0.9673947111600363 and parameters: {'n_estimators': 1521, 'max_depth': 5, 'learning_rate': 0.019909093503904997, 'min_child_weight': 5, 'subsample': 0.6558013724936377, 'colsample_bytree': 0.8368745659805732, 'reg_lambda': 2.2621020556763436, 'reg_alpha': 0.45043153914598283}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  84%|████████▍ | 42/50 [06:19<00:44,  5.57s/it]

[I 2026-01-24 11:40:46,571] Trial 44 finished with value: 0.9531265622472546 and parameters: {'n_estimators': 1567, 'max_depth': 4, 'learning_rate': 0.018696159052178262, 'min_child_weight': 6, 'subsample': 0.7111899478159276, 'colsample_bytree': 0.8533444885689115, 'reg_lambda': 0.5318799720284926, 'reg_alpha': 0.33524464051694913}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 6. Best value: 0.975974:  86%|████████▌ | 43/50 [06:20<00:27,  4.00s/it]

[I 2026-01-24 11:40:46,889] Trial 48 finished with value: 0.9394553388414929 and parameters: {'n_estimators': 1164, 'max_depth': 4, 'learning_rate': 0.019000449542605446, 'min_child_weight': 4, 'subsample': 0.6845198410231572, 'colsample_bytree': 0.8113277935715179, 'reg_lambda': 0.5697016054246076, 'reg_alpha': 0.3455391997528891}. Best is trial 6 with value: 0.9759739590007902.

Best trial: 43. Best value: 0.979196:  88%|████████▊ | 44/50 [06:24<00:24,  4.13s/it]

[I 2026-01-24 11:40:51,314] Trial 43 finished with value: 0.9791961347364081 and parameters: {'n_estimators': 1572, 'max_depth': 5, 'learning_rate': 0.07515292745909287, 'min_child_weight': 6, 'subsample': 0.7137335588908229, 'colsample_bytree': 0.8182283878453476, 'reg_lambda': 2.3006654227708974, 'reg_alpha': 0.3709614451429806}. Best is trial 43 with value: 0.9791961347364081.

Best trial: 43. Best value: 0.979196:  90%|█████████ | 45/50 [06:25<00:15,  3.20s/it]

[I 2026-01-24 11:40:52,347] Trial 45 finished with value: 0.9763148706705814 and parameters: {'n_estimators': 1561, 'max_depth': 4, 'learning_rate': 0.0769166741133543, 'min_child_weight': 6, 'subsample': 0.7159901728476397, 'colsample_bytree': 0.862616822733107, 'reg_lambda': 0.5982342692572347, 'reg_alpha': 0.31264940071744585}. Best is trial 43 with value: 0.9791961347364081.

Best trial: 42. Best value: 0.979456:  92%|█████████▏| 46/50 [06:27<00:11,  2.92s/it]

[I 2026-01-24 11:40:54,605] Trial 42 finished with value: 0.9794560939907098 and parameters: {'n_estimators': 1578, 'max_depth': 5, 'learning_rate': 0.07530958220937786, 'min_child_weight': 5, 'subsample': 0.6636151981679363, 'colsample_bytree': 0.8293060052837359, 'reg_lambda': 2.409308901879787, 'reg_alpha': 0.33529031476388216}. Best is trial 42 with value: 0.9794560939907098.

Best trial: 42. Best value: 0.979456:  98%|█████████▊| 49/50 [06:28<00:01,  1.24s/it]

[I 2026-01-24 11:40:55,337] Trial 49 finished with value: 0.9429195222628547 and parameters: {'n_estimators': 1211, 'max_depth': 4, 'learning_rate': 0.01949038325483035, 'min_child_weight': 4, 'subsample': 0.6814051661873285, 'colsample_bytree': 0.8120458671993622, 'reg_lambda': 0.610649238452825, 'reg_alpha': 0.33417844377622746}. Best is trial 42 with value: 0.9794560939907098.
[I 2026-01-24 11:40:55,342] Trial 41 finished with value: 0.9786311530004422 and parameters: {'n_estimators': 1921, 'max_depth': 5, 'learning_rate': 0.07019553748110367, 'min_child_weight': 5, 'subsample': 0.6501999319158198, 'colsample_bytree': 0.8325900380392046, 'reg_lambda': 0.5095350273519883, 'reg_alpha': 0.3617481979562722}. Best is trial 42 with value: 0.9794560939907098.
[I 2026-01-24 11:40:55,448] Trial 46 finished with value: 0.9683733789772234 and parameters: {'n_estimators': 1535, 'max_depth': 5, 'learning_rate': 0.017859243399983824, 'min_child_weight': 6, 'subsample': 0.7088043535881874, 'colsample_bytree': 0.8608539644028566, 'reg_lambda': 2.457040176330407, 'reg_alpha': 0.33214866042393915}. Best is trial 42 with value: 0.9794560939907098.

Best trial: 42. Best value: 0.979456: 100%|██████████| 50/50 [06:29<00:00,  7.79s/it]

[I 2026-01-24 11:40:56,085] Trial 47 finished with value: 0.973034817876652 and parameters: {'n_estimators': 1565, 'max_depth': 5, 'learning_rate': 0.01974556852649059, 'min_child_weight': 6, 'subsample': 0.7098962530765854, 'colsample_bytree': 0.8580590745881956, 'reg_lambda': 0.5410012513873492, 'reg_alpha': 0.32927825479092687}. Best is trial 42 with value: 0.9794560939907098.

In [14]:
print("Best mean CV R²:", study.best_value)
print("Best hyperparameters:", study.best_params)

Best mean CV R²: 0.9794560939907098
Best hyperparameters: {'n_estimators': 1578, 'max_depth': 5, 'learning_rate': 0.07530958220937786, 'min_child_weight': 5, 'subsample': 0.6636151981679363, 'colsample_bytree': 0.8293060052837359, 'reg_lambda': 2.409308901879787, 'reg_alpha': 0.33529031476388216}

In [ ]:
"""
Best mean CV R²: 0.9794560939907098
Best hyperparameters: {'n_estimators': 1578, 
'max_depth': 5, 
'learning_rate': 0.07530958220937786, 
'min_child_weight': 5, 
'subsample': 0.6636151981679363, 
'colsample_bytree': 0.8293060052837359, 
'reg_lambda': 2.409308901879787, 
'reg_alpha': 0.33529031476388216}
"""

In [20]:
best_params =  {'n_estimators': 1578, 'max_depth': 5, 'learning_rate': 0.07530958220937786, 'min_child_weight': 5, 'subsample': 0.6636151981679363, 'colsample_bytree': 0.8293060052837359, 'reg_lambda': 2.409308901879787, 'reg_alpha': 0.33529031476388216}
print(best_params)

{'n_estimators': 1578, 'max_depth': 5, 'learning_rate': 0.07530958220937786, 'min_child_weight': 5, 'subsample': 0.6636151981679363, 'colsample_bytree': 0.8293060052837359, 'reg_lambda': 2.409308901879787, 'reg_alpha': 0.33529031476388216}

In [ ]:
# 4️⃣ Train final model on all augmented train data with best params
# --------------------------
#best_params = study.best_params
final_model = XGBRegressor(
    **best_params,
    tree_method="hist",
    device="cuda",
    objective="reg:squarederror",
    random_state=42
)

final_model.fit(X_train_scaled, y_train)

y_pred_log = final_model.predict(X_test_scaled)

import numpy as np
from sklearn.metrics import r2_score

y_pred_real = np.expm1(y_pred_log)
y_test_real = np.expm1(y_test)

print("Final R² (log scale):", r2_score(y_test, y_pred_log))
print("Final R² (real scale):", r2_score(y_test_real, y_pred_real))


# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred_log)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

Final R² (log scale): 0.7083042378380461
Final R² (real scale): 0.6559290615878791
R² for DOC on normal: 0.6559290615878791
Final metrics on NORMAL scale (after inverse log):
R²   : 0.6559
MSE  : 1.0730
RMSE : 1.0358
MAE  : 0.6331

In [ ]:
#Without meteorology

In [1]:
#FOR AUGMENTED_NEW

import pandas as pd
import numpy as np

aug_factor = 3 #augmented has been done initially for aug_factor = 2, then for aug_factor = 3

doc_train_augmented = pd.read_csv (f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TRAIN_AUG{aug_factor}.csv")
doc_test = pd.read_csv(f"D:\Shukra_sir\MLAllTraining\ForTraining\TrainableWithBandRatios\AugmentedWithBR\DOC_AUG_WITH_BR\DOCWithBR_TEST_AUG{aug_factor}.csv")

doc_train_augmented.shape, doc_test.shape

((2732, 55), (171, 55))

In [2]:
doc_train_augmented ['result_DOC_log'] = np.log1p (doc_train_augmented ['result_DOC'])
doc_test ['result_DOC_log'] = np.log1p (doc_test ['result_DOC'])
doc_train_augmented

,Unnamed: 0,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,...,B3_div_B2,ND_B4_B3,ND_B2_B3,ND_B6_B8,day_of_year,doy_sin,doy_cos,hour_sin,hour_cos,result_DOC_log
0,0,2024-05-08 14:00:00,0.037800,0.168600,0.105100,0.040100,0.063600,0.050700,0.094400,0.220200,...,1.585995,-0.112860,-0.226613,-0.130503,129,0.796183,-0.605056,-0.500000,-0.866025,0.741937
1,1,2019-08-20 15:00:00,0.068100,0.144400,0.130300,0.057300,0.075900,0.073100,0.098200,0.105800,...,1.324584,-0.018792,-0.139639,0.109596,232,-0.752667,-0.658402,-0.707107,-0.707107,1.308333
2,2,2022-02-01 20:55:00,0.015100,0.165100,0.131400,0.033200,0.053800,0.056300,0.095100,0.146200,...,1.620433,0.022706,-0.236779,-0.071156,32,0.523416,0.852078,-0.866025,0.500000,0.741937
3,3,2018-11-06 21:25:00,0.007100,0.026500,0.019000,0.019100,0.030400,0.022600,0.023400,0.014200,...,1.591540,-0.147167,-0.228278,-0.080904,310,-0.811539,0.584298,-0.707107,0.707107,1.481605
4,4,2018-11-06 19:20:00,0.001400,0.010400,0.010300,0.013300,0.020300,0.008900,0.006200,0.000000,...,1.526201,-0.390398,-0.208327,0.000000,310,-0.811539,0.584298,-0.965926,0.258819,1.193922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,2727,2019-08-20 16:00:00,0.160048,0.347841,0.301870,0.194634,0.206942,0.225023,0.253643,0.254485,...,1.063231,0.041857,-0.030649,-0.043629,232,-0.752667,-0.658402,-0.866025,-0.500000,1.536867
2728,2728,2021-08-17 15:45:00,0.106466,0.173790,0.156926,0.132880,0.156900,0.169819,0.182550,0.194755,...,1.180757,0.039542,-0.082891,0.040882,229,-0.717677,-0.696376,-0.707107,-0.707107,1.547563
2729,2729,2023-05-24 17:43:00,0.041518,0.115512,0.094602,0.046671,0.063934,0.065133,0.090442,0.112315,...,1.369847,0.009291,-0.156073,-0.035528,144,0.615285,-0.788305,-0.965926,-0.258819,1.410987
2730,2730,2018-06-19 19:24:00,0.051536,0.046751,0.038356,0.069572,0.074987,0.053739,0.051703,0.041847,...,1.077817,-0.165069,-0.037458,-0.020389,170,0.213521,-0.976938,-0.965926,0.258819,1.029619
2731,2731,2019-09-17 15:50:00,0.048440,0.116872,0.101207,0.040520,0.053809,0.062569,0.082519,0.073375,...,1.327936,0.075266,-0.140880,0.122702,260,-0.972118,-0.234491,-0.707107,-0.707107,1.280934

In [3]:
TARGET = "result_DOC_log" #FOR DOC
TARGET1 = "result_DOC"

input_features_noMeteo = ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 
                'B9',
               "B4_minus_B3",
               "B4_div_B3", 
               "ND_B4_B3", 
               #'Temperature', 'DewPoint', 'v10n',
               'doy_sin', 'doy_cos', 
               'latitude', 'longitude'
               ]

X_train = doc_train_augmented[input_features_noMeteo]
y_train = doc_train_augmented[TARGET]

X_test = doc_test[input_features_noMeteo]
y_test = doc_test[TARGET]

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2732, 16), (2732,), (171, 16), (171,))

In [4]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
import xgboost as xgb
from xgboost import XGBRegressor

#Checking version of xgboost
print("XGBoost version:", xgb.__version__)

XGBoost version: 3.1.2

In [ ]:

baseline_doc_NoMeteo = XGBRegressor(
    tree_method="hist",   # histogram algorithm
    device="cuda",        # GPU
    n_estimators=1800,
    max_depth=4,
    learning_rate=0.03,
    subsample=0.8,
    min_child_weight=7,
    colsample_bytree=0.8,
    reg_lambda = 4,
    reg_alpha = 0,
    objective='reg:squarederror',
    random_state=42
)


baseline_doc_NoMeteo.fit(X_train, y_train)
y_pred = baseline_doc_NoMeteo.predict(X_test)

print("R² for DOC :", r2_score(y_test, y_pred))

y_pred_orig = np.expm1(y_pred)
y_test_real = np.expm1(y_test)
print("R² for DOC on normal:", r2_score(y_test_real, y_pred_orig))

# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred)
y_test_real = np.expm1(y_test)

print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

R² for DOC : 0.6652383944527069
R² for DOC on normal: 0.5485873910975492
R² for DOC on normal: 0.5485873910975492
Final metrics on NORMAL scale (after inverse log):
R²   : 0.5486
MSE  : 1.4077
RMSE : 1.1865
MAE  : 0.6924

In [ ]:
#HYPERPARAM TUNING WITH OPTUNA - FOR NO METEO

In [6]:
#using K fold
from sklearn.model_selection import RepeatedKFold, cross_val_score
from sklearn.metrics import make_scorer, r2_score
import optuna
import xgboost as xgb
from xgboost import XGBRegressor
from sklearn.preprocessing import StandardScaler

#Checking version of xgboost
print("XGBoost version:", xgb.__version__)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
#X_val_scaled = scaler.transform(X_test)
X_test_scaled = scaler.transform(X_test)

XGBoost version: 3.1.2

d:\Miniconda3\envs\PyTorchVirtualEnv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
#NM stands for No Meteo

def objective_cv_NM(trial):
    params = {

        "n_estimators": trial.suggest_int("n_estimators", 1000, 2500),
        "max_depth": trial.suggest_int("max_depth", 3, 6),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.08, log=True),

        "min_child_weight": trial.suggest_int("min_child_weight", 3, 12),
        "subsample": trial.suggest_float("subsample", 0.65, 0.9),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.65, 0.9),

        "reg_lambda": trial.suggest_float("reg_lambda", 0.5, 10.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 3.0),

        "tree_method": "hist",
        "device": "cuda",
        "objective": "reg:squarederror",
        "random_state": 42
    }

    model = XGBRegressor(**params)

    r2_scorer = make_scorer(r2_score)

    scores = cross_val_score(model, X_train_scaled, y_train, cv=3, scoring=r2_scorer)
    mean_r2 = np.mean(scores)
    return mean_r2

In [ ]:

study = optuna.create_study(direction="maximize", study_name = "xgboost_study_cuda", sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective_cv_NM, n_trials=50, show_progress_bar=True, n_jobs=-1)

[I 2026-02-07 17:51:10,218] A new study created in memory with name: xgboost_study_cuda
Best trial: 15. Best value: 0.823656:   2%|▏         | 1/50 [00:53<43:55, 53.79s/it]

[I 2026-02-07 17:52:04,008] Trial 15 finished with value: 0.823656017694517 and parameters: {'n_estimators': 1071, 'max_depth': 3, 'learning_rate': 0.027068514854313167, 'min_child_weight': 11, 'subsample': 0.8653715674994691, 'colsample_bytree': 0.668344770945311, 'reg_lambda': 1.6774737880810744, 'reg_alpha': 2.181926069497563}. Best is trial 15 with value: 0.823656017694517.

Best trial: 1. Best value: 0.932045:   6%|▌         | 3/50 [01:08<13:09, 16.81s/it]

[I 2026-02-07 17:52:18,676] Trial 1 finished with value: 0.9320447182110746 and parameters: {'n_estimators': 1357, 'max_depth': 3, 'learning_rate': 0.061344059322270265, 'min_child_weight': 11, 'subsample': 0.7569186020126597, 'colsample_bytree': 0.6582964593829944, 'reg_lambda': 6.183510764523812, 'reg_alpha': 0.3007447088615681}. Best is trial 1 with value: 0.9320447182110746.
[I 2026-02-07 17:52:18,855] Trial 0 finished with value: 0.8224046210964113 and parameters: {'n_estimators': 1112, 'max_depth': 4, 'learning_rate': 0.010851487433055688, 'min_child_weight': 5, 'subsample': 0.8645940873188804, 'colsample_bytree': 0.6946223767541788, 'reg_lambda': 7.588731287642164, 'reg_alpha': 1.4672523994490585}. Best is trial 1 with value: 0.9320447182110746.

Best trial: 1. Best value: 0.932045:   8%|▊         | 4/50 [01:14<09:34, 12.49s/it]

[I 2026-02-07 17:52:24,741] Trial 11 finished with value: 0.8612117877967279 and parameters: {'n_estimators': 1228, 'max_depth': 4, 'learning_rate': 0.028175931970362354, 'min_child_weight': 9, 'subsample': 0.7274774140964715, 'colsample_bytree': 0.7748656238546037, 'reg_lambda': 4.605584549067376, 'reg_alpha': 2.9133177942744224}. Best is trial 1 with value: 0.9320447182110746.

Best trial: 1. Best value: 0.932045:  10%|█         | 5/50 [01:32<10:55, 14.57s/it]

[I 2026-02-07 17:52:42,983] Trial 7 finished with value: 0.8462877088148083 and parameters: {'n_estimators': 1776, 'max_depth': 3, 'learning_rate': 0.028070282363944942, 'min_child_weight': 9, 'subsample': 0.7731936970003865, 'colsample_bytree': 0.8169350099111571, 'reg_lambda': 6.738274046794878, 'reg_alpha': 2.672269837998347}. Best is trial 1 with value: 0.9320447182110746.

Best trial: 1. Best value: 0.932045:  12%|█▏        | 6/50 [01:40<09:00, 12.27s/it]

[I 2026-02-07 17:52:50,803] Trial 2 finished with value: 0.925158430293146 and parameters: {'n_estimators': 1465, 'max_depth': 6, 'learning_rate': 0.05811307619699993, 'min_child_weight': 4, 'subsample': 0.7629911318449208, 'colsample_bytree': 0.8172914410465416, 'reg_lambda': 7.769941427370443, 'reg_alpha': 2.3756035786979512}. Best is trial 1 with value: 0.9320447182110746.

Best trial: 6. Best value: 0.951903:  14%|█▍        | 7/50 [01:57<09:48, 13.68s/it]

[I 2026-02-07 17:53:07,376] Trial 6 finished with value: 0.9519034890012815 and parameters: {'n_estimators': 2180, 'max_depth': 3, 'learning_rate': 0.04202707959494905, 'min_child_weight': 4, 'subsample': 0.6863517558764642, 'colsample_bytree': 0.8363493513677643, 'reg_lambda': 4.564797195617865, 'reg_alpha': 0.008083478122805743}. Best is trial 6 with value: 0.9519034890012815.

Best trial: 14. Best value: 0.956943:  16%|█▌        | 8/50 [02:02<07:48, 11.17s/it]

[I 2026-02-07 17:53:13,160] Trial 14 finished with value: 0.9569430335233653 and parameters: {'n_estimators': 1408, 'max_depth': 6, 'learning_rate': 0.0341427298015407, 'min_child_weight': 4, 'subsample': 0.6830901019325734, 'colsample_bytree': 0.8298265233077575, 'reg_lambda': 2.2297038907718227, 'reg_alpha': 0.9431042035045558}. Best is trial 14 with value: 0.9569430335233653.

Best trial: 14. Best value: 0.956943:  18%|█▊        | 9/50 [02:05<05:44,  8.40s/it]

[I 2026-02-07 17:53:15,469] Trial 5 finished with value: 0.8753006114426864 and parameters: {'n_estimators': 2313, 'max_depth': 3, 'learning_rate': 0.01605733831646094, 'min_child_weight': 8, 'subsample': 0.8939460961342351, 'colsample_bytree': 0.8510868286009368, 'reg_lambda': 3.32783261499949, 'reg_alpha': 1.0684545519420015}. Best is trial 14 with value: 0.9569430335233653.

Best trial: 14. Best value: 0.956943:  20%|██        | 10/50 [02:13<05:33,  8.33s/it]

[I 2026-02-07 17:53:23,643] Trial 17 finished with value: 0.8916267401693553 and parameters: {'n_estimators': 1122, 'max_depth': 3, 'learning_rate': 0.034230806343103264, 'min_child_weight': 12, 'subsample': 0.889073486842876, 'colsample_bytree': 0.7322085910098637, 'reg_lambda': 1.3244760087964291, 'reg_alpha': 0.4083372939416845}. Best is trial 14 with value: 0.9569430335233653.

Best trial: 14. Best value: 0.956943:  22%|██▏       | 11/50 [02:14<03:55,  6.03s/it]

[I 2026-02-07 17:53:24,466] Trial 9 finished with value: 0.9342907263720702 and parameters: {'n_estimators': 2113, 'max_depth': 4, 'learning_rate': 0.04708984743837868, 'min_child_weight': 12, 'subsample': 0.8905725387849173, 'colsample_bytree': 0.7344656787743841, 'reg_lambda': 8.933717026309802, 'reg_alpha': 1.4176309058902405}. Best is trial 14 with value: 0.9569430335233653.

Best trial: 4. Best value: 0.960356:  24%|██▍       | 12/50 [02:17<03:11,  5.05s/it]

[I 2026-02-07 17:53:27,274] Trial 4 finished with value: 0.9603555388890831 and parameters: {'n_estimators': 1822, 'max_depth': 5, 'learning_rate': 0.018094667026589767, 'min_child_weight': 11, 'subsample': 0.8825045768397344, 'colsample_bytree': 0.7630244612913853, 'reg_lambda': 2.043629643651995, 'reg_alpha': 0.008969547982300874}. Best is trial 4 with value: 0.9603555388890831.

Best trial: 4. Best value: 0.960356:  26%|██▌       | 13/50 [02:20<02:44,  4.44s/it]

[I 2026-02-07 17:53:30,292] Trial 12 finished with value: 0.9566573430170094 and parameters: {'n_estimators': 2013, 'max_depth': 5, 'learning_rate': 0.05779730698741243, 'min_child_weight': 3, 'subsample': 0.8532471030836738, 'colsample_bytree': 0.8088540153705956, 'reg_lambda': 3.844995377042392, 'reg_alpha': 1.0778083875850855}. Best is trial 4 with value: 0.9603555388890831.

Best trial: 4. Best value: 0.960356:  28%|██▊       | 14/50 [02:36<04:45,  7.93s/it]

[I 2026-02-07 17:53:46,310] Trial 10 finished with value: 0.9161725118149523 and parameters: {'n_estimators': 2447, 'max_depth': 4, 'learning_rate': 0.03690772658971439, 'min_child_weight': 12, 'subsample': 0.818495791888607, 'colsample_bytree': 0.7635661756269545, 'reg_lambda': 6.524375177794717, 'reg_alpha': 2.1543592092460937}. Best is trial 4 with value: 0.9603555388890831.

Best trial: 4. Best value: 0.960356:  30%|███       | 15/50 [02:36<03:18,  5.67s/it]

[I 2026-02-07 17:53:46,732] Trial 16 finished with value: 0.9327274844910459 and parameters: {'n_estimators': 1531, 'max_depth': 4, 'learning_rate': 0.03540993829025564, 'min_child_weight': 3, 'subsample': 0.8082888921468944, 'colsample_bytree': 0.7179344855429279, 'reg_lambda': 5.6053322590781525, 'reg_alpha': 1.1364519985892059}. Best is trial 4 with value: 0.9603555388890831.

Best trial: 3. Best value: 0.965552:  32%|███▏      | 16/50 [02:53<05:13,  9.21s/it]

[I 2026-02-07 17:54:04,166] Trial 3 finished with value: 0.9655519737325643 and parameters: {'n_estimators': 2397, 'max_depth': 5, 'learning_rate': 0.07900065201243973, 'min_child_weight': 9, 'subsample': 0.7002930080989547, 'colsample_bytree': 0.808311709131007, 'reg_lambda': 2.022179610297875, 'reg_alpha': 0.7781083822130559}. Best is trial 3 with value: 0.9655519737325643.

Best trial: 8. Best value: 0.972062:  34%|███▍      | 17/50 [03:00<04:39,  8.47s/it]

[I 2026-02-07 17:54:10,923] Trial 8 finished with value: 0.9720623136666516 and parameters: {'n_estimators': 2231, 'max_depth': 5, 'learning_rate': 0.04328466108730501, 'min_child_weight': 12, 'subsample': 0.7804711566963832, 'colsample_bytree': 0.8054574312555064, 'reg_lambda': 5.419948847150801, 'reg_alpha': 0.16443372043800142}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 8. Best value: 0.972062:  36%|███▌      | 18/50 [03:18<05:59, 11.22s/it]

[I 2026-02-07 17:54:28,551] Trial 13 finished with value: 0.9702700192570489 and parameters: {'n_estimators': 2074, 'max_depth': 6, 'learning_rate': 0.025832681024835512, 'min_child_weight': 11, 'subsample': 0.8084601641259396, 'colsample_bytree': 0.6542863837910758, 'reg_lambda': 8.985190755052367, 'reg_alpha': 0.14621338758603097}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 8. Best value: 0.972062:  38%|███▊      | 19/50 [03:23<04:49,  9.35s/it]

[I 2026-02-07 17:54:33,524] Trial 18 finished with value: 0.9501751453980637 and parameters: {'n_estimators': 1501, 'max_depth': 5, 'learning_rate': 0.018056270854797808, 'min_child_weight': 3, 'subsample': 0.8182422571260388, 'colsample_bytree': 0.742344386886745, 'reg_lambda': 5.2323811222753704, 'reg_alpha': 0.47695862631546637}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 8. Best value: 0.972062:  40%|████      | 20/50 [03:36<05:16, 10.55s/it]

[I 2026-02-07 17:54:46,893] Trial 22 finished with value: 0.8978435650184967 and parameters: {'n_estimators': 1263, 'max_depth': 4, 'learning_rate': 0.032856029507059174, 'min_child_weight': 6, 'subsample': 0.724302111453342, 'colsample_bytree': 0.8257576717004858, 'reg_lambda': 4.126608707992295, 'reg_alpha': 1.990091377740967}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 8. Best value: 0.972062:  42%|████▏     | 21/50 [03:47<05:08, 10.64s/it]

[I 2026-02-07 17:54:57,745] Trial 20 finished with value: 0.8791569277018126 and parameters: {'n_estimators': 1811, 'max_depth': 4, 'learning_rate': 0.027808636650549258, 'min_child_weight': 5, 'subsample': 0.8551057905772884, 'colsample_bytree': 0.7977602840459352, 'reg_lambda': 4.6454887671018845, 'reg_alpha': 2.9821224148680883}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 8. Best value: 0.972062:  44%|████▍     | 22/50 [04:20<08:05, 17.33s/it]

[I 2026-02-07 17:55:30,664] Trial 19 finished with value: 0.9589179562186433 and parameters: {'n_estimators': 2017, 'max_depth': 5, 'learning_rate': 0.03152013163594207, 'min_child_weight': 7, 'subsample': 0.8372324251083025, 'colsample_bytree': 0.6690895549488188, 'reg_lambda': 6.6639318879114535, 'reg_alpha': 0.6751725630544311}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 8. Best value: 0.972062:  46%|████▌     | 23/50 [04:55<10:15, 22.78s/it]

[I 2026-02-07 17:56:06,155] Trial 24 finished with value: 0.9587294573069226 and parameters: {'n_estimators': 1816, 'max_depth': 5, 'learning_rate': 0.037956491131031805, 'min_child_weight': 7, 'subsample': 0.7227205783049045, 'colsample_bytree': 0.8190194642605897, 'reg_lambda': 0.5523083149149185, 'reg_alpha': 0.8626708517427377}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 8. Best value: 0.972062:  48%|████▊     | 24/50 [04:59<07:23, 17.05s/it]

[I 2026-02-07 17:56:09,854] Trial 21 finished with value: 0.9174800811223215 and parameters: {'n_estimators': 1966, 'max_depth': 6, 'learning_rate': 0.019245607377082835, 'min_child_weight': 9, 'subsample': 0.7837552739547169, 'colsample_bytree': 0.7247389223174932, 'reg_lambda': 4.844290477802232, 'reg_alpha': 2.075982723458213}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 8. Best value: 0.972062:  50%|█████     | 25/50 [05:25<08:15, 19.82s/it]

[I 2026-02-07 17:56:36,125] Trial 23 finished with value: 0.9278677950721986 and parameters: {'n_estimators': 2166, 'max_depth': 6, 'learning_rate': 0.04788874859526251, 'min_child_weight': 11, 'subsample': 0.7240912278488774, 'colsample_bytree': 0.7202609816124339, 'reg_lambda': 6.421830201312685, 'reg_alpha': 2.2309106965566308}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 8. Best value: 0.972062:  52%|█████▏    | 26/50 [05:27<05:45, 14.38s/it]

[I 2026-02-07 17:56:37,803] Trial 28 finished with value: 0.9564768180990377 and parameters: {'n_estimators': 1627, 'max_depth': 6, 'learning_rate': 0.019453492697692476, 'min_child_weight': 6, 'subsample': 0.6508263455030064, 'colsample_bytree': 0.8936303929983296, 'reg_lambda': 0.6122931625257924, 'reg_alpha': 0.7726830759263756}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 8. Best value: 0.972062:  54%|█████▍    | 27/50 [05:29<04:03, 10.58s/it]

[I 2026-02-07 17:56:39,511] Trial 25 finished with value: 0.9422644168944817 and parameters: {'n_estimators': 1727, 'max_depth': 6, 'learning_rate': 0.017553102447396142, 'min_child_weight': 6, 'subsample': 0.6517696256810178, 'colsample_bytree': 0.894434918984746, 'reg_lambda': 9.570804970028362, 'reg_alpha': 0.9788001742900388}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 8. Best value: 0.972062:  56%|█████▌    | 28/50 [05:32<03:05,  8.44s/it]

[I 2026-02-07 17:56:42,963] Trial 27 finished with value: 0.9533618427679119 and parameters: {'n_estimators': 1691, 'max_depth': 6, 'learning_rate': 0.01769517314662029, 'min_child_weight': 6, 'subsample': 0.6660396241864586, 'colsample_bytree': 0.8851060474415989, 'reg_lambda': 2.7844156210234043, 'reg_alpha': 0.789607331414595}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 8. Best value: 0.972062:  58%|█████▊    | 29/50 [05:54<04:18, 12.29s/it]

[I 2026-02-07 17:57:04,230] Trial 29 finished with value: 0.9640335648403481 and parameters: {'n_estimators': 1666, 'max_depth': 6, 'learning_rate': 0.022072777574346433, 'min_child_weight': 6, 'subsample': 0.6619378717012739, 'colsample_bytree': 0.8905952248305948, 'reg_lambda': 0.5382737893173273, 'reg_alpha': 0.6001038482939967}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 8. Best value: 0.972062:  60%|██████    | 30/50 [05:54<02:55,  8.80s/it]

[I 2026-02-07 17:57:04,885] Trial 30 finished with value: 0.9602870120963848 and parameters: {'n_estimators': 1724, 'max_depth': 6, 'learning_rate': 0.01915590910407307, 'min_child_weight': 6, 'subsample': 0.6512997743319036, 'colsample_bytree': 0.8880314248803611, 'reg_lambda': 2.3337327169053235, 'reg_alpha': 0.6079817456184533}. Best is trial 8 with value: 0.9720623136666516.

Best trial: 26. Best value: 0.977897:  62%|██████▏   | 31/50 [05:56<02:06,  6.67s/it]

[I 2026-02-07 17:57:06,594] Trial 26 finished with value: 0.9778974320037014 and parameters: {'n_estimators': 1816, 'max_depth': 6, 'learning_rate': 0.040432659759585106, 'min_child_weight': 3, 'subsample': 0.6646580644242749, 'colsample_bytree': 0.8957206171905826, 'reg_lambda': 3.6867516659251933, 'reg_alpha': 0.05474003456048959}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  64%|██████▍   | 32/50 [05:59<01:43,  5.74s/it]

[I 2026-02-07 17:57:10,168] Trial 31 finished with value: 0.9536552536928141 and parameters: {'n_estimators': 1833, 'max_depth': 5, 'learning_rate': 0.017802100395235585, 'min_child_weight': 7, 'subsample': 0.7148547936243755, 'colsample_bytree': 0.8999652989503579, 'reg_lambda': 0.5930102886287774, 'reg_alpha': 0.6821335920324543}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  66%|██████▌   | 33/50 [07:27<08:33, 30.22s/it]

[I 2026-02-07 17:58:37,494] Trial 32 finished with value: 0.969908814227856 and parameters: {'n_estimators': 2482, 'max_depth': 5, 'learning_rate': 0.07752724272241432, 'min_child_weight': 6, 'subsample': 0.653807535378218, 'colsample_bytree': 0.8842319552085508, 'reg_lambda': 3.1403696451950798, 'reg_alpha': 0.5995737498560815}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  68%|██████▊   | 34/50 [07:32<06:03, 22.72s/it]

[I 2026-02-07 17:58:42,728] Trial 34 finished with value: 0.9563593687539687 and parameters: {'n_estimators': 1872, 'max_depth': 6, 'learning_rate': 0.021805837888554096, 'min_child_weight': 7, 'subsample': 0.6514637621727869, 'colsample_bytree': 0.8914795137813791, 'reg_lambda': 9.588284279475895, 'reg_alpha': 0.6866929153798332}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  70%|███████   | 35/50 [07:39<04:28, 17.87s/it]

[I 2026-02-07 17:58:49,268] Trial 33 finished with value: 0.9633519940352314 and parameters: {'n_estimators': 1955, 'max_depth': 6, 'learning_rate': 0.020056707994055678, 'min_child_weight': 7, 'subsample': 0.8088775798406252, 'colsample_bytree': 0.8762500028542516, 'reg_lambda': 9.964854004303048, 'reg_alpha': 0.5303339819913067}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  72%|███████▏  | 36/50 [07:46<03:28, 14.86s/it]

[I 2026-02-07 17:58:57,111] Trial 35 finished with value: 0.9568343171131671 and parameters: {'n_estimators': 1948, 'max_depth': 6, 'learning_rate': 0.022499638716357004, 'min_child_weight': 10, 'subsample': 0.6540207027706206, 'colsample_bytree': 0.8809932027727648, 'reg_lambda': 9.988659376221463, 'reg_alpha': 0.6733001772461467}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  74%|███████▍  | 37/50 [08:25<04:47, 22.10s/it]

[I 2026-02-07 17:59:36,096] Trial 36 finished with value: 0.9698754506889805 and parameters: {'n_estimators': 2438, 'max_depth': 6, 'learning_rate': 0.07122085595225008, 'min_child_weight': 10, 'subsample': 0.6526218907356918, 'colsample_bytree': 0.8611564299118205, 'reg_lambda': 9.626371966219473, 'reg_alpha': 0.6187377596935641}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  76%|███████▌  | 38/50 [08:49<04:30, 22.51s/it]

[I 2026-02-07 17:59:59,576] Trial 37 finished with value: 0.9685463804364672 and parameters: {'n_estimators': 2477, 'max_depth': 6, 'learning_rate': 0.06814559970986148, 'min_child_weight': 10, 'subsample': 0.7913803916446773, 'colsample_bytree': 0.8721897658360873, 'reg_lambda': 2.9085898434358377, 'reg_alpha': 0.7094072517335265}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  78%|███████▊  | 39/50 [09:21<04:38, 25.29s/it]

[I 2026-02-07 18:00:31,351] Trial 38 finished with value: 0.9705954080305084 and parameters: {'n_estimators': 2477, 'max_depth': 6, 'learning_rate': 0.07564910215708928, 'min_child_weight': 10, 'subsample': 0.7957865012072182, 'colsample_bytree': 0.8947111968571198, 'reg_lambda': 9.75384964501285, 'reg_alpha': 0.5602052174291261}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  80%|████████  | 40/50 [09:34<03:36, 21.66s/it]

[I 2026-02-07 18:00:44,521] Trial 39 finished with value: 0.974938638401325 and parameters: {'n_estimators': 2402, 'max_depth': 6, 'learning_rate': 0.07866171778159659, 'min_child_weight': 10, 'subsample': 0.6517193311008375, 'colsample_bytree': 0.8741826063916055, 'reg_lambda': 9.801673121092307, 'reg_alpha': 0.2798758494439332}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  82%|████████▏ | 41/50 [09:35<02:18, 15.43s/it]

[I 2026-02-07 18:00:45,421] Trial 41 finished with value: 0.9733858593741912 and parameters: {'n_estimators': 2398, 'max_depth': 5, 'learning_rate': 0.07487059312810325, 'min_child_weight': 10, 'subsample': 0.8040600870339631, 'colsample_bytree': 0.8577803096200864, 'reg_lambda': 9.819881807830384, 'reg_alpha': 0.21590247696767256}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  84%|████████▍ | 42/50 [09:38<01:34, 11.86s/it]

[I 2026-02-07 18:00:48,958] Trial 42 finished with value: 0.9755581501798084 and parameters: {'n_estimators': 2485, 'max_depth': 5, 'learning_rate': 0.07634846063574728, 'min_child_weight': 10, 'subsample': 0.7933906413275427, 'colsample_bytree': 0.8710956894160289, 'reg_lambda': 2.7599319539561242, 'reg_alpha': 0.1939951810008137}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  86%|████████▌ | 43/50 [09:39<01:00,  8.58s/it]

[I 2026-02-07 18:00:49,871] Trial 43 finished with value: 0.9726913450270503 and parameters: {'n_estimators': 2495, 'max_depth': 5, 'learning_rate': 0.0756525356260661, 'min_child_weight': 10, 'subsample': 0.7936413182253766, 'colsample_bytree': 0.7950445583172031, 'reg_lambda': 8.219711636658449, 'reg_alpha': 0.2357056379439187}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  88%|████████▊ | 44/50 [09:42<00:41,  6.93s/it]

[I 2026-02-07 18:00:52,976] Trial 45 finished with value: 0.9733194076613957 and parameters: {'n_estimators': 2455, 'max_depth': 5, 'learning_rate': 0.07960098144267888, 'min_child_weight': 10, 'subsample': 0.7861963603027737, 'colsample_bytree': 0.845530066186748, 'reg_lambda': 7.8386828863201305, 'reg_alpha': 0.22588483949306432}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  90%|█████████ | 45/50 [09:44<00:27,  5.42s/it]

[I 2026-02-07 18:00:54,859] Trial 46 finished with value: 0.9732083133094905 and parameters: {'n_estimators': 2319, 'max_depth': 5, 'learning_rate': 0.07421480560133498, 'min_child_weight': 10, 'subsample': 0.6979899705588181, 'colsample_bytree': 0.8658335762854449, 'reg_lambda': 7.855778663230316, 'reg_alpha': 0.24457754350338667}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  92%|█████████▏| 46/50 [09:46<00:17,  4.28s/it]

[I 2026-02-07 18:00:56,487] Trial 47 finished with value: 0.9746388577263682 and parameters: {'n_estimators': 2452, 'max_depth': 5, 'learning_rate': 0.06895677118900641, 'min_child_weight': 10, 'subsample': 0.7940748930037128, 'colsample_bytree': 0.8657096902602832, 'reg_lambda': 8.167849685796527, 'reg_alpha': 0.20678010961692814}. Best is trial 26 with value: 0.9778974320037014.
[I 2026-02-07 18:00:56,526] Trial 44 finished with value: 0.9731763058949571 and parameters: {'n_estimators': 2470, 'max_depth': 5, 'learning_rate': 0.07853493860504214, 'min_child_weight': 10, 'subsample': 0.7941785933599772, 'colsample_bytree': 0.7910403191451058, 'reg_lambda': 7.868961222315469, 'reg_alpha': 0.24078189265021277}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  96%|█████████▌| 48/50 [09:47<00:05,  2.51s/it]

[I 2026-02-07 18:00:57,378] Trial 40 finished with value: 0.9761574891105681 and parameters: {'n_estimators': 2464, 'max_depth': 6, 'learning_rate': 0.07926812203733094, 'min_child_weight': 10, 'subsample': 0.7955541977134012, 'colsample_bytree': 0.8757776276453806, 'reg_lambda': 9.142780131183944, 'reg_alpha': 0.21755542680335033}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897:  98%|█████████▊| 49/50 [09:51<00:02,  2.92s/it]

[I 2026-02-07 18:01:01,534] Trial 48 finished with value: 0.9725268240966302 and parameters: {'n_estimators': 2294, 'max_depth': 5, 'learning_rate': 0.0741755568313184, 'min_child_weight': 8, 'subsample': 0.7471776892722741, 'colsample_bytree': 0.8690011716063396, 'reg_lambda': 7.864514305599197, 'reg_alpha': 0.2781143635566358}. Best is trial 26 with value: 0.9778974320037014.

Best trial: 26. Best value: 0.977897: 100%|██████████| 50/50 [09:51<00:00, 11.83s/it]

[I 2026-02-07 18:01:01,879] Trial 49 finished with value: 0.9736211956678552 and parameters: {'n_estimators': 2306, 'max_depth': 5, 'learning_rate': 0.0736809571797117, 'min_child_weight': 10, 'subsample': 0.7473783181180905, 'colsample_bytree': 0.8695106417924644, 'reg_lambda': 7.758499950061928, 'reg_alpha': 0.22043585766428087}. Best is trial 26 with value: 0.9778974320037014.

In [31]:
print("Best mean CV R²:", study.best_value)
print("Best hyperparameters:", study.best_params)

Best mean CV R²: 0.9778974320037014
Best hyperparameters: {'n_estimators': 1816, 'max_depth': 6, 'learning_rate': 0.040432659759585106, 'min_child_weight': 3, 'subsample': 0.6646580644242749, 'colsample_bytree': 0.8957206171905826, 'reg_lambda': 3.6867516659251933, 'reg_alpha': 0.05474003456048959}

In [ ]:
#do not follow this result, follow the one below

best_params = study.best_params

final_model_noNM = XGBRegressor(
    **best_params,
    tree_method="hist",
    device="cuda",
    objective="reg:squarederror",
    random_state=42
)

final_model_noNM.fit(X_train_scaled, y_train)

y_pred_log = final_model_noNM.predict(X_test_scaled)

import numpy as np
from sklearn.metrics import r2_score

y_pred_real = np.expm1(y_pred_log)
y_test_real = np.expm1(y_test)

print("Final R² (log scale):", r2_score(y_test, y_pred_log))
print("Final R² (real scale):", r2_score(y_test_real, y_pred_real))

# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred_log)
y_test_real = np.expm1(y_test)

print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

Final R² (log scale): 0.6402587253824688
Final R² (real scale): 0.5296364550359471
R² for DOC on normal: 0.5296364550359471
Final metrics on NORMAL scale (after inverse log):
R²   : 0.5296
MSE  : 1.4668
RMSE : 1.2111
MAE  : 0.7082

In [ ]:
#follow this result, not the above one

best_params = {'n_estimators': 1816, 'max_depth': 6, 'learning_rate': 0.040432659759585106, 'min_child_weight': 3, 'subsample': 0.6646580644242749, 'colsample_bytree': 0.8957206171905826, 'reg_lambda': 3.6867516659251933, 'reg_alpha': 0.05474003456048959}

final_model_noNM = XGBRegressor(
    **best_params,
    tree_method="hist",
    device="cuda",
    objective="reg:squarederror",
    random_state=42
)

final_model_noNM.fit(X_train_scaled, y_train)

y_pred_log = final_model_noNM.predict(X_test_scaled)

import numpy as np
from sklearn.metrics import r2_score

y_pred_real = np.expm1(y_pred_log)
y_test_real = np.expm1(y_test)

print("Final R² (log scale):", r2_score(y_test, y_pred_log))
print("Final R² (real scale):", r2_score(y_test_real, y_pred_real))

# Back-transform predictions and true values
y_pred_real = np.expm1(y_pred_log)
y_test_real = np.expm1(y_test)

print("R² for DOC on normal:", r2_score(y_test_real, y_pred_real))

# ---- Metrics on normal scale ----
mse  = mean_squared_error(y_test_real, y_pred_real)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test_real, y_pred_real)
r2   = r2_score(y_test_real, y_pred_real)

print("Final metrics on NORMAL scale (after inverse log):")
print(f"R²   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")

Final R² (log scale): 0.6511543145523659
Final R² (real scale): 0.5499179803223253
R² for DOC on normal: 0.5499179803223253
Final metrics on NORMAL scale (after inverse log):
R²   : 0.5499
MSE  : 1.4036
RMSE : 1.1847
MAE  : 0.6922

d:\Miniconda3\envs\PyTorchVirtualEnv\Lib\site-packages\xgboost\core.py:750: UserWarning: [00:58:29] WARNING: D:\bld\xgboost-split_1765326833453\work\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

In [ ]:
#Completed 

# #below here is rough work || Consider it as Miscellaneous work. They are not the part of the above code

In [1]:
from datetime import datetime 
import pandas as pd

csv = "D:\Remote Sensing, ERA5, and DOCgit\Stage_2 Statistical Analysis\StatisticsAnalysis\EmptyRowRemovedData\DOC.csv"
df = pd.read_csv(csv)

date_array = df['sample_date'].to_numpy()
date_array

array(['2018-06-18 15:30:00', '2020-06-22 14:50:00',
       '2021-09-20 13:50:00', '2022-11-14 16:55:00',
       '2022-12-19 17:00:00', '2023-07-17 14:15:00',
       '2017-12-20 17:00:00', '2021-03-24 19:25:00',
       '2021-10-20 17:00:00', '2024-02-22 15:55:00',
       '2017-12-20 16:00:00', '2019-02-18 19:40:00',
       '2021-03-24 17:10:00', '2021-10-20 15:20:00',
       '2024-02-22 19:10:00', '2017-10-16 16:30:00',
       '2018-05-14 16:00:00', '2018-06-18 15:30:00',
       '2019-10-21 16:00:00', '2021-08-16 15:00:00',
       '2022-04-18 14:30:00', '2022-11-14 16:00:00',
       '2019-10-21 17:30:00', '2021-08-16 17:00:00',
       '2022-04-18 17:00:00', '2022-11-14 18:00:00',
       '2017-06-21 16:00:00', '2017-12-20 17:00:00',
       '2018-02-21 17:00:00', '2018-03-28 16:00:00',
       '2018-09-19 16:00:00', '2019-04-17 16:00:00',
       '2020-01-27 19:00:00', '2020-02-26 16:00:00',
       '2020-06-17 16:00:00', '2020-07-15 15:40:00',
       '2022-01-26 16:00:00', '2022-05-18 15:00:00',
       '2022-07-20 15:00:00', '2023-01-18 16:00:00',
       '2024-06-26 15:00:00', '2017-07-18 16:15:00',
       '2017-08-15 16:15:00', '2018-10-16 16:15:00',
       '2019-08-20 15:15:00', '2020-02-11 17:14:00',
       '2020-07-22 15:25:00', '2020-08-19 18:00:00',
       '2020-09-15 15:50:00', '2020-10-20 16:03:00',
       '2021-05-18 15:40:00', '2021-07-20 18:53:00',
       '2022-01-18 19:15:00', '2022-04-18 17:20:00',
       '2022-05-03 17:02:00', '2022-06-07 17:25:00',
       '2022-07-05 17:30:00', '2022-10-18 17:51:00',
       '2023-02-07 18:37:00', '2023-06-20 17:14:00',
       '2019-07-16 16:30:00', '2019-08-20 16:35:00',
       '2021-06-15 17:30:00', '2021-07-20 17:40:00',
       '2023-05-16 15:40:00', '2023-06-20 16:35:00',
       '2018-05-15 18:05:00', '2018-06-19 18:20:00',
       '2018-12-18 18:35:00', '2019-02-19 19:10:00',
       '2019-07-16 17:00:00', '2019-08-20 16:00:00',
       '2019-09-17 17:15:00', '2020-04-14 22:15:00',
       '2021-06-15 16:40:00', '2021-07-20 18:05:00',
       '2021-08-17 16:50:00', '2022-02-15 21:10:00',
       '2023-05-16 20:45:00', '2023-06-20 15:30:00',
       '2023-07-18 18:45:00', '2024-03-19 15:45:00',
       '2019-04-17 16:40:00', '2019-09-17 18:00:00',
       '2020-09-16 19:00:00', '2021-04-21 19:45:00',
       '2021-06-25 18:45:00', '2022-02-25 22:00:00',
       '2022-07-25 21:20:00', '2022-11-22 21:25:00',
       '2022-12-20 20:00:00', '2023-05-26 18:15:00',
       '2023-08-29 20:30:00', '2023-09-26 18:30:00',
       '2024-06-07 18:22:00', '2024-06-12 19:30:00',
       '2018-05-15 16:25:00', '2018-06-19 16:40:00',
       '2018-12-18 17:05:00', '2019-02-19 17:10:00',
       '2019-07-16 15:10:00', '2019-08-20 15:00:00',
       '2019-09-17 15:50:00', '2020-04-14 20:55:00',
       '2021-06-15 15:20:00', '2021-07-20 16:15:00',
       '2021-08-17 15:45:00', '2022-02-15 20:00:00',
       '2022-11-15 18:15:00', '2022-12-20 17:50:00',
       '2023-05-16 19:40:00', '2023-06-20 17:30:00',
       '2023-07-18 21:30:00', '2024-03-19 18:00:00',
       '2018-05-15 19:55:00', '2018-06-19 19:50:00',
       '2018-12-18 21:05:00', '2019-02-19 20:35:00',
       '2019-07-16 19:10:00', '2019-08-20 19:25:00',
       '2019-09-17 20:10:00', '2020-04-14 19:45:00',
       '2021-06-15 20:25:00', '2021-07-20 20:10:00',
       '2022-02-15 18:20:00', '2022-11-15 16:45:00',
       '2023-05-16 18:30:00', '2023-06-20 19:45:00',
       '2023-07-18 20:30:00', '2024-03-19 19:25:00',
       '2018-08-13 18:30:00', '2019-02-19 21:05:00',
       '2022-08-22 19:05:00', '2024-05-13 19:00:00',
       '2017-06-19 18:50:00', '2018-08-13 19:20:00',
       '2018-09-17 18:40:00', '2019-02-19 20:20:00',
       '2019-12-16 21:55:00', '2020-09-16 17:45:00',
       '2021-04-19 18:55:00', '2022-06-13 18:35:00',
       '2022-08-22 18:15:00', '2023-02-13 20:25:00',
       '2024-05-13 18:10:00', '2024-06-17 18:55:00',
       '2017-06-19 15:50:00', '2017-07-24 15:30:00',
       '2017-12-06 17:45:00', '2018-06-04 20:30:00',
       '2018-08-08 18:25:00', '2018-10-22 17:25:00',
       '2018-12-11 19:00:00', '2019-02-19 20:20:00',
       '2019-03-11 18:15:00', '2019-03-21 18:03:00',
       '2019-09-17 19:43:00', '2019-10-07 19:50:00',
       '2019-11-06 18:50:00', '2020-07-08 18:45:00',
       '2020-08-12 17:45:00', '2020-11-10 20:50:00',
       '2021-05-04 18:25:00', '2021-06-08 21:30:00',
       '2021-07-13 18:05:00', '2021-12-15 23:18:00',
       '2022-05-24 20:22:00', '2022-10-06 19:50:00',
       '2023-02-08 18:47:00', '2023-04-04 17:45:00',
       '2023-06-23 20:10:00', '2023-11-30 23:04:00',
       '2024-06-12 17:20:00', '2024-07-02 18:30:00',
       '2019-06-04 17:14:00', '2021-06-08 16:14:00',
       '2022-05-04 16:41:00', '2024-06-12 16:59:00',
       '2018-08-13 17:45:00', '2018-11-16 18:14:00',
       '2019-10-17 17:10:00', '2019-11-21 18:08:00',
       '2023-04-19 17:20:00', '2023-11-30 19:45:00',
       '2024-06-12 20:05:00', '2017-06-19 21:15:00',
       '2018-05-15 14:30:00', '2018-06-19 14:55:00',
       '2018-08-13 19:05:00', '2018-12-11 21:30:00',
       '2019-06-19 14:10:00', '2019-09-17 14:20:00',
       '2019-10-17 18:40:00', '2019-11-21 19:10:00',
       '2020-02-19 17:15:00', '2020-09-16 15:30:00',
       '2021-06-23 17:00:00', '2021-08-17 14:10:00',
       '2022-01-19 16:45:00', '2022-11-15 17:10:00',
       '2022-12-20 16:00:00', '2023-04-19 18:45:00',
       '2023-07-18 14:35:00', '2023-09-26 19:10:00',
       '2024-03-19 14:30:00', '2024-06-12 19:15:00',
       '2018-03-26 17:30:00', '2018-04-20 17:57:00',
       '2018-08-08 18:35:00', '2019-07-24 17:30:00',
       '2019-10-02 18:50:00', '2019-11-21 21:20:00',
       '2020-02-04 21:00:00', '2020-07-08 18:02:00',
       '2021-03-30 17:50:00', '2022-02-08 19:00:00',
       '2022-11-15 19:13:00', '2023-07-18 17:48:00',
       '2018-04-20 17:04:00', '2018-08-28 16:35:00',
       '2018-09-17 17:36:00', '2018-11-06 18:44:00',
       '2019-04-10 16:45:00', '2019-07-09 16:00:00',
       '2019-11-06 18:55:00', '2020-02-19 17:47:00',
       '2020-09-16 16:10:00', '2021-05-04 16:11:00',
       '2023-06-13 17:15:00', '2023-08-02 15:38:00',
       '2023-09-06 16:26:00', '2024-05-08 15:40:00',
       '2018-04-20 19:04:00', '2019-06-04 16:33:00',
       '2020-06-03 16:06:00', '2020-10-21 16:00:00',
       '2021-06-08 15:35:00', '2022-05-04 17:17:00',
       '2024-06-12 16:28:00', '2018-08-28 17:03:00',
       '2018-09-17 17:02:00', '2018-11-06 18:13:00',
       '2019-04-10 17:32:00', '2019-07-09 16:33:00',
       '2019-11-06 19:44:00', '2020-02-19 18:49:00',
       '2020-07-28 17:10:00', '2020-09-16 17:11:00',
       '2021-05-04 16:48:00', '2023-05-24 18:32:00',
       '2023-06-13 16:45:00', '2023-08-02 16:16:00',
       '2023-09-06 17:15:00', '2024-05-08 16:15:00',
       '2018-04-20 17:15:00', '2019-06-04 17:59:00',
       '2020-06-03 17:28:00', '2020-10-21 17:16:00',
       '2021-06-08 17:02:00', '2022-05-04 15:15:00',
       '2024-06-12 15:55:00', '2018-08-28 17:31:00',
       '2018-09-17 16:35:00', '2018-11-06 17:44:00',
       '2019-04-10 18:16:00', '2019-07-09 17:03:00',
       '2019-11-06 20:44:00', '2020-02-19 19:30:00',
       '2020-09-16 19:55:00', '2021-05-04 17:15:00',
       '2023-05-24 17:43:00', '2023-06-13 16:00:00',
       '2023-08-02 17:03:00', '2023-09-06 18:06:00',
       '2024-05-08 16:50:00', '2019-06-04 19:47:00',
       '2019-08-28 16:55:00', '2020-06-03 17:55:00',
       '2021-05-19 16:05:00', '2022-02-08 18:04:00',
       '2024-06-12 17:57:00', '2017-06-19 16:20:00',
       '2018-08-13 15:45:00', '2018-09-17 16:10:00',
       '2019-02-19 18:20:00', '2019-12-16 18:35:00',
       '2020-09-16 16:35:00', '2021-04-19 16:15:00',
       '2022-06-13 16:05:00', '2022-08-22 16:00:00',
       '2023-02-13 17:55:00', '2024-05-13 15:55:00',
       '2024-06-17 16:30:00', '2019-03-11 16:45:00',
       '2019-06-04 19:11:00', '2019-08-28 16:17:00',
       '2020-06-03 18:20:00', '2021-05-19 16:33:00',
       '2022-02-08 18:26:00', '2024-06-12 18:25:00',
       '2018-12-31 21:52:00', '2020-07-08 18:20:00',
       '2021-03-30 16:35:00', '2022-02-08 18:06:00',
       '2022-11-15 17:47:00', '2023-07-18 15:14:00',
       '2024-03-19 16:19:00', '2019-06-04 18:36:00',
       '2019-08-28 15:37:00', '2020-06-03 18:53:00',
       '2020-11-20 20:00:00', '2021-05-19 17:12:00',
       '2021-09-21 15:46:00', '2022-02-08 19:11:00',
       '2024-06-12 18:57:00', '2018-12-31 22:47:00',
       '2020-07-08 15:42:00', '2021-03-30 15:34:00',
       '2022-02-08 16:51:00', '2022-11-15 17:19:00',
       '2023-07-18 15:55:00', '2018-12-31 19:49:00',
       '2020-07-08 17:08:00', '2021-03-30 18:47:00',
       '2022-02-08 20:28:00', '2022-11-15 18:28:00',
       '2024-03-19 18:25:00', '2017-10-02 19:15:00',
       '2018-04-20 19:44:00', '2018-07-09 19:30:00',
       '2019-10-07 17:30:00', '2019-11-06 17:06:00',
       '2020-07-08 15:40:00', '2020-08-12 16:15:00',
       '2020-10-06 18:20:00', '2020-11-10 18:50:00',
       '2021-05-04 15:50:00', '2021-06-08 19:30:00',
       '2021-07-13 20:00:00', '2022-03-10 17:15:00',
       '2022-10-06 17:15:00', '2023-02-08 21:00:00',
       '2023-04-04 19:30:00', '2017-10-02 18:40:00',
       '2018-07-09 19:05:00', '2019-10-07 19:00:00',
       '2019-11-06 17:40:00', '2020-07-08 16:15:00',
       '2020-08-12 16:45:00', '2020-10-06 19:00:00',
       '2020-11-10 19:30:00', '2021-05-04 16:20:00',
       '2021-06-08 20:15:00', '2021-07-13 21:00:00',
       '2022-03-10 18:45:00', '2022-10-06 17:45:00',
       '2023-02-08 21:35:00', '2023-04-04 20:45:00',
       '2017-10-02 20:10:00', '2018-07-09 20:30:00',
       '2019-05-10 16:36:00', '2018-12-06 19:30:00',
       '2019-04-25 18:45:00', '2020-06-18 19:05:00',
       '2020-11-25 18:50:00', '2022-07-13 15:57:00',
       '2017-10-02 17:50:00', '2017-11-06 20:08:00',
       '2018-07-09 17:50:00', '2017-06-19 17:30:00',
       '2017-07-24 17:30:00', '2017-12-06 18:30:00',
       '2018-06-04 19:06:00', '2018-08-08 17:35:00',
       '2018-10-22 18:35:00', '2019-03-11 16:15:00',
       '2022-07-13 16:26:00', '2021-09-01 19:44:00',
       '2022-07-13 17:42:00', '2022-09-01 17:50:00',
       '2022-10-06 17:10:00', '2017-06-19 18:55:00',
       '2017-07-24 19:45:00', '2017-10-02 16:05:00',
       '2018-03-26 16:45:00', '2018-07-09 16:10:00',
       '2021-06-23 17:35:00', '2022-05-24 17:27:00',
       '2022-06-28 16:35:00', '2022-09-26 16:51:00',
       '2021-06-23 16:56:00', '2022-05-24 18:03:00',
       '2022-06-28 15:56:00', '2022-09-26 16:21:00',
       '2021-06-23 18:55:00', '2022-05-24 16:14:00',
       '2022-06-28 17:14:00', '2022-09-26 17:30:00',
       '2021-06-23 16:20:00', '2022-05-24 18:35:00',
       '2022-06-28 15:19:00', '2022-09-26 15:44:00',
       '2019-10-02 16:01:00', '2020-07-13 15:08:00',
       '2021-08-17 14:50:00', '2022-09-06 13:48:00',
       '2023-08-22 14:12:00', '2023-09-06 13:53:00',
       '2024-06-17 14:00:00', '2021-09-16 15:18:00',
       '2021-09-16 14:50:00', '2017-08-28 17:30:00',
       '2017-08-28 23:30:00', '2017-08-29 05:30:00',
       '2017-09-27 13:00:00', '2018-04-25 10:30:00',
       '2018-05-15 18:30:00', '2018-05-15 20:30:00',
       '2018-05-16 02:30:00', '2018-05-16 06:30:00',
       '2019-10-02 16:49:00', '2020-07-13 15:54:00',
       '2022-09-06 14:33:00', '2023-08-22 14:56:00',
       '2023-09-06 14:45:00', '2024-06-17 14:23:00',
       '2017-08-08 16:05:00', '2018-06-04 16:23:00',
       '2018-06-19 17:11:00', '2018-07-24 16:25:00',
       '2018-11-06 19:20:00', '2019-06-04 17:07:00',
       '2020-02-04 18:33:00', '2020-08-12 19:57:00',
       '2017-08-08 18:35:00', '2018-06-19 19:24:00',
       '2018-07-24 18:40:00', '2018-11-06 22:48:00',
       '2019-06-04 19:10:00', '2019-07-09 19:55:00',
       '2020-08-12 17:40:00', '2021-09-16 16:01:00',
       '2023-09-21 19:41:00', '2023-10-26 17:25:00',
       '2019-10-02 17:20:00', '2020-07-13 16:27:00',
       '2021-08-17 16:06:00', '2022-09-06 14:52:00',
       '2023-08-22 15:41:00', '2023-09-06 15:31:00',
       '2024-06-17 15:00:00', '2017-08-08 18:02:00',
       '2018-06-19 19:01:00', '2018-07-24 18:15:00',
       '2018-11-06 22:02:00', '2019-06-04 18:43:00',
       '2019-07-09 19:40:00', '2020-08-12 17:58:00',
       '2017-08-08 16:38:00', '2018-06-04 16:40:00',
       '2018-06-19 17:29:00', '2018-07-24 16:40:00',
       '2018-11-06 19:45:00', '2018-08-08 18:00:00',
       '2018-08-08 21:00:00', '2018-08-09 01:00:00',
       '2018-08-09 06:00:00', '2018-08-28 17:45:00',
       '2018-08-28 22:45:00', '2018-08-29 04:45:00',
       '2019-08-08 16:20:00', '2019-12-06 19:20:00',
       '2020-08-12 15:46:00', '2019-08-08 17:24:00',
       '2019-12-06 19:10:00', '2020-08-12 15:25:00',
       '2020-11-10 17:30:00', '2021-06-08 23:15:00',
       '2021-07-13 16:30:00', '2021-12-10 20:15:00',
       '2017-06-19 20:25:00', '2017-07-24 19:00:00',
       '2017-12-06 20:45:00', '2018-06-04 17:30:00',
       '2018-08-08 15:40:00', '2018-10-22 20:00:00',
       '2021-08-17 16:30:00', '2022-09-06 15:37:00',
       '2023-08-22 16:20:00', '2017-08-08 18:15:00',
       '2018-06-19 19:15:00', '2018-07-24 18:30:00',
       '2018-11-06 22:20:00', '2019-10-02 17:50:00',
       '2020-07-13 16:55:00', '2022-09-06 15:16:00',
       '2023-08-22 16:51:00', '2024-06-17 17:26:00',
       '2018-05-15 18:15:00', '2018-06-19 18:25:00',
       '2019-06-19 18:15:00', '2019-09-17 17:40:00',
       '2020-02-19 19:55:00', '2020-09-16 20:05:00',
       '2021-03-25 17:30:00', '2021-08-17 17:55:00',
       '2022-11-15 20:00:00', '2023-07-18 17:55:00',
       '2024-03-19 18:05:00', '2017-08-08 16:52:00',
       '2018-06-04 17:13:00', '2018-06-19 17:43:00',
       '2018-07-24 16:55:00', '2018-11-06 20:10:00',
       '2019-04-10 17:32:00', '2019-06-04 17:31:00',
       '2019-07-09 18:20:00', '2020-08-12 18:58:00',
       '2018-06-19 19:42:00', '2018-07-24 18:55:00',
       '2018-11-06 23:05:00', '2020-08-12 19:24:00',
       '2017-08-08 17:08:00', '2018-06-19 18:15:00',
       '2018-07-24 17:10:00', '2018-11-06 21:05:00',
       '2017-08-08 17:42:00', '2018-06-04 17:58:00',
       '2018-06-19 18:42:00', '2018-07-24 17:50:00',
       '2018-11-06 21:25:00', '2019-06-04 18:24:00',
       '2019-07-09 18:47:00', '2020-02-04 19:31:00',
       '2020-08-12 18:25:00', '2017-08-08 17:23:00',
       '2018-06-04 17:43:00', '2018-06-19 18:29:00',
       '2018-07-24 17:25:00', '2018-11-06 21:25:00',
       '2019-10-02 18:33:00', '2020-07-13 17:27:00',
       '2021-08-17 17:47:00', '2023-08-22 18:36:00',
       '2023-09-06 18:12:00', '2024-06-17 15:24:00',
       '2017-06-19 21:05:00', '2017-07-24 20:30:00',
       '2018-03-26 19:50:00', '2018-05-15 15:55:00',
       '2018-07-09 19:15:00', '2018-10-17 15:22:00',
       '2018-10-22 18:58:00', '2019-03-11 14:45:00',
       '2019-11-06 21:30:00', '2020-06-23 16:35:00',
       '2020-07-08 19:30:00', '2020-08-12 19:35:00',
       '2020-10-06 21:40:00', '2020-11-10 22:25:00',
       '2021-05-04 21:45:00', '2021-06-08 16:45:00',
       '2021-07-13 15:30:00', '2022-10-06 22:25:00',
       '2023-09-06 16:25:00', '2024-04-18 17:10:00',
       '2018-08-08 19:06:00', '2018-08-13 18:11:00',
       '2018-09-27 19:15:00', '2019-09-17 17:14:00',
       '2021-08-02 17:16:00', '2022-09-06 15:28:00',
       '2023-08-22 16:10:00', '2023-08-22 20:00:00',
       '2023-09-06 15:51:00', '2023-10-26 17:41:00',
       '2023-11-20 23:00:00', '2024-02-28 20:38:00',
       '2024-06-17 18:32:00', '2020-07-13 16:17:00',
       '2021-08-17 14:55:00', '2022-09-06 14:29:00',
       '2017-06-19 16:11:00', '2017-07-24 16:45:00',
       '2018-06-04 15:51:00', '2018-08-08 14:50:00',
       '2018-10-22 15:05:00', '2018-07-09 17:52:00',
       '2019-03-11 17:15:00', '2021-08-02 17:30:00',
       '2022-02-08 19:55:00', '2023-09-06 18:16:00',
       '2024-04-18 18:56:00', '2018-08-13 17:31:00',
       '2018-09-27 18:24:00', '2021-08-02 15:50:00',
       '2021-10-11 15:40:00', '2023-08-22 14:26:00',
       '2023-09-06 14:17:00', '2018-07-09 14:43:00',
       '2019-03-11 21:34:00', '2021-08-02 15:15:00',
       '2022-02-08 18:25:00', '2023-09-06 15:13:00',
       '2024-04-18 16:20:00', '2018-07-09 16:35:00',
       '2019-03-11 20:18:00', '2021-08-02 18:15:00',
       '2022-02-08 20:55:00', '2019-09-17 19:59:00',
       '2021-08-02 18:07:00', '2021-10-11 14:20:00',
       '2023-08-22 14:28:00', '2023-09-06 14:02:00',
       '2023-08-22 18:33:00', '2023-10-26 15:57:00',
       '2023-11-20 21:26:00', '2024-02-28 19:15:00',
       '2020-02-19 20:40:00', '2020-11-10 20:00:00',
       '2020-02-19 19:51:00', '2020-11-10 20:25:00',
       '2020-02-19 19:15:00', '2020-11-10 18:50:00',
       '2020-02-19 19:32:00', '2020-11-10 19:55:00',
       '2019-09-17 17:58:00', '2020-07-28 15:43:00',
       '2023-08-22 17:13:00', '2023-09-06 16:22:00',
       '2018-07-09 15:40:00', '2019-10-07 17:15:00',
       '2020-02-19 19:55:00', '2021-08-02 15:13:00',
       '2021-10-11 16:46:00', '2020-02-19 20:15:00',
       '2023-10-19 22:00:00', '2020-02-19 18:47:00',
       '2020-11-10 19:05:00', '2023-10-19 21:10:00',
       '2020-02-19 17:57:00', '2020-02-19 18:10:00',
       '2020-11-10 17:45:00', '2020-02-19 17:25:00',
       '2020-11-10 17:10:00', '2020-02-19 17:13:00',
       '2020-11-10 17:35:00', '2021-05-19 19:05:00',
       '2022-01-19 19:48:00', '2022-01-19 20:00:00',
       '2022-11-15 20:30:00', '2022-11-15 20:46:00',
       '2023-03-15 18:47:00', '2023-03-15 19:00:00',
       '2023-07-18 18:54:00', '2023-07-18 19:10:00',
       '2024-03-14 15:10:00', '2024-06-12 17:53:00',
       '2019-06-19 16:01:00', '2021-05-19 16:40:00',
       '2022-01-19 16:24:00', '2022-01-19 17:17:00',
       '2022-11-15 17:36:00', '2022-11-15 17:58:00',
       '2023-03-15 16:00:00', '2023-03-15 16:25:00',
       '2023-07-18 15:30:00', '2023-07-18 15:50:00',
       '2024-03-14 14:23:00', '2024-06-12 14:57:00',
       '2020-02-19 15:47:00', '2020-11-10 16:25:00',
       '2021-05-19 18:30:00', '2022-01-19 18:57:00',
       '2022-01-19 19:09:00', '2022-11-15 19:45:00',
       '2022-11-15 20:01:00', '2023-03-15 17:57:00',
       '2023-03-15 18:13:00', '2023-07-18 17:30:00',
       '2023-07-18 17:52:00', '2024-03-14 16:21:00',
       '2024-06-12 17:10:00', '2021-05-19 17:26:00',
       '2022-01-19 17:45:00', '2022-01-19 18:03:00',
       '2022-08-17 17:00:00', '2022-08-17 17:17:00',
       '2022-11-15 18:45:00', '2022-11-15 19:00:00',
       '2023-03-15 17:00:00', '2023-03-15 17:17:00',
       '2023-07-18 16:30:00', '2023-07-18 16:51:00',
       '2024-03-14 17:00:00', '2024-06-12 16:00:00',
       '2018-02-12 20:30:00', '2022-02-08 19:30:00',
       '2023-08-15 17:50:00', '2022-07-21 17:55:00',
       '2023-10-19 16:55:00', '2022-05-04 12:50:00',
       '2024-05-08 12:35:00', '2018-02-12 21:00:00',
       '2020-08-10 17:30:00', '2022-02-08 20:15:00',
       '2023-08-15 18:30:00', '2024-06-12 17:50:00',
       '2024-06-12 17:22:00', '2018-02-12 19:00:00',
       '2022-02-08 17:45:00', '2022-07-20 18:57:00',
       '2023-06-20 21:38:00', '2024-06-12 16:15:00',
       '2022-07-20 18:10:00', '2023-06-20 21:08:00',
       '2024-06-12 15:22:00', '2020-08-10 15:30:00',
       '2022-02-08 16:50:00', '2023-08-15 14:15:00',
       '2020-08-10 16:00:00', '2022-02-08 17:30:00',
       '2023-08-15 14:50:00', '2020-11-05 22:20:00',
       '2018-02-12 17:45:00', '2022-02-08 16:45:00',
       '2023-08-15 17:00:00', '2020-08-10 17:00:00',
       '2022-02-08 18:15:00', '2023-08-15 15:30:00',
       '2022-05-04 15:31:00', '2022-08-02 14:19:00',
       '2024-05-08 15:24:00', '2022-05-04 14:34:00',
       '2022-08-02 13:15:00', '2024-05-08 14:28:00',
       '2020-08-10 17:20:00', '2022-02-08 19:10:00',
       '2023-08-15 17:05:00', '2022-05-24 17:32:00',
       '2022-05-24 20:10:00', '2022-05-24 19:32:00',
       '2020-08-10 18:05:00', '2022-02-08 20:00:00',
       '2023-08-15 17:50:00', '2023-06-20 17:33:00',
       '2024-06-12 20:40:00', '2024-06-12 20:35:00',
       '2022-07-21 14:50:00', '2023-10-19 14:30:00',
       '2022-07-28 15:35:00', '2017-05-03 15:45:00',
       '2020-08-05 14:00:00', '2022-05-04 14:45:00',

In [ ]:
print(max(date_array))
print(min(date_array))

2024-07-02 18:30:00
2017-05-03 15:08:00